-- =====================================================
-- MIGRAÇÃO 17: VACUUM E ANÁLISE FINAL - PARTE 6
-- =====================================================
-- Descrição: Análise e atualização de estatísticas
-- Estimativa: ~1 minuto para executar

-- Atualizar estatísticas das tabelas principais
ANALYZE profiles;
ANALYZE aulas;
ANALYZE portfolios;
ANALYZE user_points_log;
ANALYZE achievements;

-- Verificar índices criados
SELECT 
    schemaname,
    tablename,
    indexname,
    indexdef
FROM pg_indexes
WHERE schemaname = 'public'
    AND indexname LIKE 'idx_%'
ORDER BY tablename, indexname;


| schemaname | tablename                       | indexname                                    | indexdef                                                                                                                                                 |
| ---------- | ------------------------------- | -------------------------------------------- | -------------------------------------------------------------------------------------------------------------------------------------------------------- |
| public     | achievements                    | idx_achievements_active                      | CREATE INDEX idx_achievements_active ON public.achievements USING btree (is_active)                                                                      |
| public     | achievements                    | idx_achievements_category                    | CREATE INDEX idx_achievements_category ON public.achievements USING btree (category)                                                                     |
| public     | achievements                    | idx_achievements_is_active                   | CREATE INDEX idx_achievements_is_active ON public.achievements USING btree (is_active) WHERE (is_active = true)                                          |
| public     | achievements                    | idx_achievements_requirement_type            | CREATE INDEX idx_achievements_requirement_type ON public.achievements USING btree (requirement_type)                                                     |
| public     | achievements_progress           | idx_achievement_progress                     | CREATE INDEX idx_achievement_progress ON public.achievements_progress USING btree (user_id, is_completed, updated_at DESC)                               |
| public     | achievements_progress           | idx_achievements_progress_user_id            | CREATE INDEX idx_achievements_progress_user_id ON public.achievements_progress USING btree (user_id)                                                     |
| public     | alpha_aluno_badges              | idx_alpha_aluno_badges_aluno                 | CREATE INDEX idx_alpha_aluno_badges_aluno ON public.alpha_aluno_badges USING btree (aluno_id)                                                            |
| public     | alpha_aluno_badges              | idx_alpha_aluno_badges_aluno_id              | CREATE INDEX idx_alpha_aluno_badges_aluno_id ON public.alpha_aluno_badges USING btree (aluno_id)                                                         |
| public     | alpha_aluno_badges              | idx_alpha_aluno_badges_badge                 | CREATE INDEX idx_alpha_aluno_badges_badge ON public.alpha_aluno_badges USING btree (badge_id)                                                            |
| public     | alpha_aluno_badges              | idx_alpha_aluno_badges_badge_id              | CREATE INDEX idx_alpha_aluno_badges_badge_id ON public.alpha_aluno_badges USING btree (badge_id)                                                         |
| public     | alpha_aluno_badges              | idx_alpha_aluno_badges_data                  | CREATE INDEX idx_alpha_aluno_badges_data ON public.alpha_aluno_badges USING btree (data_obtencao DESC)                                                   |
| public     | alpha_aluno_badges              | idx_alpha_aluno_badges_destacada             | CREATE INDEX idx_alpha_aluno_badges_destacada ON public.alpha_aluno_badges USING btree (destacada)                                                       |
| public     | alpha_aluno_desafios            | idx_alpha_aluno_desafios_aluno               | CREATE INDEX idx_alpha_aluno_desafios_aluno ON public.alpha_aluno_desafios USING btree (aluno_id)                                                        |
| public     | alpha_aluno_desafios            | idx_alpha_aluno_desafios_aluno_id            | CREATE INDEX idx_alpha_aluno_desafios_aluno_id ON public.alpha_aluno_desafios USING btree (aluno_id)                                                     |
| public     | alpha_aluno_desafios            | idx_alpha_aluno_desafios_desafio             | CREATE INDEX idx_alpha_aluno_desafios_desafio ON public.alpha_aluno_desafios USING btree (desafio_id)                                                    |
| public     | alpha_aluno_desafios            | idx_alpha_aluno_desafios_desafio_id          | CREATE INDEX idx_alpha_aluno_desafios_desafio_id ON public.alpha_aluno_desafios USING btree (desafio_id)                                                 |
| public     | alpha_aluno_desafios            | idx_alpha_aluno_desafios_status              | CREATE INDEX idx_alpha_aluno_desafios_status ON public.alpha_aluno_desafios USING btree (status)                                                         |
| public     | alpha_aula_progresso            | idx_alpha_aula_progresso_aluno_id            | CREATE INDEX idx_alpha_aula_progresso_aluno_id ON public.alpha_aula_progresso USING btree (aluno_id)                                                     |
| public     | alpha_aula_progresso            | idx_alpha_aula_progresso_aluno_status        | CREATE INDEX idx_alpha_aula_progresso_aluno_status ON public.alpha_aula_progresso USING btree (aluno_id, status)                                         |
| public     | alpha_aula_progresso            | idx_alpha_aula_progresso_aula_id             | CREATE INDEX idx_alpha_aula_progresso_aula_id ON public.alpha_aula_progresso USING btree (aula_id)                                                       |
| public     | alpha_aula_progresso            | idx_alpha_aula_progresso_status              | CREATE INDEX idx_alpha_aula_progresso_status ON public.alpha_aula_progresso USING btree (status)                                                         |
| public     | alpha_badges                    | idx_alpha_badges_ativo                       | CREATE INDEX idx_alpha_badges_ativo ON public.alpha_badges USING btree (ativo) WHERE (ativo = true)                                                      |
| public     | alpha_badges                    | idx_alpha_badges_categoria                   | CREATE INDEX idx_alpha_badges_categoria ON public.alpha_badges USING btree (categoria)                                                                   |
| public     | alpha_badges                    | idx_alpha_badges_raridade                    | CREATE INDEX idx_alpha_badges_raridade ON public.alpha_badges USING btree (raridade)                                                                     |
| public     | alpha_badges                    | idx_badges_categoria                         | CREATE INDEX idx_badges_categoria ON public.alpha_badges USING btree (categoria)                                                                         |
| public     | alpha_badges                    | idx_badges_pilar                             | CREATE INDEX idx_badges_pilar ON public.alpha_badges USING btree (pilar_alpha)                                                                           |
| public     | alpha_badges                    | idx_badges_raridade                          | CREATE INDEX idx_badges_raridade ON public.alpha_badges USING btree (raridade)                                                                           |
| public     | alpha_badges                    | idx_badges_secreto                           | CREATE INDEX idx_badges_secreto ON public.alpha_badges USING btree (secreto) WHERE (secreto = true)                                                      |
| public     | alpha_celebracoes               | idx_alpha_celebracoes_aluno_id               | CREATE INDEX idx_alpha_celebracoes_aluno_id ON public.alpha_celebracoes USING btree (aluno_id)                                                           |
| public     | alpha_celebracoes               | idx_alpha_celebracoes_created_at             | CREATE INDEX idx_alpha_celebracoes_created_at ON public.alpha_celebracoes USING btree (created_at DESC)                                                  |
| public     | alpha_celebracoes               | idx_alpha_celebracoes_estudante_id           | CREATE INDEX idx_alpha_celebracoes_estudante_id ON public.alpha_celebracoes USING btree (estudante_id)                                                   |
| public     | alpha_celebracoes               | idx_alpha_celebracoes_tipo                   | CREATE INDEX idx_alpha_celebracoes_tipo ON public.alpha_celebracoes USING btree (tipo)                                                                   |
| public     | alpha_celebracoes               | idx_celebracoes_data                         | CREATE INDEX idx_celebracoes_data ON public.alpha_celebracoes USING btree (created_at DESC)                                                              |
| public     | alpha_celebracoes               | idx_celebracoes_publico                      | CREATE INDEX idx_celebracoes_publico ON public.alpha_celebracoes USING btree (publico) WHERE (publico = true)                                            |
| public     | alpha_competencias              | idx_alpha_competencias_ativo                 | CREATE INDEX idx_alpha_competencias_ativo ON public.alpha_competencias USING btree (ativo) WHERE (ativo = true)                                          |
| public     | alpha_competencias              | idx_alpha_competencias_metodologia           | CREATE INDEX idx_alpha_competencias_metodologia ON public.alpha_competencias USING btree (metodologia_id)                                                |
| public     | alpha_competencias              | idx_alpha_competencias_metodologia_id        | CREATE INDEX idx_alpha_competencias_metodologia_id ON public.alpha_competencias USING btree (metodologia_id)                                             |
| public     | alpha_desafios                  | idx_alpha_desafios_ativo                     | CREATE INDEX idx_alpha_desafios_ativo ON public.alpha_desafios USING btree (ativo)                                                                       |
| public     | alpha_desafios                  | idx_alpha_desafios_categoria                 | CREATE INDEX idx_alpha_desafios_categoria ON public.alpha_desafios USING btree (categoria)                                                               |
| public     | alpha_desafios                  | idx_alpha_desafios_codigo                    | CREATE INDEX idx_alpha_desafios_codigo ON public.alpha_desafios USING btree (codigo)                                                                     |
| public     | alpha_desafios                  | idx_alpha_desafios_datas                     | CREATE INDEX idx_alpha_desafios_datas ON public.alpha_desafios USING btree (data_inicio, data_fim)                                                       |
| public     | alpha_desafios                  | idx_alpha_desafios_tipo                      | CREATE INDEX idx_alpha_desafios_tipo ON public.alpha_desafios USING btree (tipo)                                                                         |
| public     | alpha_metodologias              | idx_alpha_metodologias_ativo                 | CREATE INDEX idx_alpha_metodologias_ativo ON public.alpha_metodologias USING btree (ativo) WHERE (ativo = true)                                          |
| public     | alpha_metodologias              | idx_alpha_metodologias_codigo                | CREATE INDEX idx_alpha_metodologias_codigo ON public.alpha_metodologias USING btree (codigo)                                                             |
| public     | alpha_progresso                 | idx_alpha_progresso_user                     | CREATE INDEX idx_alpha_progresso_user ON public.alpha_progresso USING btree (user_id)                                                                    |
| public     | alpha_ranking                   | idx_alpha_ranking_aluno_id                   | CREATE INDEX idx_alpha_ranking_aluno_id ON public.alpha_ranking USING btree (aluno_id)                                                                   |
| public     | alpha_ranking                   | idx_alpha_ranking_estudante_id               | CREATE INDEX idx_alpha_ranking_estudante_id ON public.alpha_ranking USING btree (estudante_id)                                                           |
| public     | alpha_ranking                   | idx_alpha_ranking_posicao                    | CREATE INDEX idx_alpha_ranking_posicao ON public.alpha_ranking USING btree (posicao)                                                                     |
| public     | alpha_ranking                   | idx_alpha_ranking_turma_id                   | CREATE INDEX idx_alpha_ranking_turma_id ON public.alpha_ranking USING btree (turma_id)                                                                   |
| public     | alpha_ranking                   | idx_ranking_estudante                        | CREATE INDEX idx_ranking_estudante ON public.alpha_ranking USING btree (estudante_id)                                                                    |
| public     | alpha_ranking                   | idx_ranking_periodo                          | CREATE INDEX idx_ranking_periodo ON public.alpha_ranking USING btree (periodo, data_fim DESC)                                                            |
| public     | alpha_ranking                   | idx_ranking_posicao                          | CREATE INDEX idx_ranking_posicao ON public.alpha_ranking USING btree (posicao)                                                                           |
| public     | alpha_submissoes                | idx_alpha_submissoes_aluno_id                | CREATE INDEX idx_alpha_submissoes_aluno_id ON public.alpha_submissoes USING btree (aluno_id)                                                             |
| public     | alpha_submissoes                | idx_alpha_submissoes_data                    | CREATE INDEX idx_alpha_submissoes_data ON public.alpha_submissoes USING btree (data_submissao DESC)                                                      |
| public     | alpha_submissoes                | idx_alpha_submissoes_desafio                 | CREATE INDEX idx_alpha_submissoes_desafio ON public.alpha_submissoes USING btree (desafio_id)                                                            |
| public     | alpha_submissoes                | idx_alpha_submissoes_desafio_id              | CREATE INDEX idx_alpha_submissoes_desafio_id ON public.alpha_submissoes USING btree (desafio_id)                                                         |
| public     | alpha_submissoes                | idx_alpha_submissoes_status                  | CREATE INDEX idx_alpha_submissoes_status ON public.alpha_submissoes USING btree (status)                                                                 |
| public     | alpha_submissoes                | idx_alpha_submissoes_user                    | CREATE INDEX idx_alpha_submissoes_user ON public.alpha_submissoes USING btree (user_id)                                                                  |
| public     | alpha_submissoes                | idx_alpha_submissoes_user_id                 | CREATE INDEX idx_alpha_submissoes_user_id ON public.alpha_submissoes USING btree (user_id)                                                               |
| public     | alpha_xp_historico              | idx_alpha_xp_historico_aluno_id              | CREATE INDEX idx_alpha_xp_historico_aluno_id ON public.alpha_xp_historico USING btree (aluno_id)                                                         |
| public     | alpha_xp_historico              | idx_alpha_xp_historico_data                  | CREATE INDEX idx_alpha_xp_historico_data ON public.alpha_xp_historico USING btree (created_at DESC)                                                      |
| public     | alpha_xp_historico              | idx_alpha_xp_historico_estudante_id          | CREATE INDEX idx_alpha_xp_historico_estudante_id ON public.alpha_xp_historico USING btree (estudante_id)                                                 |
| public     | alpha_xp_historico              | idx_xp_historico_data                        | CREATE INDEX idx_xp_historico_data ON public.alpha_xp_historico USING btree (created_at DESC)                                                            |
| public     | alpha_xp_historico              | idx_xp_historico_estudante                   | CREATE INDEX idx_xp_historico_estudante ON public.alpha_xp_historico USING btree (estudante_id)                                                          |
| public     | alpha_xp_historico              | idx_xp_historico_level_up                    | CREATE INDEX idx_xp_historico_level_up ON public.alpha_xp_historico USING btree (level_up) WHERE (level_up = true)                                       |
| public     | alunos                          | idx_alunos_instrumento                       | CREATE INDEX idx_alunos_instrumento ON public.alunos USING btree (instrumento_id)                                                                        |
| public     | audit_activities                | idx_audit_action_time                        | CREATE INDEX idx_audit_action_time ON public.audit_activities USING btree (action, created_at DESC)                                                      |
| public     | audit_activities                | idx_audit_activities_created_at              | CREATE INDEX idx_audit_activities_created_at ON public.audit_activities USING btree (created_at DESC)                                                    |
| public     | audit_activities                | idx_audit_resource                           | CREATE INDEX idx_audit_resource ON public.audit_activities USING btree (resource, resource_id)                                                           |
| public     | audit_activities                | idx_audit_severity                           | CREATE INDEX idx_audit_severity ON public.audit_activities USING btree (severity, created_at DESC) WHERE (severity <> 'info'::text)                      |
| public     | audit_activities                | idx_audit_user_time                          | CREATE INDEX idx_audit_user_time ON public.audit_activities USING btree (user_id, created_at DESC)                                                       |
| public     | aula_atividades                 | idx_aula_atividades_aula_id                  | CREATE INDEX idx_aula_atividades_aula_id ON public.aula_atividades USING btree (aula_id)                                                                 |
| public     | aula_avaliacoes                 | idx_aula_avaliacoes_aluno_id                 | CREATE INDEX idx_aula_avaliacoes_aluno_id ON public.aula_avaliacoes USING btree (aluno_id)                                                               |
| public     | aula_avaliacoes                 | idx_aula_avaliacoes_aula_id                  | CREATE INDEX idx_aula_avaliacoes_aula_id ON public.aula_avaliacoes USING btree (aula_id)                                                                 |
| public     | aula_checklist                  | idx_aula_checklist_aula_id                   | CREATE INDEX idx_aula_checklist_aula_id ON public.aula_checklist USING btree (aula_id)                                                                   |
| public     | aula_checklist                  | idx_aula_checklist_feito                     | CREATE INDEX idx_aula_checklist_feito ON public.aula_checklist USING btree (feito)                                                                       |
| public     | aula_checklist                  | idx_aula_checklist_tipo                      | CREATE INDEX idx_aula_checklist_tipo ON public.aula_checklist USING btree (tipo)                                                                         |
| public     | aula_criterios_avaliacao        | idx_aula_criterios_aula_id                   | CREATE INDEX idx_aula_criterios_aula_id ON public.aula_criterios_avaliacao USING btree (aula_id)                                                         |
| public     | aula_desafio_alpha              | idx_aula_desafio_alpha_aula_id               | CREATE INDEX idx_aula_desafio_alpha_aula_id ON public.aula_desafio_alpha USING btree (aula_id)                                                           |
| public     | aula_desafios                   | idx_aula_desafios_aula_id                    | CREATE INDEX idx_aula_desafios_aula_id ON public.aula_desafios USING btree (aula_id)                                                                     |
| public     | aula_feedback                   | idx_aula_feedback_aula_id                    | CREATE INDEX idx_aula_feedback_aula_id ON public.aula_feedback USING btree (aula_id)                                                                     |
| public     | aula_feedbacks                  | idx_aula_feedbacks_aula_id                   | CREATE INDEX idx_aula_feedbacks_aula_id ON public.aula_feedbacks USING btree (aula_id)                                                                   |
| public     | aula_materiais                  | idx_aula_materiais_aula_id                   | CREATE INDEX idx_aula_materiais_aula_id ON public.aula_materiais USING btree (aula_id)                                                                   |
| public     | aula_materiais                  | idx_aula_materiais_aula_tipo                 | CREATE INDEX idx_aula_materiais_aula_tipo ON public.aula_materiais USING btree (aula_id, tipo)                                                           |
| public     | aula_materiais                  | idx_aula_materiais_tipo                      | CREATE INDEX idx_aula_materiais_tipo ON public.aula_materiais USING btree (tipo)                                                                         |
| public     | aula_permissoes                 | idx_aula_permissoes_aula_id                  | CREATE INDEX idx_aula_permissoes_aula_id ON public.aula_permissoes USING btree (aula_id)                                                                 |
| public     | aula_presencas                  | idx_aula_presencas_aluno_id                  | CREATE INDEX idx_aula_presencas_aluno_id ON public.aula_presencas USING btree (aluno_id)                                                                 |
| public     | aula_presencas                  | idx_aula_presencas_aula_id                   | CREATE INDEX idx_aula_presencas_aula_id ON public.aula_presencas USING btree (aula_id)                                                                   |
| public     | aula_registros                  | idx_aula_registros_aula_id                   | CREATE INDEX idx_aula_registros_aula_id ON public.aula_registros USING btree (aula_id)                                                                   |
| public     | aula_status_log                 | idx_aula_status_log_aula_id                  | CREATE INDEX idx_aula_status_log_aula_id ON public.aula_status_log USING btree (aula_id)                                                                 |
| public     | aula_tags                       | idx_aula_tags_aula_id                        | CREATE INDEX idx_aula_tags_aula_id ON public.aula_tags USING btree (aula_id)                                                                             |
| public     | aulas                           | idx_aulas_data_programada                    | CREATE INDEX idx_aulas_data_programada ON public.aulas USING btree (data_programada)                                                                     |
| public     | aulas                           | idx_aulas_deleted_at                         | CREATE INDEX idx_aulas_deleted_at ON public.aulas USING btree (deleted_at) WHERE (deleted_at IS NULL)                                                    |
| public     | aulas                           | idx_aulas_detalhes_gin                       | CREATE INDEX idx_aulas_detalhes_gin ON public.aulas USING gin (detalhes_aula)                                                                            |
| public     | aulas                           | idx_aulas_modulo_id                          | CREATE INDEX idx_aulas_modulo_id ON public.aulas USING btree (modulo_id) WHERE (modulo_id IS NOT NULL)                                                   |
| public     | aulas                           | idx_aulas_nivel                              | CREATE INDEX idx_aulas_nivel ON public.aulas USING btree (nivel) WHERE (nivel IS NOT NULL)                                                               |
| public     | aulas                           | idx_aulas_not_deleted                        | CREATE INDEX idx_aulas_not_deleted ON public.aulas USING btree (deleted_at) WHERE (deleted_at IS NULL)                                                   |
| public     | aulas                           | idx_aulas_numero                             | CREATE INDEX idx_aulas_numero ON public.aulas USING btree (numero)                                                                                       |
| public     | aulas                           | idx_aulas_responsavel_id                     | CREATE INDEX idx_aulas_responsavel_id ON public.aulas USING btree (responsavel_id)                                                                       |
| public     | aulas                           | idx_aulas_status                             | CREATE INDEX idx_aulas_status ON public.aulas USING btree (status)                                                                                       |
| public     | aulas                           | idx_aulas_status_data                        | CREATE INDEX idx_aulas_status_data ON public.aulas USING btree (status, data_programada) WHERE (deleted_at IS NULL)                                      |
| public     | autoavaliacoes                  | idx_autoavaliacoes_periodo                   | CREATE INDEX idx_autoavaliacoes_periodo ON public.autoavaliacoes USING btree (periodo_tipo)                                                              |
| public     | autoavaliacoes                  | idx_autoavaliacoes_portfolio                 | CREATE INDEX idx_autoavaliacoes_portfolio ON public.autoavaliacoes USING btree (portfolio_id)                                                            |
| public     | autoavaliacoes                  | idx_autoavaliacoes_user                      | CREATE INDEX idx_autoavaliacoes_user ON public.autoavaliacoes USING btree (user_id)                                                                      |
| public     | avaliacoes_rubricas             | idx_avaliacoes_rubrica                       | CREATE INDEX idx_avaliacoes_rubrica ON public.avaliacoes_rubricas USING btree (rubrica_id)                                                               |
| public     | capacitacao_docente             | idx_capacitacao_professor                    | CREATE INDEX idx_capacitacao_professor ON public.capacitacao_docente USING btree (professor_id)                                                          |
| public     | cessoes_instrumentos            | idx_cessoes_aluno_id                         | CREATE INDEX idx_cessoes_aluno_id ON public.cessoes_instrumentos USING btree (aluno_id)                                                                  |
| public     | cessoes_instrumentos            | idx_cessoes_data_inicio                      | CREATE INDEX idx_cessoes_data_inicio ON public.cessoes_instrumentos USING btree (data_inicio)                                                            |
| public     | cessoes_instrumentos            | idx_cessoes_instrumento_fisico_id            | CREATE INDEX idx_cessoes_instrumento_fisico_id ON public.cessoes_instrumentos USING btree (instrumento_fisico_id)                                        |
| public     | devotional_content              | idx_devotional_content_category              | CREATE INDEX idx_devotional_content_category ON public.devotional_content USING btree (category)                                                         |
| public     | devotional_content              | idx_devotional_content_published             | CREATE INDEX idx_devotional_content_published ON public.devotional_content USING btree (is_published)                                                    |
| public     | devotional_content              | idx_devotional_content_published_date        | CREATE INDEX idx_devotional_content_published_date ON public.devotional_content USING btree (published_date DESC)                                        |
| public     | experiencias_brasileiras        | idx_experiencias_regiao                      | CREATE INDEX idx_experiencias_regiao ON public.experiencias_brasileiras USING btree (regiao_brasil)                                                      |
| public     | experiencias_brasileiras        | idx_experiencias_status                      | CREATE INDEX idx_experiencias_status ON public.experiencias_brasileiras USING btree (status_projeto)                                                     |
| public     | experiencias_brasileiras        | idx_experiencias_tipo                        | CREATE INDEX idx_experiencias_tipo ON public.experiencias_brasileiras USING btree (tipo_experiencia)                                                     |
| public     | feedback_pares                  | idx_feedback_avaliado                        | CREATE INDEX idx_feedback_avaliado ON public.feedback_pares USING btree (avaliado_id)                                                                    |
| public     | feedback_pares                  | idx_feedback_avaliador                       | CREATE INDEX idx_feedback_avaliador ON public.feedback_pares USING btree (avaliador_id)                                                                  |
| public     | feedback_pares                  | idx_feedback_evidencia                       | CREATE INDEX idx_feedback_evidencia ON public.feedback_pares USING btree (evidencia_id)                                                                  |
| public     | feedback_pares                  | idx_feedback_pares_evidencia                 | CREATE INDEX idx_feedback_pares_evidencia ON public.feedback_pares USING btree (evidencia_id)                                                            |
| public     | forum_perguntas                 | idx_forum_perguntas_aluno                    | CREATE INDEX idx_forum_perguntas_aluno ON public.forum_perguntas USING btree (aluno_id)                                                                  |
| public     | forum_perguntas                 | idx_forum_perguntas_modulo                   | CREATE INDEX idx_forum_perguntas_modulo ON public.forum_perguntas USING btree (modulo_id)                                                                |
| public     | forum_perguntas                 | idx_forum_perguntas_status                   | CREATE INDEX idx_forum_perguntas_status ON public.forum_perguntas USING btree (status)                                                                   |
| public     | historia_compositores           | idx_compositores_periodo                     | CREATE INDEX idx_compositores_periodo ON public.historia_compositores USING btree (periodo_id)                                                           |
| public     | historia_eventos_timeline       | idx_timeline_ano                             | CREATE INDEX idx_timeline_ano ON public.historia_eventos_timeline USING btree (ano)                                                                      |
| public     | historia_movimentos_artisticos  | idx_movimentos_nome                          | CREATE INDEX idx_movimentos_nome ON public.historia_movimentos_artisticos USING btree (nome)                                                             |
| public     | historia_movimentos_artisticos  | idx_movimentos_ordem                         | CREATE INDEX idx_movimentos_ordem ON public.historia_movimentos_artisticos USING btree (ordem_cronologica)                                               |
| public     | historia_obras                  | idx_obras_compositor                         | CREATE INDEX idx_obras_compositor ON public.historia_obras USING btree (compositor_id)                                                                   |
| public     | historia_obras                  | idx_obras_periodo                            | CREATE INDEX idx_obras_periodo ON public.historia_obras USING btree (periodo_id)                                                                         |
| public     | historia_progresso_usuario      | idx_progresso_user                           | CREATE INDEX idx_progresso_user ON public.historia_progresso_usuario USING btree (user_id)                                                               |
| public     | historia_quiz_respostas         | idx_quiz_respostas_user                      | CREATE INDEX idx_quiz_respostas_user ON public.historia_quiz_respostas USING btree (user_id)                                                             |
| public     | historia_timeline               | idx_timeline_compositor                      | CREATE INDEX idx_timeline_compositor ON public.historia_timeline USING btree (compositor_id)                                                             |
| public     | historia_timeline               | idx_timeline_obra                            | CREATE INDEX idx_timeline_obra ON public.historia_timeline USING btree (obra_id)                                                                         |
| public     | historia_timeline               | idx_timeline_periodo                         | CREATE INDEX idx_timeline_periodo ON public.historia_timeline USING btree (periodo_id)                                                                   |
| public     | historia_timeline               | idx_timeline_tipo                            | CREATE INDEX idx_timeline_tipo ON public.historia_timeline USING btree (tipo_evento)                                                                     |
| public     | historico_instrumentos          | idx_historico_instrumento_fisico_id          | CREATE INDEX idx_historico_instrumento_fisico_id ON public.historico_instrumentos USING btree (instrumento_fisico_id)                                    |
| public     | hook_cache                      | idx_cache_cleanup                            | CREATE INDEX idx_cache_cleanup ON public.hook_cache USING btree (expires_at)                                                                             |
| public     | hook_cache                      | idx_cache_lookup                             | CREATE INDEX idx_cache_lookup ON public.hook_cache USING btree (cache_key, expires_at)                                                                   |
| public     | hook_cache                      | idx_cache_user_hook                          | CREATE INDEX idx_cache_user_hook ON public.hook_cache USING btree (user_id, hook_name)                                                                   |
| public     | indicadores_impacto             | idx_indicadores_impacto_user                 | CREATE INDEX idx_indicadores_impacto_user ON public.indicadores_impacto USING btree (user_id)                                                            |
| public     | indicadores_impacto             | idx_indicadores_medicao                      | CREATE INDEX idx_indicadores_medicao ON public.indicadores_impacto USING btree (data_medicao)                                                            |
| public     | indicadores_impacto             | idx_indicadores_tipo                         | CREATE INDEX idx_indicadores_tipo ON public.indicadores_impacto USING btree (tipo_indicador)                                                             |
| public     | indicadores_impacto             | idx_indicadores_user                         | CREATE INDEX idx_indicadores_user ON public.indicadores_impacto USING btree (user_id)                                                                    |
| public     | instrumento_curiosidades        | idx_instrumento_curiosidades_categoria       | CREATE INDEX idx_instrumento_curiosidades_categoria ON public.instrumento_curiosidades USING btree (categoria)                                           |
| public     | instrumento_curiosidades        | idx_instrumento_curiosidades_instrumento     | CREATE INDEX idx_instrumento_curiosidades_instrumento ON public.instrumento_curiosidades USING btree (instrumento_id)                                    |
| public     | instrumento_midias              | idx_instrumento_midias_categoria             | CREATE INDEX idx_instrumento_midias_categoria ON public.instrumento_midias USING btree (categoria)                                                       |
| public     | instrumento_midias              | idx_instrumento_midias_instrumento           | CREATE INDEX idx_instrumento_midias_instrumento ON public.instrumento_midias USING btree (instrumento_id)                                                |
| public     | instrumento_midias              | idx_instrumento_midias_tipo                  | CREATE INDEX idx_instrumento_midias_tipo ON public.instrumento_midias USING btree (tipo)                                                                 |
| public     | instrumento_performances        | idx_instrumento_performances_artista         | CREATE INDEX idx_instrumento_performances_artista ON public.instrumento_performances USING btree (artista)                                               |
| public     | instrumento_performances        | idx_instrumento_performances_instrumento     | CREATE INDEX idx_instrumento_performances_instrumento ON public.instrumento_performances USING btree (instrumento_id)                                    |
| public     | instrumento_quiz                | idx_instrumento_quiz_instrumento             | CREATE INDEX idx_instrumento_quiz_instrumento ON public.instrumento_quiz USING btree (instrumento_id)                                                    |
| public     | instrumento_quiz                | idx_instrumento_quiz_tipo                    | CREATE INDEX idx_instrumento_quiz_tipo ON public.instrumento_quiz USING btree (tipo_pergunta)                                                            |
| public     | instrumento_sons                | idx_instrumento_sons_instrumento             | CREATE INDEX idx_instrumento_sons_instrumento ON public.instrumento_sons USING btree (instrumento_id)                                                    |
| public     | instrumento_sons                | idx_instrumento_sons_tecnica                 | CREATE INDEX idx_instrumento_sons_tecnica ON public.instrumento_sons USING btree (tecnica)                                                               |
| public     | instrumento_tecnicas            | idx_instrumento_tecnicas_instrumento         | CREATE INDEX idx_instrumento_tecnicas_instrumento ON public.instrumento_tecnicas USING btree (instrumento_id)                                            |
| public     | instrumento_tecnicas            | idx_instrumento_tecnicas_nivel               | CREATE INDEX idx_instrumento_tecnicas_nivel ON public.instrumento_tecnicas USING btree (nivel)                                                           |
| public     | instrumento_tecnicas            | idx_instrumento_tecnicas_tipo                | CREATE INDEX idx_instrumento_tecnicas_tipo ON public.instrumento_tecnicas USING btree (tipo_tecnica)                                                     |
| public     | instrumentos                    | idx_instrumentos_ativo                       | CREATE INDEX idx_instrumentos_ativo ON public.instrumentos USING btree (ativo)                                                                           |
| public     | instrumentos                    | idx_instrumentos_categoria                   | CREATE INDEX idx_instrumentos_categoria ON public.instrumentos USING btree (categoria)                                                                   |
| public     | instrumentos                    | idx_instrumentos_nome                        | CREATE INDEX idx_instrumentos_nome ON public.instrumentos USING btree (nome)                                                                             |
| public     | instrumentos                    | idx_instrumentos_not_deleted                 | CREATE INDEX idx_instrumentos_not_deleted ON public.instrumentos USING btree (id) WHERE (deleted_at IS NULL)                                             |
| public     | instrumentos                    | idx_instrumentos_search                      | CREATE INDEX idx_instrumentos_search ON public.instrumentos USING gin (to_tsvector('portuguese'::regconfig, (((nome)::text || ' '::text) || descricao))) |
| public     | instrumentos_relacionados       | idx_instrumentos_relacionados_instrumento    | CREATE INDEX idx_instrumentos_relacionados_instrumento ON public.instrumentos_relacionados USING btree (instrumento_id)                                  |
| public     | instrumentos_relacionados       | idx_instrumentos_relacionados_tipo           | CREATE INDEX idx_instrumentos_relacionados_tipo ON public.instrumentos_relacionados USING btree (tipo_relacao)                                           |
| public     | lessons                         | idx_lessons_exercise                         | CREATE INDEX idx_lessons_exercise ON public.lessons USING btree (has_exercise)                                                                           |
| public     | lessons                         | idx_lessons_free                             | CREATE INDEX idx_lessons_free ON public.lessons USING btree (is_free)                                                                                    |
| public     | lessons                         | idx_lessons_module_id                        | CREATE INDEX idx_lessons_module_id ON public.lessons USING btree (module_id)                                                                             |
| public     | lessons                         | idx_lessons_order                            | CREATE INDEX idx_lessons_order ON public.lessons USING btree (module_id, order_index)                                                                    |
| public     | lessons                         | idx_lessons_slug                             | CREATE INDEX idx_lessons_slug ON public.lessons USING btree (slug)                                                                                       |
| public     | lessons                         | idx_lessons_tags                             | CREATE INDEX idx_lessons_tags ON public.lessons USING gin (tags)                                                                                         |
| public     | manutencoes_instrumentos        | idx_manutencoes_instrumento_fisico_id        | CREATE INDEX idx_manutencoes_instrumento_fisico_id ON public.manutencoes_instrumentos USING btree (instrumento_fisico_id)                                |
| public     | materiais_apoio                 | idx_materiais_modulo                         | CREATE INDEX idx_materiais_modulo ON public.materiais_apoio USING btree (modulo_relacionado_id)                                                          |
| public     | materiais_apoio                 | idx_materiais_tipo                           | CREATE INDEX idx_materiais_tipo ON public.materiais_apoio USING btree (tipo)                                                                             |
| public     | matriculas                      | idx_matriculas_aluno                         | CREATE INDEX idx_matriculas_aluno ON public.matriculas USING btree (aluno_id)                                                                            |
| public     | matriculas                      | idx_matriculas_aluno_id                      | CREATE INDEX idx_matriculas_aluno_id ON public.matriculas USING btree (aluno_id)                                                                         |
| public     | matriculas                      | idx_matriculas_aluno_status                  | CREATE INDEX idx_matriculas_aluno_status ON public.matriculas USING btree (aluno_id, status)                                                             |
| public     | matriculas                      | idx_matriculas_data                          | CREATE INDEX idx_matriculas_data ON public.matriculas USING btree (data_matricula)                                                                       |
| public     | matriculas                      | idx_matriculas_data_matricula                | CREATE INDEX idx_matriculas_data_matricula ON public.matriculas USING btree (data_matricula)                                                             |
| public     | matriculas                      | idx_matriculas_not_deleted                   | CREATE INDEX idx_matriculas_not_deleted ON public.matriculas USING btree (id) WHERE (deleted_at IS NULL)                                                 |
| public     | matriculas                      | idx_matriculas_status                        | CREATE INDEX idx_matriculas_status ON public.matriculas USING btree (status)                                                                             |
| public     | matriculas                      | idx_matriculas_turma                         | CREATE INDEX idx_matriculas_turma ON public.matriculas USING btree (turma_id)                                                                            |
| public     | matriculas                      | idx_matriculas_turma_id                      | CREATE INDEX idx_matriculas_turma_id ON public.matriculas USING btree (turma_id)                                                                         |
| public     | matriculas                      | idx_matriculas_turma_status                  | CREATE INDEX idx_matriculas_turma_status ON public.matriculas USING btree (turma_id, status)                                                             |
| public     | modules                         | idx_modules_active                           | CREATE INDEX idx_modules_active ON public.modules USING btree (is_active)                                                                                |
| public     | modules                         | idx_modules_instrument                       | CREATE INDEX idx_modules_instrument ON public.modules USING btree (instrument_category)                                                                  |
| public     | modules                         | idx_modules_level                            | CREATE INDEX idx_modules_level ON public.modules USING btree (level_required)                                                                            |
| public     | modules                         | idx_modules_level_instrument                 | CREATE INDEX idx_modules_level_instrument ON public.modules USING btree (level_required, instrument_category)                                            |
| public     | modules                         | idx_modules_order                            | CREATE INDEX idx_modules_order ON public.modules USING btree (order_index)                                                                               |
| public     | modules                         | idx_modules_premium                          | CREATE INDEX idx_modules_premium ON public.modules USING btree (is_premium)                                                                              |
| public     | modules                         | idx_modules_slug                             | CREATE INDEX idx_modules_slug ON public.modules USING btree (slug)                                                                                       |
| public     | modulos                         | idx_modulos_ativo                            | CREATE INDEX idx_modulos_ativo ON public.modulos USING btree (ativo)                                                                                     |
| public     | modulos                         | idx_modulos_ordem                            | CREATE INDEX idx_modulos_ordem ON public.modulos USING btree (ordem)                                                                                     |
| public     | portfolio_evidencias            | idx_evidencias_aprovado                      | CREATE INDEX idx_evidencias_aprovado ON public.portfolio_evidencias USING btree (aprovado)                                                               |
| public     | portfolio_evidencias            | idx_evidencias_tipo                          | CREATE INDEX idx_evidencias_tipo ON public.portfolio_evidencias USING btree (tipo_evidencia)                                                             |
| public     | portfolio_evidencias            | idx_portfolio_evidencias_portfolio           | CREATE INDEX idx_portfolio_evidencias_portfolio ON public.portfolio_evidencias USING btree (portfolio_id)                                                |
| public     | portfolio_evidencias            | idx_portfolio_evidencias_tipo                | CREATE INDEX idx_portfolio_evidencias_tipo ON public.portfolio_evidencias USING btree (tipo_evidencia)                                                   |
| public     | portfolios                      | idx_portfolios_competencia_id                | CREATE INDEX idx_portfolios_competencia_id ON public.portfolios USING btree (competencia_id) WHERE (competencia_id IS NOT NULL)                          |
| public     | portfolios                      | idx_portfolios_metodologia                   | CREATE INDEX idx_portfolios_metodologia ON public.portfolios USING btree (metodologia_id)                                                                |
| public     | portfolios                      | idx_portfolios_metodologia_id                | CREATE INDEX idx_portfolios_metodologia_id ON public.portfolios USING btree (metodologia_id) WHERE (metodologia_id IS NOT NULL)                          |
| public     | portfolios                      | idx_portfolios_not_deleted                   | CREATE INDEX idx_portfolios_not_deleted ON public.portfolios USING btree (id) WHERE (deleted_at IS NULL)                                                 |
| public     | portfolios                      | idx_portfolios_status                        | CREATE INDEX idx_portfolios_status ON public.portfolios USING btree (status)                                                                             |
| public     | portfolios                      | idx_portfolios_tipo                          | CREATE INDEX idx_portfolios_tipo ON public.portfolios USING btree (tipo) WHERE (deleted_at IS NULL)                                                      |
| public     | portfolios                      | idx_portfolios_user                          | CREATE INDEX idx_portfolios_user ON public.portfolios USING btree (user_id)                                                                              |
| public     | portfolios                      | idx_portfolios_user_id                       | CREATE INDEX idx_portfolios_user_id ON public.portfolios USING btree (user_id)                                                                           |
| public     | portfolios                      | idx_portfolios_user_status                   | CREATE INDEX idx_portfolios_user_status ON public.portfolios USING btree (user_id, status) WHERE (deleted_at IS NULL)                                    |
| public     | presencas                       | idx_presencas_data_aula                      | CREATE INDEX idx_presencas_data_aula ON public.presencas USING btree (data_aula)                                                                         |
| public     | presencas                       | idx_presencas_matricula_id                   | CREATE INDEX idx_presencas_matricula_id ON public.presencas USING btree (matricula_id)                                                                   |
| public     | professor_instrumentos          | idx_professor_instrumentos_instrumento       | CREATE INDEX idx_professor_instrumentos_instrumento ON public.professor_instrumentos USING btree (instrumento_id)                                        |
| public     | professor_instrumentos          | idx_professor_instrumentos_professor         | CREATE INDEX idx_professor_instrumentos_professor ON public.professor_instrumentos USING btree (professor_id)                                            |
| public     | professores_conteudos           | idx_professores_conteudos_ativo              | CREATE INDEX idx_professores_conteudos_ativo ON public.professores_conteudos USING btree (ativo)                                                         |
| public     | professores_conteudos           | idx_professores_conteudos_categoria_id       | CREATE INDEX idx_professores_conteudos_categoria_id ON public.professores_conteudos USING btree (categoria_id)                                           |
| public     | professores_conteudos           | idx_professores_conteudos_criado_em          | CREATE INDEX idx_professores_conteudos_criado_em ON public.professores_conteudos USING btree (criado_em DESC)                                            |
| public     | professores_conteudos           | idx_professores_conteudos_criado_em_desc     | CREATE INDEX idx_professores_conteudos_criado_em_desc ON public.professores_conteudos USING btree (criado_em DESC)                                       |
| public     | professores_conteudos           | idx_professores_conteudos_criado_por         | CREATE INDEX idx_professores_conteudos_criado_por ON public.professores_conteudos USING btree (criado_por)                                               |
| public     | professores_conteudos           | idx_professores_conteudos_destaque           | CREATE INDEX idx_professores_conteudos_destaque ON public.professores_conteudos USING btree (destaque)                                                   |
| public     | professores_conteudos           | idx_professores_conteudos_tags               | CREATE INDEX idx_professores_conteudos_tags ON public.professores_conteudos USING gin (tags)                                                             |
| public     | professores_conteudos           | idx_professores_conteudos_tipo               | CREATE INDEX idx_professores_conteudos_tipo ON public.professores_conteudos USING btree (tipo)                                                           |
| public     | professores_conteudos           | idx_professores_conteudos_visivel            | CREATE INDEX idx_professores_conteudos_visivel ON public.professores_conteudos USING btree (visivel)                                                     |
| public     | professores_conteudos           | idx_professores_conteudos_visualizacoes_desc | CREATE INDEX idx_professores_conteudos_visualizacoes_desc ON public.professores_conteudos USING btree (visualizacoes DESC NULLS LAST)                    |
| public     | profiles                        | idx_profiles_city_state                      | CREATE INDEX idx_profiles_city_state ON public.profiles USING btree (city, state)                                                                        |
| public     | profiles                        | idx_profiles_current_streak                  | CREATE INDEX idx_profiles_current_streak ON public.profiles USING btree (current_streak DESC)                                                            |
| public     | profiles                        | idx_profiles_email                           | CREATE INDEX idx_profiles_email ON public.profiles USING btree (email)                                                                                   |
| public     | profiles                        | idx_profiles_instrument                      | CREATE INDEX idx_profiles_instrument ON public.profiles USING btree (instrument)                                                                         |
| public     | profiles                        | idx_profiles_last_active                     | CREATE INDEX idx_profiles_last_active ON public.profiles USING btree (last_active DESC)                                                                  |
| public     | profiles                        | idx_profiles_lessons_completed               | CREATE INDEX idx_profiles_lessons_completed ON public.profiles USING btree (lessons_completed DESC)                                                      |
| public     | profiles                        | idx_profiles_tipo_usuario                    | CREATE INDEX idx_profiles_tipo_usuario ON public.profiles USING btree (tipo_usuario)                                                                     |
| public     | profiles                        | idx_profiles_total_points                    | CREATE INDEX idx_profiles_total_points ON public.profiles USING btree (total_points DESC)                                                                |
| public     | profiles                        | idx_profiles_user_id                         | CREATE INDEX idx_profiles_user_id ON public.profiles USING btree (id)                                                                                    |
| public     | profiles                        | idx_profiles_user_level                      | CREATE INDEX idx_profiles_user_level ON public.profiles USING btree (user_level)                                                                         |
| public     | proposta_curricular             | idx_curricular_nivel                         | CREATE INDEX idx_curricular_nivel ON public.proposta_curricular USING btree (nivel_ensino)                                                               |
| public     | qr_codes                        | idx_qr_aula                                  | CREATE INDEX idx_qr_aula ON public.qr_codes USING btree (aula_id, type, created_at DESC)                                                                 |
| public     | qr_codes                        | idx_qr_cleanup                               | CREATE INDEX idx_qr_cleanup ON public.qr_codes USING btree (expires_at, is_active)                                                                       |
| public     | qr_codes                        | idx_qr_code_lookup                           | CREATE INDEX idx_qr_code_lookup ON public.qr_codes USING btree (code, is_active, expires_at)                                                             |
| public     | qr_scans                        | idx_qr_scans_code                            | CREATE INDEX idx_qr_scans_code ON public.qr_scans USING btree (qr_code_id, scanned_at DESC)                                                              |
| public     | qr_scans                        | idx_qr_scans_result                          | CREATE INDEX idx_qr_scans_result ON public.qr_scans USING btree (result, scanned_at DESC)                                                                |
| public     | qr_scans                        | idx_qr_scans_user                            | CREATE INDEX idx_qr_scans_user ON public.qr_scans USING btree (user_id, scanned_at DESC)                                                                 |
| public     | repertorio_musical              | idx_repertorio_instrumento                   | CREATE INDEX idx_repertorio_instrumento ON public.repertorio_musical USING btree (instrumento_principal_id)                                              |
| public     | repertorio_musical              | idx_repertorio_nivel                         | CREATE INDEX idx_repertorio_nivel ON public.repertorio_musical USING btree (nivel)                                                                       |
| public     | rubricas_avaliacao              | idx_rubricas_ativo                           | CREATE INDEX idx_rubricas_ativo ON public.rubricas_avaliacao USING btree (ativo)                                                                         |
| public     | rubricas_avaliacao              | idx_rubricas_tipo                            | CREATE INDEX idx_rubricas_tipo ON public.rubricas_avaliacao USING btree (tipo)                                                                           |
| public     | sequencias_didaticas_expandidas | idx_sequencias_metodologia                   | CREATE INDEX idx_sequencias_metodologia ON public.sequencias_didaticas_expandidas USING btree (metodologia_base)                                         |
| public     | sistema_presto                  | idx_presto_metodologia                       | CREATE INDEX idx_presto_metodologia ON public.sistema_presto USING btree (metodologia_associada)                                                         |
| public     | sistema_presto                  | idx_presto_tipo                              | CREATE INDEX idx_presto_tipo ON public.sistema_presto USING btree (tipo_recurso)                                                                         |
| public     | sistema_presto                  | idx_presto_user                              | CREATE INDEX idx_presto_user ON public.sistema_presto USING btree (user_id)                                                                              |
| public     | trigger_logs                    | idx_trigger_logs_created_at                  | CREATE INDEX idx_trigger_logs_created_at ON public.trigger_logs USING btree (created_at DESC)                                                            |
| public     | trigger_logs                    | idx_trigger_logs_user_id                     | CREATE INDEX idx_trigger_logs_user_id ON public.trigger_logs USING btree (user_id)                                                                       |
| public     | turma_alunos                    | idx_turma_alunos_aluno_id                    | CREATE INDEX idx_turma_alunos_aluno_id ON public.turma_alunos USING btree (aluno_id)                                                                     |
| public     | turma_alunos                    | idx_turma_alunos_turma_id                    | CREATE INDEX idx_turma_alunos_turma_id ON public.turma_alunos USING btree (turma_id)                                                                     |
| public     | turmas                          | idx_turmas_ativo                             | CREATE INDEX idx_turmas_ativo ON public.turmas USING btree (ativo)                                                                                       |
| public     | turmas                          | idx_turmas_instrumento                       | CREATE INDEX idx_turmas_instrumento ON public.turmas USING btree (instrumento_id)                                                                        |
| public     | turmas                          | idx_turmas_instrumento_id                    | CREATE INDEX idx_turmas_instrumento_id ON public.turmas USING btree (instrumento_id)                                                                     |
| public     | turmas                          | idx_turmas_not_deleted                       | CREATE INDEX idx_turmas_not_deleted ON public.turmas USING btree (id) WHERE (deleted_at IS NULL)                                                         |
| public     | turmas                          | idx_turmas_professor                         | CREATE INDEX idx_turmas_professor ON public.turmas USING btree (professor_id)                                                                            |
| public     | turmas                          | idx_turmas_professor_ativo                   | CREATE INDEX idx_turmas_professor_ativo ON public.turmas USING btree (professor_id, ativo)                                                               |
| public     | turmas                          | idx_turmas_professor_id                      | CREATE INDEX idx_turmas_professor_id ON public.turmas USING btree (professor_id)                                                                         |
| public     | turmas                          | idx_turmas_status                            | CREATE INDEX idx_turmas_status ON public.turmas USING btree (status)                                                                                     |
| public     | user_achievements               | idx_user_achievements_achievement_id         | CREATE INDEX idx_user_achievements_achievement_id ON public.user_achievements USING btree (achievement_id)                                               |
| public     | user_achievements               | idx_user_achievements_earned_at              | CREATE INDEX idx_user_achievements_earned_at ON public.user_achievements USING btree (earned_at DESC)                                                    |
| public     | user_achievements               | idx_user_achievements_user                   | CREATE INDEX idx_user_achievements_user ON public.user_achievements USING btree (user_id)                                                                |
| public     | user_achievements               | idx_user_achievements_user_id                | CREATE INDEX idx_user_achievements_user_id ON public.user_achievements USING btree (user_id)                                                             |
| public     | user_badges                     | idx_user_badges_badge_id                     | CREATE INDEX idx_user_badges_badge_id ON public.user_badges USING btree (badge_id)                                                                       |
| public     | user_badges                     | idx_user_badges_obtido_em                    | CREATE INDEX idx_user_badges_obtido_em ON public.user_badges USING btree (obtido_em DESC)                                                                |
| public     | user_badges                     | idx_user_badges_user_id                      | CREATE INDEX idx_user_badges_user_id ON public.user_badges USING btree (user_id)                                                                         |
| public     | user_devotional_progress        | idx_user_devotional_devotional_id            | CREATE INDEX idx_user_devotional_devotional_id ON public.user_devotional_progress USING btree (devotional_id)                                            |
| public     | user_devotional_progress        | idx_user_devotional_read_at                  | CREATE INDEX idx_user_devotional_read_at ON public.user_devotional_progress USING btree (read_at DESC)                                                   |
| public     | user_devotional_progress        | idx_user_devotional_user_id                  | CREATE INDEX idx_user_devotional_user_id ON public.user_devotional_progress USING btree (user_id)                                                        |
| public     | user_notifications              | idx_notifications_cleanup                    | CREATE INDEX idx_notifications_cleanup ON public.user_notifications USING btree (expires_at) WHERE (expires_at IS NOT NULL)                              |
| public     | user_notifications              | idx_notifications_user_unread                | CREATE INDEX idx_notifications_user_unread ON public.user_notifications USING btree (user_id, is_read, created_at DESC)                                  |
| public     | user_points_log                 | idx_points_action                            | CREATE INDEX idx_points_action ON public.user_points_log USING btree (action, created_at DESC)                                                           |
| public     | user_points_log                 | idx_points_source                            | CREATE INDEX idx_points_source ON public.user_points_log USING btree (source_type, source_id)                                                            |
| public     | user_points_log                 | idx_user_points_log_action                   | CREATE INDEX idx_user_points_log_action ON public.user_points_log USING btree (action)                                                                   |
| public     | user_points_log                 | idx_user_points_log_created                  | CREATE INDEX idx_user_points_log_created ON public.user_points_log USING btree (created_at DESC)                                                         |
| public     | user_points_log                 | idx_user_points_log_created_at               | CREATE INDEX idx_user_points_log_created_at ON public.user_points_log USING btree (created_at DESC)                                                      |
| public     | user_points_log                 | idx_user_points_log_source_type              | CREATE INDEX idx_user_points_log_source_type ON public.user_points_log USING btree (source_type)                                                         |
| public     | user_points_log                 | idx_user_points_log_user_date                | CREATE INDEX idx_user_points_log_user_date ON public.user_points_log USING btree (user_id, created_at DESC)                                              |
| public     | user_points_log                 | idx_user_points_log_user_id                  | CREATE INDEX idx_user_points_log_user_id ON public.user_points_log USING btree (user_id)                                                                 |
| public     | user_points_log                 | idx_user_points_user_source                  | CREATE INDEX idx_user_points_user_source ON public.user_points_log USING btree (user_id, source_type, created_at DESC)                                   |
| public     | user_progress                   | idx_user_progress_completed                  | CREATE INDEX idx_user_progress_completed ON public.user_progress USING btree (is_completed)                                                              |
| public     | user_progress                   | idx_user_progress_lesson                     | CREATE INDEX idx_user_progress_lesson ON public.user_progress USING btree (lesson_id)                                                                    |
| public     | user_progress                   | idx_user_progress_lesson_id                  | CREATE INDEX idx_user_progress_lesson_id ON public.user_progress USING btree (lesson_id)                                                                 |
| public     | user_progress                   | idx_user_progress_rating                     | CREATE INDEX idx_user_progress_rating ON public.user_progress USING btree (rating)                                                                       |
| public     | user_progress                   | idx_user_progress_user                       | CREATE INDEX idx_user_progress_user ON public.user_progress USING btree (user_id)                                                                        |
| public     | user_progress                   | idx_user_progress_user_completed             | CREATE INDEX idx_user_progress_user_completed ON public.user_progress USING btree (user_id, is_completed)                                                |
| public     | user_progress                   | idx_user_progress_user_id                    | CREATE INDEX idx_user_progress_user_id ON public.user_progress USING btree (user_id)                                                                     |
| public     | user_roles                      | idx_user_roles_active                        | CREATE INDEX idx_user_roles_active ON public.user_roles USING btree (user_id, is_active, role_level DESC)                                                |
| public     | user_roles                      | idx_user_roles_type                          | CREATE INDEX idx_user_roles_type ON public.user_roles USING btree (role_type, is_active)                                                                 |

