-- =============================================
-- Migration: 021_history_periods.sql
-- Table: core.history_periods
-- Source CSV: historia_periodos_rows.csv
-- Generated: 2026-02-28T16:15:03.637Z
-- Rows: 23
-- =============================================

BEGIN;

INSERT INTO core.history_periods (tenant_id, id, name, description, start_year, end_year, theme_color, cover_image_url, chronological_order, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '058f61ff-806e-4179-8c5b-2cd597b36d76', $$Era do Rádio (Brasil)$$, $$A era de ouro da música brasileira. Samba se consolida como identidade nacional. Rádio Nacional difunde música por todo o país. Surgem grandes intérpretes e compositores. Carmen Miranda conquista Hollywood.$$, 1930, 1950, $$#f1c40f$$, NULL, 21, true, '2025-12-14 20:49:33.510717+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_periods (tenant_id, id, name, description, start_year, end_year, theme_color, cover_image_url, chronological_order, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '17bf83a0-e91e-4983-915f-51ace4da29ea', $$Era Meiji (Japão)$$, $$A Restauração Meiji traz profundas mudanças. Música ocidental é introduzida nas escolas. Primeiros compositores japoneses treinados em técnicas europeias. Início da música híbrida nipônica-ocidental.$$, 1868, 1912, $$#f39c12$$, NULL, 16, true, '2025-12-14 20:49:33.510717+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_periods (tenant_id, id, name, description, start_year, end_year, theme_color, cover_image_url, chronological_order, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '36750dc3-177d-4b56-b230-66df92911877', $$Brasil Colonial$$, $$A música colonial brasileira resulta do encontro de três matrizes culturais. Música sacra europeia trazida pelos jesuítas. Ritmos e instrumentos africanos dos escravizados. Tradições musicais indígenas. Destaque para o barroco mineiro.$$, 1500, 1822, $$#8b4513$$, NULL, 19, true, '2025-12-14 20:49:33.510717+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_periods (tenant_id, id, name, description, start_year, end_year, theme_color, cover_image_url, chronological_order, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '36ea1a6e-5615-48dc-9c2f-c8cc87d2dfd4', $$Período Heian (Japão)$$, $$O Período Heian marca o apogeu da cultura aristocrática japonesa. A música gagaku (música da corte imperial) foi consolidada nesta época, combinando influências chinesas, coreanas e tradições nativas japonesas. Instrumentos como biwa, koto e shakuhachi começaram a ser refinados.$$, 794, 1185, $$#9b59b6$$, NULL, 13, true, '2025-12-14 20:49:33.510717+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_periods (tenant_id, id, name, description, start_year, end_year, theme_color, cover_image_url, chronological_order, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '3ff47d85-e4f2-4f79-9a04-1dcf021abfad', $$Período Kamakura (Japão)$$, $$Com o estabelecimento do shogunato em Kamakura, emerge uma cultura mais austera dos samurais. O teatro Noh começa a se desenvolver, combinando dança, drama e música. O shakuhachi torna-se instrumento dos monges zen.$$, 1185, 1333, $$#3498db$$, NULL, 14, true, '2025-12-14 20:49:33.510717+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_periods (tenant_id, id, name, description, start_year, end_year, theme_color, cover_image_url, chronological_order, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '40424e40-4c08-4885-a55f-a560c8dd90d7', $$Renascimento$$, $$O Renascimento musical (c.1400-1600) representa a transição da música medieval para o período moderno. Caracteriza-se pelo desenvolvimento pleno da polifonia imitativa, com destaque para a missa e o moteto sacro, além do florescimento do madrigal secular italiano. O humanismo renascentista influenciou profundamente a música, com maior atenção ao texto e à expressão das palavras (madrigalismos, text painting). A imprensa musical, iniciada por Ottaviano Petrucci em Veneza (1501), revolucionou a disseminação de obras. Compositores como Josquin des Prez, Giovanni Pierluigi da Palestrina e Orlando di Lasso elevaram a polifonia vocal a níveis de sofisticação sem precedentes. A música instrumental começou a ganhar autonomia, deixando de ser apenas acompanhamento de danças. A Reforma Protestante (Lutero, 1517) e a Contrarreforma Católica (Concílio de Trento, 1545-1563) tiveram grande impacto na produção musical, com Palestrina respondendo às exigências de clareza textual. Escolas principais: Franco-flamenga (Josquin, Ockeghem), Italiana (Palestrina, Gabrieli), Espanhola (Victoria), Inglesa (Byrd, Tallis).$$, 1400, 1600, $$#DAA520$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Francesco_Rosselli_-_Ptolemaic_Chart.jpg/800px-Francesco_Rosselli_-_Ptolemaic_Chart.jpg$$, 2, true, '2025-10-09 02:04:21.44846+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_periods (tenant_id, id, name, description, start_year, end_year, theme_color, cover_image_url, chronological_order, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '480e5257-9aca-48e8-971f-f19794fc0dcf', $$MPB e Tropicália$$, $$Período de intensa criatividade e experimentação. Festivais de MPB revelam novos talentos. Tropicália mistura rock, baião, samba e vanguarda. Música torna-se veículo de protesto contra ditadura.$$, 1965, 1980, $$#9b59b6$$, NULL, 22, true, '2025-12-14 20:49:33.510717+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_periods (tenant_id, id, name, description, start_year, end_year, theme_color, cover_image_url, chronological_order, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '68690a8a-47f6-40a7-ad15-c1951e377172', $$Contemporâneo$$, $$A música contemporânea (1950-2024) é marcada por pluralismo e fragmentação estilística sem precedentes. Múltiplas correntes coexistem: Serialismo integral (Pierre Boulez, Karlheinz Stockhausen) serializa todos os parâmetros musicais - altura, duração, dinâmica, timbre, articulação. Música eletrônica surge em Colônia (Stockhausen) e Paris (Pierre Schaeffer: musique concrète). John Cage introduz indeterminação, acaso e filosofia zen (4'33": 4 minutos e 33 segundos de silêncio, 1952). Minimalismo americano (Steve Reich, Philip Glass, Terry Riley, La Monte Young) reage ao serialismo complexo com pulso constante, repetição gradual, processos audíveis. Espectralismo francês (Gérard Grisey, Tristan Murail) analisa espectros acústicos via computador e compõe com base em harmônicos. György Ligeti desenvolve micropolifonia (milhares de linhas entrelaçadas) e clusters móveis (Atmosphères). Krzysztof Penderecki explora massas sonoras e glissandi orquestrais (Threnos para as Vítimas de Hiroshima). George Crumb usa notação gráfica e técnicas estendidas. Henryk Górecki e Arvo Pärt criam "novo misticismo" ou "sacro minimalismo". Pós-modernismo abraça ecletismo, citação irônica e fusão de erudito/popular (John Adams). Tecnologia digital revoluciona composição, notação e performance (Max/MSP, Csound). Globalização traz influências não-ocidentais sistemáticas. Música de concerto se fragmenta em múltiplas correntes coexistentes: complexidade (Brian Ferneyhough), Nova Simplicidade alemã, pós-minimalismo, novo romantismo, música espectral, laptop music, live electronics.$$, 1950, 2024, $$#00CED1$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Karlheinz_Stockhausen_1994.jpg/800px-Karlheinz_Stockhausen_1994.jpg$$, 8, true, '2025-10-09 02:09:20.82561+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_periods (tenant_id, id, name, description, start_year, end_year, theme_color, cover_image_url, chronological_order, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '798ce272-a0af-40a3-97c5-11b83fe0addb', $$Bossa Nova$$, $$Bossa Nova (literalmente "batida nova" ou "jeito novo") nasceu no final dos anos 1950s no Rio de Janeiro (bairros Copacabana, Ipanema), criada principalmente por Tom Jobim (compositor/pianista), Vinicius de Moraes (poeta/letrista) e João Gilberto (violonista/cantor). Características revolucionárias: harmonias sofisticadas (acordes de 9ª, 11ª, 13ª, influência de Debussy e Ravel), batida sincopada característica no violão (polegar marca graves, dedos fazem síncope nos agudos), canto intimista "de dentro" (João Gilberto sussurra ao invés de projetar), melodias melancólicas mas leves, letras poéticas sobre mar, sol, amor, saudade. Fusão perfeita de samba tradicional (ritmo), jazz cool (harmonias), impressionismo francês (cores harmônicas). Marco inicial: álbum Chega de Saudade de João Gilberto (1959), com composições de Tom Jobim e Vinicius. Explosão internacional: concerto no Carnegie Hall NY (1962), colaboração com Stan Getz (Getz/Gilberto 1964, com "Garota de Ipanema" cantada por Astrud Gilberto tornou-se hit mundial). Outros mestres: Carlos Lyra, Roberto Menescal, Nara Leão, Edu Lobo, Baden Powell (violão virtuosístico), Luiz Bonfá, Sérgio Mendes. Influenciou profundamente jazz (Miles Davis, Stan Getz), pop (Frank Sinatra gravou Jobim), música brasileira subsequente (MPB descende dela). Representa otimismo desenvolvimentista do Brasil pré-64 (governo JK: "50 anos em 5", construção de Brasília). Após golpe de 1964, muitos bossa-novistas se engajaram politicamente, evoluindo para MPB. Legado permanente: standards como "Garota de Ipanema", "Desafinado", "Águas de Março", "Corcovado" são conhecidos mundialmente.$$, 1958, 1970, $$#87CEEB$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Tom_Jobim_1965.jpg/800px-Tom_Jobim_1965.jpg$$, 11, true, '2025-10-09 02:09:20.82561+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_periods (tenant_id, id, name, description, start_year, end_year, theme_color, cover_image_url, chronological_order, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '8c167784-6592-4f6f-bb74-422c863439ec', $$Período Edo (Japão)$$, $$O longo período de paz Tokugawa permitiu extraordinário desenvolvimento cultural urbano. O teatro kabuki floresce nas grandes cidades. O shamisen torna-se extremamente popular. Surgem os primeiros estilos de música popular japonesa.$$, 1603, 1868, $$#e74c3c$$, NULL, 15, true, '2025-12-14 20:49:33.510717+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_periods (tenant_id, id, name, description, start_year, end_year, theme_color, cover_image_url, chronological_order, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', 'a202d11a-4152-4640-acc4-b538109b0a44', $$Rock e Música Popular$$, $$Música Popular do século XX-XXI abrange múltiplos gêneros nascidos da revolução cultural juvenil pós-1950. Rock'n'Roll (1950s: Elvis Presley, Chuck Berry, Little Richard) funde rhythm & blues negro com country branco, chocando moralidade conservadora. Rock evolui: British Invasion (1964: Beatles, Rolling Stones), Rock Psicodélico (1967: Hendrix, Pink Floyd), Hard Rock/Heavy Metal (Led Zeppelin, Black Sabbath), Punk Rock (1975: Sex Pistols, Ramones: anti-establishment cru), New Wave (1980s: Talking Heads, The Cure), Grunge (1990s: Nirvana, Pearl Jam). Soul/R&B (1960s: Aretha Franklin, Marvin Gaye, Stevie Wonder) expressa experiência afro-americana. Funk (James Brown, Parliament-Funkadelic) cria groove sincopado supremo. Disco (1970s: Donna Summer, Bee Gees) domina pistas de dança. Hip-Hop/Rap (1970s Bronx: DJ Kool Herc, Grandmaster Flash) revoluciona com samples, breakbeats, MCs rimando. Música Eletrônica: House (Chicago 1980s), Techno (Detroit 1980s: Juan Atkins, Derrick May), Drum and Bass, Dubstep (2000s). Pop mainstream (Michael Jackson "Rei do Pop", Madonna, Prince) domina MTV (1981-). Anos 2000s-2020s: indie rock, emo, post-rock, EDM (electronic dance music), trap, K-pop (Coreia do Sul conquista mundo), Afrobeats (Nigéria: Burna Boy, Wizkid), fusões globais via internet/streaming. Características comuns: importância de gravação/produção como arte, cultura juvenil, dança, amplificação elétrica, bateria rock, guitarra/baixo elétricos, sintetizadores, samplers, autotune (2000s), streaming (Spotify 2008, revoluciona distribuição).$$, 1950, 2024, $$#FF1493$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Beatles_ad_1965_just_the_beatles_crop.jpg/800px-Beatles_ad_1965_just_the_beatles_crop.jpg$$, 12, true, '2025-10-09 02:09:20.82561+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_periods (tenant_id, id, name, description, start_year, end_year, theme_color, cover_image_url, chronological_order, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', 'a456e639-d38c-4098-8915-427e2fe80de8', $$Jazz$$, $$O Jazz nasceu em Nova Orleans no final do século XIX, da fusão explosiva de blues rural, ragtime pianístico, música de brass band europeia, gospel protestante e tradições rítmicas africanas preservadas por escravizados. Características definidoras: improvisação sobre progressões harmônicas (changes), swing (subdivisão ternária fluida do tempo), blue notes (terças e sétimas abaixadas microtonalmente), síncope constante, call-and-response entre solista e grupo. Evolui em múltiplos estilos cronológicos: Dixieland/New Orleans Jazz (1900-1920: coletivo), Swing/Era das Big Bands (1930-1945: Count Basie, Duke Ellington, Benny Goodman, arranjos escritos), Bebop (1940s: Charlie Parker, Dizzy Gillespie, velocidade virtuosística, harmonias complexas), Cool Jazz (1950s: Miles Davis Birth of the Cool, West Coast Jazz), Hard Bop (1950s-60s: reação ao cool, volta às raízes blues/gospel), Modal Jazz (1959: Miles Davis Kind of Blue, John Coltrane, escalas modais ao invés de changes), Free Jazz (1960s: Ornette Coleman, Cecil Taylor, completa liberdade harmônica/rítmica), Jazz Fusion (1970s: Miles Davis Bitches Brew, combinação com rock, funk, eletrônica), Jazz Contemporâneo (1980s-2024: ecletismo total). Grandes inovadores: Louis Armstrong (primeiro grande solista improvisador, 1920s), Duke Ellington (compositor-bandleader supremo), Charlie Parker (revolucionou com bebop), Miles Davis (reinventou o jazz 5 vezes), John Coltrane (espiritualidade modal e free), Herbie Hancock (fusão eletrônica). O Jazz se internacionalizou, influenciando e sendo influenciado por músicas de todo o mundo (bossa nova brasileira, jazz europeu, afrobeat). Continua vivo e evoluindo no século XXI.$$, 1895, 2024, $$#FFD700$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Louis_Armstrong_restored.jpg/800px-Louis_Armstrong_restored.jpg$$, 9, true, '2025-10-09 02:09:20.82561+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_periods (tenant_id, id, name, description, start_year, end_year, theme_color, cover_image_url, chronological_order, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', 'a8106bcd-4791-46f4-b502-bda5fe19c041', $$Modernismo$$, $$O Modernismo musical (1900-1950) representa a ruptura mais radical com a tradição tonal milenar. Arnold Schoenberg desenvolve a atonalidade livre (Três Peças para Piano Op. 11, 1909) e depois o método dodecafônico ou serialismo (1921): composição com série de 12 sons sem hierarquia tonal, onde cada nota deve aparecer antes de qualquer repetição. Alban Berg e Anton Webern (Segunda Escola de Viena) estendem a técnica de maneiras distintas - Berg com expressionismo lírico (ópera Wozzeck), Webern com concisão aforística extrema. Igor Stravinsky choca Paris com ritmos irregulares, dissonâncias, politonalidade e primitivismo (A Sagração da Primavera, 1913, causou tumulto). Béla Bartók integra música folclórica húngara e romena autêntica em linguagem modernista (Música para Cordas, Percussão e Celesta). Neoclassicismo surge como reação ao romantismo e expressionismo: Stravinsky, Hindemith, Poulenc voltam a formas clássicas com linguagem moderna. Edgard Varèse explora organização de sons como massas e timbres, antecipando a música eletrônica (Ionisation para percussão). Charles Ives nos EUA experimenta com politonalidade e citações colagens décadas antes. Webern antecipa o serialismo integral do pós-guerra. Olivier Messiaen incorpora ritmos indianos e transcrições de canto de pássaros. Primeira e Segunda Guerras Mundiais influenciam profundamente a produção, com muitos compositores no exílio (Schoenberg, Stravinsky, Bartók, Hindemith fogem do nazismo).$$, 1900, 1950, $$#FF6347$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Vassily_Kandinsky%2C_1913_-_Composition_7.jpg/800px-Vassily_Kandinsky%2C_1913_-_Composition_7.jpg$$, 7, true, '2025-10-09 02:09:20.82561+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_periods (tenant_id, id, name, description, start_year, end_year, theme_color, cover_image_url, chronological_order, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', 'b0bef9be-0afc-4319-a8fe-a117f44e2dc9', $$Brasil Imperial$$, $$Com a independência, o Brasil desenvolve identidade musical própria. Surgem o choro no Rio de Janeiro e a modinha romântica. Influências europeias mesclam-se com ritmos afro-brasileiros. Carlos Gomes leva ópera brasileira à Europa.$$, 1822, 1889, $$#1abc9c$$, NULL, 20, true, '2025-12-14 20:49:33.510717+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_periods (tenant_id, id, name, description, start_year, end_year, theme_color, cover_image_url, chronological_order, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', 'bf731274-4647-4e61-aa72-2ac8a0b3944c', $$J-Pop Contemporâneo$$, $$O J-Pop torna-se fenômeno global. Música para anime e games atinge audiência mundial. Artistas como Hikaru Utada, Perfume e BABYMETAL reinventam o pop japonês. Vocaloid e música eletrônica ganham destaque.$$, 1990, 2025, $$#e91e63$$, NULL, 18, true, '2025-12-14 20:49:33.510717+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_periods (tenant_id, id, name, description, start_year, end_year, theme_color, cover_image_url, chronological_order, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', 'cb79f2bb-813a-485c-a6c8-2000fced9334', $$Shōwa Pós-Guerra (Japão)$$, $$Após a Segunda Guerra, o Japão reconstrói sua identidade musical. O enka preserva tradições melódicas japonesas. Surgem as primeiras influências do rock e pop ocidental. Desenvolvimento da indústria musical moderna.$$, 1945, 1989, $$#16a085$$, NULL, 17, true, '2025-12-14 20:49:33.510717+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_periods (tenant_id, id, name, description, start_year, end_year, theme_color, cover_image_url, chronological_order, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', 'd8c30e03-788e-4a90-970c-7585963b3949', $$Barroco$$, $$O período Barroco (1600-1750) é marcado pela dramaticidade, contraste dinâmico e ornamentação exuberante. Nasce a ópera em Florença (1600) com a Camerata Fiorentina (Peri, Caccini, Monteverdi), revolucionando a música dramática. O sistema tonal maior-menor se consolida definitivamente, substituindo os modos eclesiásticos. O baixo contínuo (basso continuo) torna-se a base harmônica obrigatória, com o cravo ou órgão realizando a harmonia cifrada sobre uma linha de baixo. Desenvolvem-se formas instrumentais: concerto grosso (Corelli, Vivaldi), sonata trio, suite de danças. A fuga atinge sua perfeição absoluta com J.S. Bach. A música serve à retórica dos afetos (Affektenlehre alemã): cada emoção tem sua representação musical codificada. O violino atinge maturidade técnica e acústica com os luthiers Stradivarius e Guarneri del Gesù. A música sacra luterana floresce (Bach, cantatas e paixões) enquanto a católica mantém tradição com música sacra italiana. Três estilos nacionais: italiano (ópera, concerto), francês (tragédie lyrique, suite), alemão (contraponto, música sacra). Compositores supremos: Monteverdi, Vivaldi, Handel, J.S. Bach.$$, 1600, 1750, $$#4B0082$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Antonio_Stradivari.jpg/800px-Antonio_Stradivari.jpg$$, 3, true, '2025-10-09 02:04:21.44846+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_periods (tenant_id, id, name, description, start_year, end_year, theme_color, cover_image_url, chronological_order, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', 'db0214a5-ccf3-4068-ac3a-681450eaf06c', $$Medieval$$, $$O período medieval da música ocidental abrange quase mil anos de desenvolvimento musical, desde a queda do Império Romano até o início do Renascimento. Caracteriza-se pela predominância da música litúrgica católica, com o desenvolvimento gradual do Cantochão (canto gregoriano) até formas polifônicas mais complexas como o organum e o moteto. A notação musical começou a ser sistematizada neste período por Guido d'Arezzo (século XI), permitindo a preservação e transmissão das obras. Os monastérios e catedrais eram os principais centros de criação musical, e a Igreja exercia controle absoluto sobre a produção musical erudita. A música secular também existia (trovadores, trouvères, Minnesänger), mas foi menos documentada. Compositores notáveis: Hildegard von Bingen, Léonin, Pérotin, Guillaume de Machaut.$$, 500, 1400, $$#8B4513$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Meister_der_Manessischen_Liederhandschrift_004.jpg/800px-Meister_der_Manessischen_Liederhandschrift_004.jpg$$, 1, true, '2025-10-09 02:04:21.44846+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_periods (tenant_id, id, name, description, start_year, end_year, theme_color, cover_image_url, chronological_order, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', 'e5fdb4e4-69c0-44fa-82f7-3fa21888bfd9', $$MPB - Música Popular Brasileira$$, $$MPB (Música Popular Brasileira) é termo cunhado nos anos 1960s para designar a música popular brasileira sofisticada pós-bossa nova, que incorpora elementos de samba, jazz, bossa nova, baião, rock, música erudita e tradições regionais. Surge no contexto de festivais de música (TV Record/TV Excelsior 1960s), ditadura militar (1964-1985: censura, exílio) e tropicalismo. Características: harmonias sofisticadas (influência de bossa nova e jazz), letras poéticas com consciência social, fusão de regional e cosmopolita, arranjos elaborados. Diferencia-se do samba tradicional pela complexidade harmônica e do rock pela manutenção de raízes brasileiras. Principais artistas: Chico Buarque (poesia urbana, resistência política), Caetano Veloso e Gilberto Gil (Tropicália: antropofagia cultural, fusão com rock psicodélico), Elis Regina (intérprete suprema), Milton Nascimento (Clube da Esquina: fusão mineira com jazz), Gal Costa, Maria Bethânia, Tom Jobim (transição bossa-MPB), Vinicius de Moraes, Baden Powell, João Bosco, Ivan Lins, Djavan (fusion com funk/soul). Movimentos internos: Tropicália (1967-68: Caetano, Gil, Mutantes, vanguarda), Clube da Esquina (1970s: Milton Nascimento, Beto Guedes, rock progressivo mineiro), Vanguarda Paulista (1980s: Arrigo Barnabé, Itamar Assumpção, experimentação). MPB resiste durante ditadura com metáforas (Cálice de Chico, Apesar de Você). Pós-redemocratização (1985-), MPB se diversifica enormemente: incorpora pop, funk carioca, música eletrônica, rap. Continua como espinha dorsal da música brasileira de qualidade.$$, 1960, 2024, $$#228B22$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Chico_Buarque_1966.jpg/800px-Chico_Buarque_1966.jpg$$, 10, true, '2025-10-09 02:09:20.82561+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_periods (tenant_id, id, name, description, start_year, end_year, theme_color, cover_image_url, chronological_order, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', 'e8ce8fcc-5d20-4557-be06-c908b975e141', $$Romântico$$, $$O Romantismo musical (1820-1900) enfatiza a subjetividade emocional, a imaginação, a expressão pessoal e o nacionalismo. Beethoven (fase tardia, sinfonias 6-9) abre o caminho para a liberdade formal. O Lied (canção de arte alemã) atinge sofisticação sublime com Schubert (mais de 600 lieds), Schumann e Brahms. O piano se torna instrumento virtuosístico supremo (Chopin poeta do piano, Liszt virtuose transcendental), capaz de grande expressividade e volume. Desenvolve-se o poema sinfônico (Liszt inventa o termo), música programática (Berlioz: Sinfonia Fantástica 1830) e o leitmotiv wagneriano (motivos musicais associados a personagens/ideias). A harmonia se expande com cromatismo intenso, modulações a tons distantes e ambiguidade tonal crescente (Wagner: Tristão e Isolda 1865, "acorde de Tristão"). Surgem escolas nacionais fortes: alemã (Brahms, Wagner), francesa (Berlioz, Franck, Saint-Saëns), russa (Grupo dos Cinco: Mussorgsky, Rimsky-Korsakov, Borodin, Cui, Balakirev + Tchaikovsky), checa (Smetana, Dvořák), escandinava (Grieg, Sibelius), cada uma com características próprias. A orquestra se expande enormemente: mais metais (tuba, trompete a pistões), percussão variada, harpa, até 100 músicos. A ópera se divide em grandes tradições nacionais: italiana (Verdi, Puccini: verismo), francesa (grand opéra, Berlioz), alemã (Wagner: Gesamtkunstwerk, "obra de arte total"), culminando nas tetralogias wagnerianas monumentais (O Anel do Nibelungo, 1876). O compositor romântico é visto como gênio inspirado, profeta incompreendido pelo público burguês.$$, 1820, 1900, $$#DC143C$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Caspar_David_Friedrich_-_Wanderer_above_the_sea_of_fog.jpg/800px-Caspar_David_Friedrich_-_Wanderer_above_the_sea_of_fog.jpg$$, 5, true, '2025-10-09 02:04:21.44846+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_periods (tenant_id, id, name, description, start_year, end_year, theme_color, cover_image_url, chronological_order, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', 'f2f37801-7669-4d4b-9bb9-2e79589d410e', $$Música Brasileira Contemporânea$$, $$A música brasileira diversifica-se enormemente. Sertanejo universitário domina charts. Funk carioca conquista periferias e elite. Rap e hip-hop ganham voz política. Samba e MPB renovam-se. Música brasileira é remix cultural constante.$$, 1980, 2025, $$#e74c3c$$, NULL, 23, true, '2025-12-14 20:49:33.510717+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_periods (tenant_id, id, name, description, start_year, end_year, theme_color, cover_image_url, chronological_order, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', 'f8ed8ab3-ef44-47e5-8a3f-80b4dd60f89a', $$Clássico$$, $$O Classicismo musical (1750-1820) representa o ideal iluminista de clareza, ordem, equilíbrio e razão. A forma sonata se torna a estrutura dominante: exposição (2 temas contrastantes), desenvolvimento (modulações e transformações) e recapitulação. A sinfonia evolui de três movimentos (abertura italiana) para quatro movimentos padronizados (Allegro-Andante-Minueto-Presto), estabelecendo-se como gênero supremo com Haydn (criou 104 sinfonias), Mozart (41 sinfonias) e Beethoven inicial (sinfonias 1-2). O quarteto de cordas atinge maturidade definitiva como medium supremo de música de câmara. O pianoforte substitui o cravo, permitindo dinâmicas graduais (crescendo, diminuendo). A orquestra se expande e padroniza: cordas divididas (1º e 2º violinos, violas, violoncelos, contrabaixos), madeiras a dois (2 flautas, 2 oboés, 2 fagotes, 2 clarinetes), metais (2 trompas, 2 trompetes), tímpanos. Melodias são cantábeis e memorizáveis, frases são simétricas (4+4 compassos), texturas são homofônicas (melodia acompanhada). A ópera se divide em seria (mitológica, Gluck reformou) e buffa (cômica, Mozart revolucionou). O compositor deixa de ser servo da igreja/corte e busca independência artística (Beethoven pioneiro). Viena é o centro musical indisputado da Europa (Haydn, Mozart, Beethoven).$$, 1750, 1820, $$#4169E1$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Wolfgang-amadeus-mozart_1.jpg/800px-Wolfgang-amadeus-mozart_1.jpg$$, 4, true, '2025-10-09 02:04:21.44846+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_periods (tenant_id, id, name, description, start_year, end_year, theme_color, cover_image_url, chronological_order, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', 'fec1fe65-dfd0-4797-bd51-693f3a612214', $$Impressionismo$$, $$O Impressionismo musical (1890-1920), paralelo ao movimento pictórico francês (Monet, Renoir), busca criar atmosferas nebulosas e impressões sensoriais ao invés de desenvolver temas. Claude Debussy é o principal representante, revolucionando a harmonia com acordes paralelos (movimento de blocos harmônicos sem preparação/resolução), escalas de tons inteiros (6 notas equidistantes, sem sensível), modos antigos (dórico, frígio, lídio, mixolídio) e escalas exóticas, especialmente pentatônica (5 notas, influência asiática do gamelão javanês que Debussy ouviu na Exposição Universal de Paris 1889). A funcionalidade harmônica tradicional (T-D-T) é suspensa em favor de progressões cromáticas paralelas e acordes como cores puras (nona, décima primeira, décima terceira sem resolução). Texturas são fluidas, translúcidas, quase nebulosas. Há fascínio pelo timbre puro e pela sonoridade em si, exploração de registros extremos do piano e orquestra. Maurice Ravel adiciona precisão neoclássica e brilhantismo orquestral ao impressionismo (Bolero 1928, orquestração de Quadros de uma Exposição de Mussorgsky). Escrita pianística explora pedais sobrepostos, ressonâncias etéreas e registros agudos cintilantes. Títulos evocam natureza, água, luz, perfumes (Prélude à l'après-midi d'un faune, La Mer, Reflets dans l'eau, Jardins sous la pluie). O movimento antecipa muitos procedimentos do século XX: politonalidade, clusters, início do serialismo. Outros compositores: Erik Satie (precursor minimalista), Fauré (lirismo francês), Dukas, Delius.$$, 1890, 1920, $$#9370DB$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Claude_Monet%2C_Impression%2C_soleil_levant.jpg/800px-Claude_Monet%2C_Impression%2C_soleil_levant.jpg$$, 6, true, '2025-10-09 02:04:21.44846+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

COMMIT;