-- =============================================
-- Migration: 022_history_composers.sql
-- Table: core.history_composers
-- Source CSV: historia_compositores_rows.csv
-- Generated: 2026-02-28T16:15:03.658Z
-- Rows: 40
-- =============================================

BEGIN;

INSERT INTO core.history_composers (tenant_id, id, full_name, artistic_name, period_id, birth_country, birth_date, death_date, biography, photo_url, importance_level, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '01826610-9488-44c5-92c3-4edfd0470bee', $$Georg Friedrich Händel$$, $$Handel$$, 'd8c30e03-788e-4a90-970c-7585963b3949', $$Alemanha$$, '1685-02-23'::date, '1759-04-14'::date, $$George Frideric Handel foi um compositor barroco alemão que se naturalizou britânico. Nasceu em Halle, Alemanha, em 1685, mesmo ano que Bach e Scarlatti. Mudou-se para Londres onde fez carreira brilhante. Foi o maior compositor de óperas italianas na Inglaterra e revolucionou o gênero do oratório em inglês. Seu Messias é uma das obras corais mais executadas da história. Compôs também música instrumental como Water Music e Music for the Royal Fireworks. Teve vida longa e produtiva, sendo enterrado na Abadia de Westminster com honras de estado.$$, NULL, 5, true, '2025-12-15 02:37:56.378902+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_composers (tenant_id, id, full_name, artistic_name, period_id, birth_country, birth_date, death_date, biography, photo_url, importance_level, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '102ed8a3-0f8b-4bd4-9bcc-ea6ccbf49c16', $$Jakob Ludwig Felix Mendelssohn Bartholdy$$, $$Mendelssohn$$, 'e8ce8fcc-5d20-4557-be06-c908b975e141', $$Alemanha$$, '1809-02-03'::date, '1847-11-04'::date, $$Felix Mendelssohn (1809-1847) foi criança prodígio de família abastada judia convertida ao protestantismo. Aos 9 anos estreou como pianista, aos 17 compôs Sonho de Uma Noite de Verão (abertura). Em 1829, aos 20 anos, regeu a Paixão segundo São Mateus de Bach em Berlim, 100 anos após morte do compositor - evento que iniciou o renascimento bachiano. Foi um dos primeiros maestros profissionais modernos. Fundou Conservatório de Leipzig (1843). Viajou pela Europa (Itália, Escócia, Inglaterra). Compôs 5 sinfonias (Italiana, Escocesa), Concerto para Violino (um dos mais populares), oratório Elias, música de câmara, peças para piano (Canções Sem Palavras). Morreu prematuramente aos 38 anos de derrame cerebral, meses após morte da irmã amada Fanny (também compositora talentosa). Sua música combina elegância clássica com lirismo romântico.$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Mendelssohn_Bartholdy.jpg/800px-Mendelssohn_Bartholdy.jpg$$, 4, true, '2025-10-09 02:50:34.631005+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_composers (tenant_id, id, full_name, artistic_name, period_id, birth_country, birth_date, death_date, biography, photo_url, importance_level, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '242645c7-e035-4868-8fbb-bd67916f7ebe', $$Béla Viktor János Bartók$$, $$Bartók$$, 'a8106bcd-4791-46f4-b502-bda5fe19c041', $$Hungria$$, '1881-03-25'::date, '1945-09-26'::date, $$Béla Bartók (1881-1945) foi compositor, pianista e etnomusicólogo pioneiro. Estudou Academia de Música de Budapeste. Com Zoltán Kodály, viajou por vilarejos húngaros, romenos, eslovacos, turcos, árabes (1906-1918), gravando com fonógrafo cilíndrico mais de 10.000 canções folclóricas autênticas (não urbanas, mas camponesas primitivas). Incorporou ritmos, escalas e melodias folclóricas em linguagem modernista: Música para Cordas, Percussão e Celesta (1936), Concerto para Orquestra (1943), 6 Quartetos de Cordas (obras-primas do gênero), Mikrokosmos (153 peças progressivas para piano), 3 concertos para piano, ópera O Castelo do Barba Azul. Técnicas: escalas folclóricas, ritmos irregulares (aksak búlgaro), clusters, politonalidade, batidas percussivas no piano. Fugiu nazismo (1940), exilando-se em Nova York, onde viveu em pobreza. Morreu de leucemia aos 64 anos, pobre e pouco reconhecido. Pós-morte, tornou-se um dos mais influentes do século XX.$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Bartok_Bela_1927.jpg/800px-Bartok_Bela_1927.jpg$$, 4, true, '2025-10-09 02:50:34.631005+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_composers (tenant_id, id, full_name, artistic_name, period_id, birth_country, birth_date, death_date, biography, photo_url, importance_level, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '26f0c4d7-e0f6-4ba3-a360-574ddf65d2e6', $$Johann Pachelbel$$, $$Pachelbel$$, 'd8c30e03-788e-4a90-970c-7585963b3949', $$Alemanha$$, '1653-09-01'::date, '1706-03-09'::date, $$Johann Pachelbel foi um compositor e organista alemão do período Barroco. Nasceu em Nuremberg em 1653. Foi um dos compositores mais importantes de sua época, especialmente famoso por suas obras para órgão e música de câmara. Seu Canon em Ré maior é uma das peças mais conhecidas da música clássica, embora tenha sido redescoberta apenas no século XX. Trabalhou em várias cidades alemãs e foi professor de Johann Christoph Bach, irmão mais velho de J.S. Bach. Sua música influenciou profundamente o desenvolvimento da fuga e do coral luterano.$$, NULL, 4, true, '2025-12-15 02:37:56.378902+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_composers (tenant_id, id, full_name, artistic_name, period_id, birth_country, birth_date, death_date, biography, photo_url, importance_level, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '280b11e5-12eb-4b8e-9099-d4dff10fcc18', $$Milton Silva Campos do Nascimento$$, $$Milton Nascimento$$, 'f2f37801-7669-4d4b-9bb9-2e79589d410e', $$Brasil$$, '1942-10-26'::date, NULL, $$Milton Nascimento possui uma das vozes mais extraordinárias da história da música. Nascido no Rio de Janeiro, criado em Três Pontas, Minas Gerais, sua voz tem alcance e timbre únicos. Venceu o II Festival Internacional da Canção com "Travessia" (1967). Líder do movimento Clube da Esquina, ao lado de Lô Borges, Fernando Brant e Toninho Horta, criou um som que mescla MPB, jazz, rock, música erudita e raízes mineiras. Álbuns como "Clube da Esquina" (1972) e "Minas" (1975) são obras-primas absolutas. Suas harmonias sofisticadas influenciaram jazz musicians como Wayne Shorter e Herbie Hancock. "Maria Maria" e "Ponta de Areia" são hinos brasileiros.$$, NULL, 5, true, '2025-12-14 20:49:33.510717+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_composers (tenant_id, id, full_name, artistic_name, period_id, birth_country, birth_date, death_date, biography, photo_url, importance_level, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '2c66f118-3e49-479f-99b8-e7fde3340932', $$Frédéric François Chopin$$, $$Chopin$$, 'e8ce8fcc-5d20-4557-be06-c908b975e141', $$Polônia$$, '1810-03-01'::date, '1849-10-17'::date, $$Frédéric Chopin (1810-1849) é o poeta do piano romântico. Nasceu na Polônia, filho de pai francês e mãe polonesa. Estudou no Conservatório de Varsóvia. Em 1830, deixou a Polônia pouco antes da Revolta de Novembro contra a Rússia, nunca mais retornando. Estabeleceu-se em Paris (1831), onde se tornou sensação nos salões aristocráticos. Ao contrário dos virtuoses showmen como Liszt, Chopin preferia a intimidade dos salões, detestando grandes concertos públicos. Compôs quase exclusivamente para piano solo (exceto 2 concertos para piano, sonata para violoncelo, algumas canções). Criou ou aperfeiçoou formas: balada (narrativa musical), scherzo pianístico, noturno poético, estudo de concerto (técnica + arte), prelúdio moderno, valsa de concerto. Incorporou elementos folclóricos poloneses (mazurca, polonaise) elevados a arte erudita. Relacionamento famoso com a escritora George Sand (1838-1847). Sofria de tuberculose desde jovem, falecendo aos 39 anos em Paris. Seu coração foi levado para Varsóvia conforme seu desejo.$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Frederic_Chopin_photo.jpeg/800px-Frederic_Chopin_photo.jpeg$$, 5, true, '2025-10-09 02:04:40.115836+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_composers (tenant_id, id, full_name, artistic_name, period_id, birth_country, birth_date, death_date, biography, photo_url, importance_level, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '2d6c26aa-002e-4fe4-a5be-5f1da2ceaad8', $$Marcus Vinicius da Cruz e Mello Moraes$$, $$Vinicius de Moraes$$, '798ce272-a0af-40a3-97c5-11b83fe0addb', $$Brasil$$, '1913-10-19'::date, '1980-07-09'::date, $$Vinicius de Moraes foi poeta, dramaturgo, diplomata e compositor. Conhecido como "o poetinha", suas letras transformaram a canção popular brasileira em alta poesia. Diplomata de carreira, serviu em Los Angeles, Paris e Montevidéu, mas a música sempre foi sua paixão. Parceiro de Tom Jobim, Baden Powell, Toquinho e muitos outros, escreveu algumas das mais belas letras da música brasileira. "Garota de Ipanema", "Chega de Saudade", "Aquarela do Brasil" - todas com letras que são poemas. Casou-se nove vezes e dizia: "Sou essencialmente um homem de amor". Sua obra poético-musical é patrimônio da língua portuguesa.$$, NULL, 5, true, '2025-12-14 20:49:33.510717+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_composers (tenant_id, id, full_name, artistic_name, period_id, birth_country, birth_date, death_date, biography, photo_url, importance_level, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '2d850638-b14d-4fb8-b987-d85c7892ea62', $$Francisco Buarque de Hollanda$$, $$Chico Buarque$$, '480e5257-9aca-48e8-971f-f19794fc0dcf', $$Brasil$$, '1944-06-19'::date, NULL, $$Chico Buarque é um dos maiores artistas brasileiros vivos. Filho do historiador Sérgio Buarque de Hollanda, desde jovem mostrou talento extraordinário para a palavra. Venceu festivais nos anos 1960 com "A Banda" e "Roda Viva". Durante a ditadura militar, suas letras inteligentes e metafóricas driblavam a censura enquanto denunciavam o regime - "Apesar de Você", "Cálice". Criou heterônimos como Julinho da Adelaide para burlar censores. Além de compositor, é romancista premiado ("Budapeste", "Leite Derramado"). Suas letras têm qualidade literária rara, trabalhando com trocadilhos, metáforas e estruturas poéticas complexas como em "Construção".$$, NULL, 5, true, '2025-12-14 20:49:33.510717+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_composers (tenant_id, id, full_name, artistic_name, period_id, birth_country, birth_date, death_date, biography, photo_url, importance_level, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '2ef6c728-858b-41cf-bb9d-e844783a0969', $$Achille-Claude Debussy$$, $$Debussy$$, 'fec1fe65-dfd0-4797-bd51-693f3a612214', $$França$$, '1862-08-22'::date, '1918-03-25'::date, $$Claude Debussy (1862-1918) é o pai do Impressionismo musical e um dos compositores mais revolucionários. Estudou no Conservatório de Paris (1872-1884), ganhando Prix de Rome (1884). Rompeu com tradição romântica alemã, criando linguagem radicalmente nova. Influências: gamelão javanês (Exposição Universal de Paris 1889), simbolismo literário (Mallarmé, Verlaine), pintura impressionista (Monet). Características: acordes paralelos (quintas, nonas), escalas de tons inteiros, modos antigos, pentatônica, politonalidade incipiente, orquestração refinadíssima (timbres puros, cores). Obras principais: Prélude à l'après-midi d'un faune (1894, baseado em Mallarmé), La Mer (1905, 3 esboços sinfônicos do mar), ópera Pelléas et Mélisande (1902, texto de Maeterlinck), 24 Préludes para piano (1910-1913: Des pas sur la neige, Feux d'artifice), Estampes, Images. Escrita pianística explora pedais, ressonâncias, registros etéreos. Vida pessoal turbulenta: 2 casamentos, amante Emma Bardac. Nacionalista durante 1ª Guerra Mundial, assinou obras "Claude Debussy, musicien français". Morreu de câncer retal aos 55 anos, durante bombardeio alemão de Paris (1918). Influenciou profundamente música do século XX: Ravel, Messiaen, Boulez, jazz (Bill Evans).$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Claude_Debussy_ca_1908%2C_foto_av_F%C3%A9lix_Nadar.jpg/800px-Claude_Debussy_ca_1908%2C_foto_av_F%C3%A9lix_Nadar.jpg$$, 5, true, '2025-10-09 02:15:02.70535+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_composers (tenant_id, id, full_name, artistic_name, period_id, birth_country, birth_date, death_date, biography, photo_url, importance_level, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '37681c66-7ef1-4634-b268-fbc1be69e4c5', $$Ludwig van Beethoven$$, $$Beethoven$$, 'f8ed8ab3-ef44-47e5-8a3f-80b4dd60f89a', $$Alemanha$$, '1770-12-17'::date, '1827-03-26'::date, $$Ludwig van Beethoven nasceu em Bonn em 1770. Seu pai, tenor na corte, deu-lhe educação musical rigorosa e às vezes brutal, sonhando criar um novo Mozart. Em 1792, mudou-se para Viena para estudar com Haydn. Beethoven revolucionou a música, expandindo dramaticamente a forma sonata, a sinfonia e o concerto. Sua obra divide-se em três períodos: inicial influência de Haydn e Mozart, médio obras heroicas como a 5ª Sinfonia e tardio quartetos de cordas transcendentais. A tragédia de sua vida foi a surdez progressiva, diagnosticada aos 26 anos. Em 1802, escreveu o Testamento de Heiligenstadt contemplando o suicídio. Mas decidiu viver pela arte. Surpreendentemente, suas obras mais profundas - 9ª Sinfonia, Missa Solemnis, últimos quartetos - foram compostas quando completamente surdo. Beethoven foi o primeiro compositor verdadeiramente independente, não servindo a nenhuma corte. Morreu em 1827 durante uma tempestade, e 20000 pessoas compareceram ao seu funeral.$$, $$https://upload.wikimedia.org/wikipedia/commons/6/6f/Beethoven.jpg$$, 5, true, '2025-10-09 02:04:40.115836+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_composers (tenant_id, id, full_name, artistic_name, period_id, birth_country, birth_date, death_date, biography, photo_url, importance_level, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '3788e175-a745-4d5e-bf98-bd011644db39', $$Kōsaku Yamada$$, $$Yamada$$, '17bf83a0-e91e-4983-915f-51ace4da29ea', $$Japão$$, '1886-06-09'::date, '1965-12-29'::date, $$Kōsaku Yamada foi o arquiteto da música orquestral japonesa moderna. Estudou composição em Berlim com Max Bruch e foi influenciado pelo romantismo alemão. Ao retornar ao Japão, fundou a primeira orquestra sinfônica profissional do país e compôs a primeira ópera japonesa em estilo ocidental. Sua obra "Kurai Tobira" (Porta Escura) tornou-se uma das canções mais amadas do Japão. Durante sua longa vida, foi mentor de toda uma geração de compositores japoneses.$$, NULL, 5, true, '2025-12-14 20:49:33.510717+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_composers (tenant_id, id, full_name, artistic_name, period_id, birth_country, birth_date, death_date, biography, photo_url, importance_level, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '397a64ad-cf05-411e-b00b-6ba14db292a4', $$Giacomo Antonio Domenico Michele Secondo Maria Puccini$$, $$Puccini$$, 'e8ce8fcc-5d20-4557-be06-c908b975e141', $$Itália$$, '1858-12-29'::date, '1924-11-29'::date, $$Giacomo Puccini (1858-1924) foi o sucessor de Verdi como maior compositor de ópera italiana. Nasceu em dinastia de músicos de igreja em Lucca. Estudou no Conservatório de Milão. Primeira ópera de sucesso: Manon Lescaut (1893). Depois vieram 3 óperas supremas de um ato (Il Trittico, 1918) e especialmente: La Bohème (1896, vida boêmia em Paris, com soprano Mimì), Tosca (1900, drama político violento), Madama Butterfly (1904, gueixa japonesa abandonada), Turandot (1926, princesa chinesa gélida, inacabada - morreu de câncer de garganta antes de terminar, completada por Franco Alfano). Estilo: verismo (realismo), melodias inesquecíveis, orquestração refinada (influência de Wagner e Debussy), senso dramático aguçado, heroínas comoventes que morrem tragicamente. Árias famosas: Che gelida manina, O mio babbino caro, Nessun dorma, Vissi d'arte. Vida pessoal: escândalos, casos amorosos, paixão por carros e barcos. Morreu em Bruxelas durante tratamento de câncer aos 65 anos.$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Puccini.jpg/800px-Puccini.jpg$$, 4, true, '2025-10-09 02:50:34.631005+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_composers (tenant_id, id, full_name, artistic_name, period_id, birth_country, birth_date, death_date, biography, photo_url, importance_level, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '3c106370-db4c-4b34-bfdf-2b995c954036', $$Gilberto Passos Gil Moreira$$, $$Gilberto Gil$$, '480e5257-9aca-48e8-971f-f19794fc0dcf', $$Brasil$$, '1942-06-26'::date, NULL, $$Gilberto Gil é um dos maiores nomes da música brasileira. Nascido em Salvador, Bahia, foi cofundador do movimento Tropicália ao lado de Caetano Veloso. Mestre em mesclar estilos - do baião ao reggae, do samba ao rock - sua versatilidade musical é impressionante. Guitarrista virtuoso, foi um dos primeiros a usar guitarra elétrica na MPB. Preso e exilado pela ditadura (1969-72), voltou e continuou produzindo obras seminais. Foi Ministro da Cultura (2003-2008), onde defendeu cultura digital livre e software livre. "Aquele Abraço" virou hino do Rio. Sua música "Toda Menina Baiana" celebra a cultura afro-baiana. Continua em atividade, ícone da cultura brasileira.$$, NULL, 5, true, '2025-12-14 20:49:33.510717+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_composers (tenant_id, id, full_name, artistic_name, period_id, birth_country, birth_date, death_date, biography, photo_url, importance_level, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '3c501d98-c0ca-4032-8d4c-4528c1c6a930', $$Antônio Carlos Gomes$$, $$Carlos Gomes$$, 'b0bef9be-0afc-4319-a8fe-a117f44e2dc9', $$Brasil$$, '1836-07-11'::date, '1896-09-16'::date, $$Carlos Gomes nasceu em Campinas, São Paulo, filho de maestro. Estudou no Conservatório do Rio de Janeiro e, com bolsa de Dom Pedro II, foi para a Itália estudar no Conservatório de Milão. Sua ópera "Il Guarany" (1870), baseada no romance de José de Alencar, estreou no Teatro alla Scala com sucesso triunfal. Foi o primeiro compositor das Américas a ter uma ópera encenada no Scala. Suas óperas mesclam bel canto italiano com temáticas indigenistas e brasileiras. É patrono da cadeira nº 15 da Academia Brasileira de Música.$$, NULL, 5, true, '2025-12-14 20:49:33.510717+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_composers (tenant_id, id, full_name, artistic_name, period_id, birth_country, birth_date, death_date, biography, photo_url, importance_level, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '4c5a9cfe-a040-4ee5-9dc9-a479a0bf8876', $$Giuseppe Fortunino Francesco Verdi$$, $$Verdi$$, 'e8ce8fcc-5d20-4557-be06-c908b975e141', $$Itália$$, '1813-10-10'::date, '1901-01-27'::date, $$Giuseppe Verdi (1813-1901) é o maior compositor de ópera italiana do século XIX e um dos maiores de todos os tempos. Nasceu em família camponesa pobre, estudou música com mecenato local. Primeira ópera, Oberto (1839), foi sucesso moderado em Milão. Após tragédia pessoal (morte da esposa e dois filhos em 1840), entrou em depressão mas retornou triunfalmente com Nabucco (1842), cujo coro Va, pensiero tornou-se hino não-oficial da unificação italiana. Período dos "anos de galés" (1843-1850): produziu óperas anualmente. Fase intermediária: Rigoletto (1851), Il Trovatore (1853), La Traviata (1853) - trilogia popular suprema. Fase tardia: óperas cada vez mais sofisticadas (Simon Boccanegra, La Forza del Destino, Don Carlos), culminando em obras-primas shakespearianas Otello (1887, aos 74 anos) e Falstaff (1893, aos 80, ópera cômica genial). Também Requiem (1874), dedicado a Manzoni, uma das maiores obras corais. Verdi foi símbolo do Risorgimento (unificação italiana): seu nome era grito político (Viva VERDI = Viva Vittorio Emanuele Re D'Italia). Eleito senador do Reino da Itália. Casou-se com soprano Giuseppina Strepponi. Últimos anos dedicou-se à filantropia (Casa di Riposo per Musicisti em Milão, casa de repouso para músicos). Morreu aos 87 anos; 300.000 pessoas no funeral.$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Giuseppe_Verdi_by_Giovanni_Boldini.jpg/800px-Giuseppe_Verdi_by_Giovanni_Boldini.jpg$$, 5, true, '2025-10-09 02:15:02.70535+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_composers (tenant_id, id, full_name, artistic_name, period_id, birth_country, birth_date, death_date, biography, photo_url, importance_level, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '60e9514d-57d1-4d87-860f-d1314507b8d0', $$Johann Strauss II$$, $$Rei da Valsa$$, 'e8ce8fcc-5d20-4557-be06-c908b975e141', $$Áustria$$, '1825-10-25'::date, '1899-06-03'::date, $$Johann Strauss II (1825-1899), conhecido como "Rei da Valsa", foi o mais famoso da dinastia Strauss. Filho de Johann Strauss I (também compositor), contra a vontade do pai estudou música secretamente e formou sua própria orquestra aos 19 anos, rivaliz ando com o pai. Tornou-se o compositor de música de dança mais popular da Europa. Compôs mais de 400 valsas, polcas e marchas, além de 16 operetas. Suas valsas elevaram a dança popular vienense a forma de arte sinfônica. A mais famosa, An der schönen blauen Donau (Danúbio Azul, 1867), tornou-se o hino não-oficial da Áustria. Suas operetas, especialmente Die Fledermaus (O Morcego, 1874), são pilares do repertório até hoje. Foi diretor musical de bailes da corte imperial de Viena e excursionou pela Europa e EUA. Brahms admirava profundamente sua música. Regeu no Jubileu da Rainha Vitória em Londres. Sua música simboliza a alegria e elegância da Viena imperial. Morreu aos 73 anos, com funeral de Estado.$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Johann_Strauss_II_by_August_Eisenmenger.jpg/800px-Johann_Strauss_II_by_August_Eisenmenger.jpg$$, 5, true, '2025-10-09 02:04:40.115836+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_composers (tenant_id, id, full_name, artistic_name, period_id, birth_country, birth_date, death_date, biography, photo_url, importance_level, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '66697bd8-3ad7-4e00-82ef-4b35686d41b5', $$Alfredo da Rocha Viana Filho$$, $$Pixinguinha$$, '058f61ff-806e-4179-8c5b-2cd597b36d76', $$Brasil$$, '1897-04-23'::date, '1973-02-17'::date, $$Pixinguinha é considerado um dos maiores músicos da história do Brasil. Nascido no bairro de Piedade, Rio de Janeiro, filho de músico, aos 14 anos já era flautista profissional. Revolucionou o choro com suas composições sofisticadas e arranjos inovadores. "Carinhoso" é uma das músicas mais gravadas da história brasileira. Viajou a Paris com o grupo Os Oito Batutas em 1922, levando música brasileira à Europa. Como arranjador da Rádio Nacional, orquestrou centenas de músicas. Seu estilo único combinou o choro tradicional com influências do jazz, criando a sonoridade que define a música brasileira instrumental.$$, NULL, 5, true, '2025-12-14 20:49:33.510717+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_composers (tenant_id, id, full_name, artistic_name, period_id, birth_country, birth_date, death_date, biography, photo_url, importance_level, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '6aae14ae-1c25-47ed-80d5-8112a9674d2f', $$Aaron Copland$$, NULL, 'a8106bcd-4791-46f4-b502-bda5fe19c041', $$Estados Unidos$$, '1900-11-14'::date, '1990-12-02'::date, $$Aaron Copland (1900-1990) é o compositor americano mais importante do século XX, criando som distintamente americano. Filho de imigrantes judeus russos no Brooklyn. Estudou com Nadia Boulanger em Paris (1921-1924). Inicialmente modernista (influência de Stravinsky), depois adotou estilo mais acessível (populismo). Obras principais: balés Appalachian Spring (1944, Prêmio Pulitzer, tema Shaker Simple Gifts), Billy the Kid (1938, faroeste), Rodeo (1942, rodeio, Hoe-Down famoso), Fanfare for the Common Man (1942, 2ª Guerra), sinfonia Sinfonia nº 3 (incorpora Fanfare), Concerto para Clarinete (para Benny Goodman, fusão com jazz), música de câmara, canções. Estilo: harmonias abertas (quartas e quintas), melodias simples folclóricas, ritmos de dança americana, orquestração clara. Também compositor de cinema (Of Mice and Men, The Heiress - Oscar). Professor influente, escritor sobre música. Abertamente homossexual em época repressiva. Viveu 90 anos.$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Aaron_Copland_1970.JPG/800px-Aaron_Copland_1970.JPG$$, 4, true, '2025-10-09 02:50:34.631005+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_composers (tenant_id, id, full_name, artistic_name, period_id, birth_country, birth_date, death_date, biography, photo_url, importance_level, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '6ab9f4fb-93a2-441a-a97f-ee974eef8838', $$Franz Joseph Haydn$$, $$Papa Haydn$$, 'f8ed8ab3-ef44-47e5-8a3f-80b4dd60f89a', $$Áustria$$, '1732-03-31'::date, '1809-05-31'::date, $$Joseph Haydn (1732-1809) estabeleceu as formas da sinfonia e quarteto de cordas clássicos. Nasceu em família modesta, menino soprano na Catedral de Viena. Aos 29 anos, entrou ao serviço dos Príncipes Esterházy (1761-1790), uma das famílias mais ricas da Europa, onde teve orquestra à disposição por 30 anos para experimentar. Compôs 104 sinfonias, 68 quartetos de cordas, concertos, óperas, missas. Estabeleceu a forma sonata de 4 movimentos, desenvolveu minueto e scherzo. Foi mentor de Mozart (amizade mútua admiração) e professor de Beethoven. Visitou Londres duas vezes (1791-1792, 1794-1795), onde escreveu 12 Sinfonias de Londres (últimas e melhores). Morreu em Viena durante bombardeio napoleônico aos 77 anos. Apelidado Papa Haydn pela bondade paternal.$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Joseph_Haydn.jpg/800px-Joseph_Haydn.jpg$$, 4, true, '2025-10-09 02:50:34.631005+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_composers (tenant_id, id, full_name, artistic_name, period_id, birth_country, birth_date, death_date, biography, photo_url, importance_level, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '6bdf2c72-6099-4fc5-9294-a887f79ac000', $$Ryuichi Sakamoto$$, $$Sakamoto$$, 'bf731274-4647-4e61-aa72-2ac8a0b3944c', $$Japão$$, '1952-01-17'::date, '2023-03-28'::date, $$Ryuichi Sakamoto foi um dos músicos mais influentes e inovadores do Japão. Começou como pioneiro da música eletrônica nos anos 1970 com o Yellow Magic Orchestra, que influenciou techno, hip-hop e música eletrônica mundial. Venceu o Oscar de Melhor Trilha Sonora por "O Último Imperador" (1987). Sua carreira solo explorou fusões únicas de eletrônica, música clássica contemporânea e sons ambientais. Ativista anti-nuclear após Fukushima, usou sua música para causas humanitárias. Continuou criando até sua morte em 2023, deixando legado imenso.$$, NULL, 5, true, '2025-12-14 20:49:33.510717+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_composers (tenant_id, id, full_name, artistic_name, period_id, birth_country, birth_date, death_date, biography, photo_url, importance_level, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '83c61d11-1558-4af3-b50d-4bc83f83a934', $$Yatsuhashi Kengyō$$, $$Yatsuhashi$$, '8c167784-6592-4f6f-bb74-422c863439ec', $$Japão$$, '1614-01-01'::date, '1685-01-01'::date, $$Yatsuhashi Kengyō nasceu em Kyoto durante o início do período Edo. Cego desde a infância, dedicou-se completamente à música do koto. Revolucionou o instrumento ao criar o estilo danmono (composições em seções) e ao adaptar músicas populares para koto solo, antes tocado apenas como acompanhamento. Suas inovações permitiram que o koto se tornasse um instrumento de concerto. Fundou a escola Yatsuhashi de koto, que influencia músicos até hoje.$$, NULL, 5, true, '2025-12-14 20:49:33.510717+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_composers (tenant_id, id, full_name, artistic_name, period_id, birth_country, birth_date, death_date, biography, photo_url, importance_level, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '83e3fcb3-ef41-434e-96f3-179028ff2957', $$Mamoru Fujisawa$$, $$Joe Hisaishi$$, 'bf731274-4647-4e61-aa72-2ac8a0b3944c', $$Japão$$, '1950-12-06'::date, NULL, $$Joe Hisaishi (nome artístico de Mamoru Fujisawa) é o compositor por trás da magia sonora do Studio Ghibli. Sua parceria com Hayao Miyazaki produziu algumas das trilhas de anime mais amadas: "Meu Amigo Totoro", "A Viagem de Chihiro", "O Castelo Animado", "Princesa Mononoke". Seu estilo combina minimalismo inspirado em Philip Glass com melodias profundamente emotivas e toques da música tradicional japonesa. Suas trilhas não apenas acompanham os filmes - elas contam histórias paralelas que capturam a essência mágica dos mundos de Miyazaki.$$, NULL, 5, true, '2025-12-14 20:49:33.510717+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_composers (tenant_id, id, full_name, artistic_name, period_id, birth_country, birth_date, death_date, biography, photo_url, importance_level, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '85e30fba-02f7-4cf9-af4b-d2cf3389a1b9', $$Robert Alexander Schumann$$, NULL, 'e8ce8fcc-5d20-4557-be06-c908b975e141', $$Alemanha$$, '1810-06-08'::date, '1856-07-29'::date, $$Robert Schumann (1810-1856) é um dos compositores mais românticos e literários. Inicialmente estudou direito mas dedicou-se à música. Tentou carreira de virtuose do piano mas lesionou mão permanentemente (aparelho de fortalecimento de dedos). Voltou-se para composição e crítica musical, fundando Neue Zeitschrift für Musik (1834), revista onde defendeu jovens talentos (Chopin, Brahms) e atacou filisteus. Apaixonou-se por Clara Wieck (filha de seu professor), mas o pai dela opôs-se violentamente. Só conseguiram casar após processo judicial (1840). Clara tornou-se pianista mais famosa da Europa, interpretando obras de Robert. Fases criativas: anos 1830s (piano: Carnaval, Estudos Sinfônicos, Cenas Infantis, Kreisleriana), 1840 (ano das canções: 140 Lieder, incluindo Dichterliebe, Frauenliebe und Leben), 1841 (sinfonias), 1842 (câmara), 1843 (oratórios). 4 sinfonias, Concerto para Piano (dedicado a Clara), música de câmara. Sofria de transtorno mental progressivo (possivelmente bipolar + sífilis + depressão). Tentou suicídio em 1854 atirando-se no Reno e foi resgatado. Internado voluntariamente em asilo (Endenich), onde morreu aos 46 anos. Clara dedicou resto da vida (40 anos) a promover sua música. Brahms era amigo íntimo do casal.$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Robert_Schumann_1850.jpg/800px-Robert_Schumann_1850.jpg$$, 5, true, '2025-10-09 02:22:14.349741+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_composers (tenant_id, id, full_name, artistic_name, period_id, birth_country, birth_date, death_date, biography, photo_url, importance_level, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '86b7ff25-1dbb-4827-b29c-3b7d3a4b8709', $$Antônio Carlos Brasileiro de Almeida Jobim$$, $$Tom Jobim$$, '798ce272-a0af-40a3-97c5-11b83fe0addb', $$Brasil$$, '1927-01-25'::date, '1994-12-08'::date, $$Tom Jobim é o compositor brasileiro mais importante de todos os tempos. Pianista, compositor e arranjador, criou a bossa nova ao lado de João Gilberto e Vinicius de Moraes no final dos anos 1950. "Garota de Ipanema", composta com Vinicius, é a segunda música mais gravada da história (depois de Yesterday dos Beatles). Suas composições são standards do jazz mundial, gravadas por Frank Sinatra, Ella Fitzgerald, Stan Getz e inúmeros outros. Mestre das harmonias sofisticadas, influenciado por Debussy e Villa-Lobos, criou um idioma musical único que definiu o Brasil para o mundo. O Aeroporto Internacional do Rio de Janeiro leva seu nome.$$, NULL, 5, true, '2025-12-14 20:49:33.510717+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_composers (tenant_id, id, full_name, artistic_name, period_id, birth_country, birth_date, death_date, biography, photo_url, importance_level, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '8ac10d5e-503e-4a46-a976-f79e987686f3', $$Francisca Edwiges Neves Gonzaga$$, $$Chiquinha Gonzaga$$, 'b0bef9be-0afc-4319-a8fe-a117f44e2dc9', $$Brasil$$, '1847-10-17'::date, '1935-02-28'::date, $$Chiquinha Gonzaga foi revolucionária em todos os sentidos. Em uma época em que mulheres não tinham direitos, divorciou-se, perdeu a guarda dos filhos e tornou-se pianeira profissional. Compôs "Ó Abre Alas" (1899), a primeira marchinha de carnaval do Brasil. Foi abolicionista e republicana fervorosa. Fundou a Sociedade Brasileira de Autores Teatrais (SBAT), lutando pelos direitos autorais dos compositores. Compôs mais de 2000 músicas, incluindo operetas, maxixes, valsas e choros. Tocou piano até os 87 anos, sendo uma das artistas mais longevas e produtivas do Brasil.$$, NULL, 5, true, '2025-12-14 20:49:33.510717+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_composers (tenant_id, id, full_name, artistic_name, period_id, birth_country, birth_date, death_date, biography, photo_url, importance_level, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '8d121f8d-363a-4825-9eca-d62553d1ea53', $$Johann Sebastian Bach$$, $$J.S. Bach$$, 'd8c30e03-788e-4a90-970c-7585963b3949', $$Alemanha$$, '1685-03-21'::date, '1750-07-28'::date, $$Johann Sebastian Bach nasceu em Eisenach em 1685, em uma família de músicos. Ficou órfão aos 10 anos e foi criado pelo irmão mais velho. Trabalhou como organista em várias igrejas e capelas, incluindo a Thomaskirche em Leipzig, onde passou seus últimos 27 anos. Casou-se duas vezes e teve 20 filhos, dos quais 4 se tornaram compositores importantes. Bach dominou todos os gêneros musicais de sua época, exceto ópera. Sua obra representa o ápice do Barroco alemão, unindo profunda espiritualidade luterana com maestria técnica insuperável. Apesar de ter caído no esquecimento após sua morte, foi redescoberto por Mendelssohn no século XIX e hoje é reconhecido como um dos maiores gênios da música ocidental. Sua influência se estende de Mozart e Beethoven até o jazz e a música contemporânea.$$, $$https://upload.wikimedia.org/wikipedia/commons/6/6a/Johann_Sebastian_Bach.jpg$$, 5, true, '2025-10-09 02:04:40.115836+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_composers (tenant_id, id, full_name, artistic_name, period_id, birth_country, birth_date, death_date, biography, photo_url, importance_level, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '9148c439-1fbe-45d0-beed-56e97f6cf026', $$Wolfgang Amadeus Mozart$$, $$W.A. Mozart$$, 'f8ed8ab3-ef44-47e5-8a3f-80b4dd60f89a', $$Áustria$$, '1756-01-27'::date, '1791-12-05'::date, $$Wolfgang Amadeus Mozart nasceu em Salzburgo em 1756. Prodígio musical incomparável, compunha desde os 5 anos e aos 6 já excursionava pelas cortes europeias com sua irmã Nannerl. Seu pai Leopold, também compositor, educou-o rigorosamente. Mozart dominou todos os gêneros: 41 sinfonias, 27 concertos para piano, 23 óperas, música sacra, quartetos de cordas e sonatas. Sua capacidade de memorização era lendária - copiou de memória o Miserere de Allegri após uma única audição. Em 1781, rompeu com o Arcebispo de Salzburgo e tornou-se músico freelancer em Viena, uma decisão ousada para a época. Casou-se com Constanze Weber em 1782. Apesar do sucesso artístico, enfrentou dificuldades financeiras e morreu prematuramente aos 35 anos, deixando o Réquiem inacabado. Sua música une perfeição formal com profunda expressividade emocional.$$, $$https://upload.wikimedia.org/wikipedia/commons/1/1e/Wolfgang-amadeus-mozart_1.jpg$$, 5, true, '2025-10-09 02:04:40.115836+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_composers (tenant_id, id, full_name, artistic_name, period_id, birth_country, birth_date, death_date, biography, photo_url, importance_level, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '9beb6a1a-96e6-4434-9e29-dad1417dade2', $$Rentarō Taki$$, $$Taki$$, '17bf83a0-e91e-4983-915f-51ace4da29ea', $$Japão$$, '1879-11-24'::date, '1903-06-29'::date, $$Rentarō Taki foi pioneiro na fusão da música ocidental com a sensibilidade japonesa. Estudou no Conservatório de Música de Tóquio, onde aprendeu piano e composição ocidental. Suas composições, especialmente "Kōjō no Tsuki" (Lua sobre Castelo em Ruínas), tornaram-se parte do coração cultural japonês. Morreu tragicamente aos 23 anos de tuberculose, mas suas poucas obras criaram um modelo para gerações de compositores japoneses que buscavam unir duas tradições musicais.$$, NULL, 4, true, '2025-12-14 20:49:33.510717+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_composers (tenant_id, id, full_name, artistic_name, period_id, birth_country, birth_date, death_date, biography, photo_url, importance_level, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', 'a3707aa4-7707-43de-bcd1-493e38f77dc6', $$Tōru Takemitsu$$, $$Takemitsu$$, 'cb79f2bb-813a-485c-a6c8-2000fced9334', $$Japão$$, '1930-10-08'::date, '1996-02-20'::date, $$Tōru Takemitsu é considerado o maior compositor japonês do século XX. Autodidata, foi profundamente influenciado por Debussy e pela música concreta francesa, mas sempre manteve conexão profunda com a estética japonesa do ma (間 - espaço/silêncio). Suas obras como "November Steps" combinam orquestra ocidental com instrumentos tradicionais como biwa e shakuhachi. Compôs mais de 90 trilhas sonoras para cinema, incluindo filmes de Akira Kurosawa. Suas composições são tocadas pelas principais orquestras mundiais.$$, NULL, 5, true, '2025-12-14 20:49:33.510717+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_composers (tenant_id, id, full_name, artistic_name, period_id, birth_country, birth_date, death_date, biography, photo_url, importance_level, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', 'aa7603a5-6982-4a13-b7ae-002e2f0ce8e3', $$Caetano Emanuel Viana Teles Veloso$$, $$Caetano Veloso$$, '480e5257-9aca-48e8-971f-f19794fc0dcf', $$Brasil$$, '1942-08-07'::date, NULL, $$Caetano Veloso é um dos artistas mais importantes da cultura brasileira. Nascido em Santo Amaro da Purificação, Bahia, foi líder do movimento Tropicália (1967-68), que revolucionou a música brasileira ao incorporar rock, guitarras elétricas, poesia concreta e antropofagia oswaldiana. "Alegria, Alegria" e "Tropicália" chocaram e renovaram a MPB. Preso e exilado pela ditadura militar (1969-72), viveu em Londres. Sua obra é marcada pela experimentação constante e reflexão sobre identidade brasileira. Além de músico, é ensaísta e pensador cultural. Influenciou gerações de artistas e continua produzindo aos 80 anos.$$, NULL, 5, true, '2025-12-14 20:49:33.510717+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_composers (tenant_id, id, full_name, artistic_name, period_id, birth_country, birth_date, death_date, biography, photo_url, importance_level, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', 'b42d30f0-d927-4ead-aee2-38b4800e79fc', $$Marcus Vinícius da Cruz e Mello Moraes$$, $$Vinicius de Moraes$$, '798ce272-a0af-40a3-97c5-11b83fe0addb', $$Brasil$$, '1913-10-19'::date, '1980-07-09'::date, $$Vinicius de Moraes (1913-1980), O Poetinha, foi poeta, dramaturgo, diplomata e letrista brasileiro. Formou-se em Direito, entrou no Itamaraty (diplomacia), serviu em Los Angeles, Paris, Montevidéu. Paralelamente, carreira literária: 9 livros de poesia, peças teatrais (Orfeu da Conceição, 1956, com Tom Jobim). Em 1958, com Jobim e João Gilberto, criou a Bossa Nova: fusão de samba, jazz, poesia. Parcerias principais: Tom Jobim (Garota de Ipanema, Chega de Saudade, Insensatez, Águas de Março), Baden Powell (Afro-sambas: Berimbau, Canto de Ossanha), Toquinho (Aquarela, Regra Três), Carlos Lyra. Letras poéticas sobre amor (especialmente feminino: Garota, Chega de Saudade, Se Todos Fossem Iguais a Você), natureza, Rio, existência. Foi casado 9 vezes (Eu sou um chato com as mulheres). Deixou diplomacia (1969) para dedicar-se à música. Shows com Toquinho (1970s) foram fenômeno. Morreu de edema pulmonar aos 66 anos. Legado: elevou letra de música popular a poesia sofisticada.$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Vinicius_de_Moraes_1970.jpg/800px-Vinicius_de_Moraes_1970.jpg$$, 4, true, '2025-10-09 02:50:34.631005+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_composers (tenant_id, id, full_name, artistic_name, period_id, birth_country, birth_date, death_date, biography, photo_url, importance_level, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', 'b75a281f-371d-418b-9b84-4095631e2524', $$Sergei Vasilyevich Rachmaninoff$$, $$Rachmaninoff$$, 'e8ce8fcc-5d20-4557-be06-c908b975e141', $$Rússia$$, '1873-04-01'::date, '1943-03-28'::date, $$Sergei Rachmaninoff (1873-1943) foi o último grande compositor romântico e um dos maiores pianistas da história. Estudou no Conservatório de Moscou, graduando-se com medalha de ouro. Primeira Sinfonia (1897) foi desastre (mal regida), causando depressão severa por 3 anos. Recuperou-se com hipnoterapia, compondo Concerto para Piano nº 2 (1901), sua obra mais popular. Tinha mãos enormes (podia alcançar 13 teclas, uma terça décima), permitindo acordes impossíveis. Após Revolução Russa (1917), exilou-se permanentemente, estabelecendo-se nos EUA (1918). Viveu de concertos como pianista virtuose. Principais obras: 4 concertos para piano (nº 2 e nº 3 supremos), Rapsódia sobre um Tema de Paganini (24 variações), 3 sinfonias, Vésperas (música sacra ortodoxa), Prelúdios. Estilo: melancolia russa, melodias extensas, harmonias ricas, virtuosismo pianístico extremo. Gravou extensivamente (78 RPM). Morreu de câncer aos 69 anos na Califórnia. Legado: ponte entre romantismo do século XIX e século XX.$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Sergei_Rachmaninoff_cph.3a40575.jpg/800px-Sergei_Rachmaninoff_cph.3a40575.jpg$$, 4, true, '2025-10-09 02:50:34.631005+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_composers (tenant_id, id, full_name, artistic_name, period_id, birth_country, birth_date, death_date, biography, photo_url, importance_level, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', 'bb281b5c-b3c7-4494-aecb-c328ab88defe', $$Johannes Brahms$$, NULL, 'e8ce8fcc-5d20-4557-be06-c908b975e141', $$Alemanha$$, '1833-05-07'::date, '1897-04-03'::date, $$Johannes Brahms (1833-1897) representa a síntese perfeita entre forma clássica e expressão romântica. Nasceu em Hamburgo, filho de músico pobre. Aos 20 anos conheceu Robert Schumann, que proclamou Brahms como sucessor de Beethoven no artigo "Novas Vias" (1853). Após suicídio frustrado de Schumann (1854), Brahms apoiou Clara Schumann, desenvolvendo amor platônico eterno. Estabeleceu-se em Viena (1862), cidade de Beethoven. Compôs 4 sinfonias monumentais (1ª estreou quando tinha 43 anos, após 20 anos de trabalho), 2 concertos para piano, concerto para violino, Concerto Duplo, Requiem Alemão (1868, em vernáculo ao invés de latim), música de câmara suprema (quintetos, sextetos), variações pianísticas (sobre tema de Paganini, de Handel), mais de 200 lieder. Era perfeccionista extremo, destruindo muitas obras. Conservador na forma (manteve tonalidade, formas clássicas) mas inovador na elaboração temática e desenvolvimento motívico. Amizade com Clara Schumann durou 40 anos (nunca se casaram). Rivalidade musical com Wagner: Brahms representava tradição clássica "absoluta", Wagner a ópera e o "futuro". Apoiado por crítico Eduard Hanslick. Tinha barba característica. Morreu de câncer de fígado aos 63 anos. É o B do "três Bs" alemães (Bach, Beethoven, Brahms).$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Johannes_Brahms_1889.jpg/800px-Johannes_Brahms_1889.jpg$$, 5, true, '2025-10-09 02:15:02.70535+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_composers (tenant_id, id, full_name, artistic_name, period_id, birth_country, birth_date, death_date, biography, photo_url, importance_level, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', 'bb314e0e-90fb-409e-a57a-b190e71fce7c', $$Antonio Lucio Vivaldi$$, $$Vivaldi$$, 'd8c30e03-788e-4a90-970c-7585963b3949', $$Itália$$, '1678-03-04'::date, '1741-07-28'::date, $$Antonio Vivaldi foi um compositor e virtuoso violinista italiano do período Barroco. Nasceu em Veneza em 1678. Ordenado sacerdote católico, ficou conhecido como "Il Prete Rosso" devido aos seus cabelos ruivos. Trabalhou como professor de violino no Ospedale della Pietà, um orfanato para meninas. Compôs mais de 500 concertos, sendo As Quatro Estações sua obra mais famosa. Revolucionou o concerto barroco, estabelecendo a forma de três movimentos (rápido-lento-rápido). Sua música influenciou profundamente Bach, que transcreveu vários de seus concertos.$$, NULL, 5, true, '2025-12-15 02:37:56.378902+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_composers (tenant_id, id, full_name, artistic_name, period_id, birth_country, birth_date, death_date, biography, photo_url, importance_level, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', 'c8821384-584a-4915-9655-1c710406201c', $$Gustav Mahler$$, NULL, 'e8ce8fcc-5d20-4557-be06-c908b975e141', $$Império Austro-Húngaro (atual Tchéquia)$$, '1860-07-07'::date, '1911-05-18'::date, $$Gustav Mahler (1860-1911) foi o último grande sinfonista do romantismo e um dos maiores maestros de todos os tempos. Judeu nascido na Boêmia (Império Austro-Húngaro), estudou no Conservatório de Viena. Maestro da Ópera de Viena (1897-1907), depois em Nova York. Revolucionou regência com ensaios meticulosos. Como compositor, dedicou-se a sinfonias (9 completas + 10ª inacabada) e Lieder com orquestra (Das Lied von der Erde). Estilo: expansão extrema da tonalidade, longas melodias, contraponto complexo, citações e marchas. Vida pessoal trágica: perda da filha, casamento turbulento com Alma. Morte prematura aos 50 por endocardite. Redescoberto no século XX por Bernstein; hoje é onipresente nas salas de concerto.$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Gustav_Mahler_1909.jpg/800px-Gustav_Mahler_1909.jpg$$, 5, true, '2025-10-09 02:22:14.349741+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_composers (tenant_id, id, full_name, artistic_name, period_id, birth_country, birth_date, death_date, biography, photo_url, importance_level, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', 'd2489059-8725-4e79-a729-8b14002578c0', $$Dmitri Dmitriyevich Shostakovich$$, $$Shostakovich$$, 'a8106bcd-4791-46f4-b502-bda5fe19c041', $$Rússia/URSS$$, '1906-09-25'::date, '1975-08-09'::date, $$Dmitri Shostakovich (1906-1975) foi o maior compositor soviético, vivendo sob tirania stalinista. Prodígio, graduou-se no Conservatório de Leningrado aos 19 anos com Sinfonia nº 1 (1925). Sucesso inicial com ópera Lady Macbeth do Distrito de Mtsensk (1934). Mas Stalin assistiu, ofendeu-se, e Pravda publicou artigo Caos ao Invés de Música (1936), denunciando Shostakovich. Passou a viver em terror constante de ser preso e executado (Grande Expurgo 1936-1938). Dormia vestido na escada, para não acordar família se polícia secreta viesse. Compôs 15 sinfonias, 15 quartetos de cordas, concertos, óperas, trilhas para cinema. Obras principais: Sinfonia nº 5 (1937, resposta a críticas, ambiguamente conformista), Sinfonia nº 7 Leningrado (1941, durante cerco nazista), Sinfonia nº 10 (1953, após morte de Stalin, retrato musical do tirano?), Quarteto nº 8 (autobiográfico, assinatura DSCH). Estilo: sarcasmo, ironia, grotesco, marches fúnebres, citações, ambiguidade (criticava regime codificadamente). Forçado a aderir ao Partido (1960), viveu atormentado. Morreu de câncer aos 68 anos. Testamento (livro) publicado no Ocidente é controverso (autenticidade disputada).$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Shostakovich_signature.svg/800px-Shostakovich_signature.svg.png$$, 4, true, '2025-10-09 02:50:34.631005+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_composers (tenant_id, id, full_name, artistic_name, period_id, birth_country, birth_date, death_date, biography, photo_url, importance_level, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', 'd5bdcd5d-27f2-4133-a511-097e3e0ea709', $$Franz Liszt$$, NULL, 'e8ce8fcc-5d20-4557-be06-c908b975e141', $$Hungria$$, '1811-10-22'::date, '1886-07-31'::date, $$Franz Liszt (1811-1886) foi o maior virtuose do piano da história e figura central do romantismo. Criança prodígio húngara, estudou com Czerny (aluno de Beethoven) e Salieri em Viena. Aos 11 tocou para Beethoven. Carreira de pianista virtuose em Paris (1827-1847): mulheres desmaiavam em concertos (Lisztomania). Inventou o recital solo moderno. Técnica transcendental: oitavas, saltos, glissandi, tremolo. Escreveu música pianística de dificuldade inédita (Estudos Transcendentais, Paganini Etudes, Mazeppa). Relacionamento com Condessa Marie d'Agoult (3 filhos, incluindo Cosima que casou com Wagner) e depois com Princesa Carolyne zu Sayn-Wittgenstein. Em Weimar, promoveu música nova (Wagner, Berlioz), compôs poemas sinfônicos (inventou o termo e o gênero), 2 concertos para piano, Sonata em Si menor. Fase final: tornou-se Abade, viveu entre Roma, Weimar, Budapeste; deu aulas gratuitas. Obras tardias antecipam impressionismo e atonalidade (Bagatela sem Tonalidade, 1885). Morreu aos 74 anos em Bayreuth.$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Franz_Liszt_1858.jpg/800px-Franz_Liszt_1858.jpg$$, 5, true, '2025-10-09 02:22:14.349741+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_composers (tenant_id, id, full_name, artistic_name, period_id, birth_country, birth_date, death_date, biography, photo_url, importance_level, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', 'e23ae30f-1410-4610-b30f-8f12fc8e8bdd', $$Yoko Kanno$$, $$Kanno$$, 'bf731274-4647-4e61-aa72-2ac8a0b3944c', $$Japão$$, '1963-03-18'::date, NULL, $$Yoko Kanno é uma das compositoras mais versáteis e respeitadas da música japonesa. Conhecida principalmente por suas trilhas sonoras de anime, domina praticamente todos os gêneros musicais: jazz fusion, rock, eletrônica, música clássica, folk, e muito mais. "Tank!", tema de abertura de Cowboy Bebop, é considerada uma das melhores músicas de anime de todos os tempos. Trabalha frequentemente com a banda The Seatbelts e já compôs para jogos, filmes live-action e comerciais. Sua habilidade de capturar a essência emocional de uma narrativa através da música é lendária.$$, NULL, 5, true, '2025-12-14 20:49:33.510717+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_composers (tenant_id, id, full_name, artistic_name, period_id, birth_country, birth_date, death_date, biography, photo_url, importance_level, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', 'efa0d7ad-57ee-4d53-b74f-4aae46be0634', $$Pyotr Ilyich Tchaikovsky$$, $$Tchaikovsky$$, 'e8ce8fcc-5d20-4557-be06-c908b975e141', $$Rússia$$, '1840-05-07'::date, '1893-11-06'::date, $$Pyotr Ilyich Tchaikovsky (1840-1893) é o compositor russo mais popular mundialmente. Inicialmente estudou direito, só aos 21 anos dedicou-se à música profissionalmente no recém-fundado Conservatório de São Petersburgo (Anton Rubinstein). Tornou-se professor no Conservatório de Moscou (1866). Sua música combina melodias intensamente líricas, orquestração brilhante e emocionalidade romântica extrema com maestria formal. Embora russo, não integrava o nacionalista Grupo dos Cinco (Balakirev, Mussorgsky, Rimsky-Korsakov, Borodin, Cui), sendo mais cosmopolita e ocidentalizado. Obras principais: 3 balés supremos (O Lago dos Cisnes 1876, A Bela Adormecida 1889, O Quebra-Nozes 1892 - os mais executados do mundo), 6 sinfonias (especialmente nº 6 Pathétique 1893), Concerto para Piano nº 1 (1875, um dos mais populares), Concerto para Violino (1878), óperas (Eugene Onegin 1879, A Dama de Espadas 1890), Abertura 1812 (com canhões!), Romeu e Julieta. Vida pessoal torturada: homossexualidade reprimida, casamento desastroso (1877, durou semanas), tentativa de suicídio. Mecenato de Nadezhda von Meck (14 anos de correspondência, nunca se encontraram pessoalmente). Morreu aos 53 anos, oficialmente de cólera (bebeu água não-fervida), mas teorias sugerem suicídio. Suas sinfonias e balés são pilares do repertório orquestral mundial.$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Tchaikovsky_by_Reutlinger.jpg/800px-Tchaikovsky_by_Reutlinger.jpg$$, 5, true, '2025-10-09 02:15:02.70535+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_composers (tenant_id, id, full_name, artistic_name, period_id, birth_country, birth_date, death_date, biography, photo_url, importance_level, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', 'faa61f81-2bdb-4a04-96fb-2fbbb259babf', $$Wilhelm Richard Wagner$$, $$Wagner$$, 'e8ce8fcc-5d20-4557-be06-c908b975e141', $$Alemanha$$, '1813-05-22'::date, '1883-02-13'::date, $$Richard Wagner (1813-1883) é a figura mais revolucionária e controversa da ópera. Desenvolveu o conceito de Gesamtkunstwerk (obra de arte total): fusão de música, drama, poesia, cenografia, filosofia. Criou o leitmotiv: motivos musicais recorrentes associados a personagens, objetos, ideias. Sua harmonia cromática extrema (especialmente no Tristão e Isolda, 1865, com o famoso "acorde de Tristão") suspende a tonalidade e pavimenta caminho para atonalidade do século XX. Obras principais são óperas monumentais: Der Ring des Nibelungen (O Anel do Nibelungo, 1876: tetralogia de 4 óperas, 15 horas totais), Tristan und Isolde, Die Meistersinger von Nürnberg, Parsifal. Construiu Festspielhaus em Bayreuth (1876), teatro especialmente desenhado para suas óperas (orquestra invisível, acústica perfeita). Vida pessoal escandalosa: múltiplos casamentos/amantes, incluindo Cosima (filha de Liszt, casada com maestro Hans von Bülow), dívidas enormes, exílios políticos, mecenato do Rei Ludwig II da Baviera (louco por Wagner). Escreveu seus próprios libretos. Antissemitismo virulento em ensaios (Das Judentum in der Musik) manchou legado; nazistas apropriaram-se de sua música. Apesar de controvérsias, revolucionou ópera e influenciou profundamente música, filosofia (Nietzsche foi amigo depois inimigo), literatura, cinema (John Williams usa técnicas wagnerianas em Star Wars).$$, $$https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/RichardWagner.jpg/800px-RichardWagner.jpg$$, 5, true, '2025-10-09 02:15:02.70535+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

COMMIT;