-- =============================================
-- Migration: 023_history_genres.sql
-- Table: core.history_genres
-- Source CSV: historia_generos_rows.csv
-- Generated: 2026-02-28T16:15:03.681Z
-- Rows: 32
-- =============================================

BEGIN;

INSERT INTO core.history_genres (tenant_id, id, name, slug, origin_period_id, origin_decade, origin_country, description, musical_characteristics, related_genres, main_composers, representative_works, cultural_influences, image_url, theme_color, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '00931bfa-fe78-45f6-985d-85dd690f7e5c', $$Enka$$, $$enka$$, 'cb79f2bb-813a-485c-a6c8-2000fced9334', NULL, NULL, $$Estilo de balada melancólica japonesa. Letras sobre amor perdido, saudade e nostalgia. Popular entre gerações mais velhas.$$, $${"temas": "Saudade, amor, perda", "vocal": "Vibratos e inflexões tradicionais", "estrutura": "Balada", "instrumentos": ["shamisen", "piano", "orquestra"]}$$, '[]', '[]', '[]', NULL, NULL, NULL, true, '2025-12-14 20:49:33.510717+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_genres (tenant_id, id, name, slug, origin_period_id, origin_decade, origin_country, description, musical_characteristics, related_genres, main_composers, representative_works, cultural_influences, image_url, theme_color, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '11f5c353-c327-4dd0-b90b-f753d56eb600', $$Gagaku$$, $$gagaku$$, '36ea1a6e-5615-48dc-9c2f-c8cc87d2dfd4', NULL, NULL, $$Música clássica da corte imperial japonesa. Uma das formas de música orquestral mais antigas do mundo ainda praticadas. Solene e ritualística.$$, $${"ritmo": "Lento e majestoso", "escalas": "Modi japoneses", "estrutura": "Ensemble orquestral", "instrumentos": ["hichiriki", "ryuteki", "biwa", "koto"]}$$, '[]', '[]', '[]', NULL, NULL, NULL, true, '2025-12-14 20:49:33.510717+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_genres (tenant_id, id, name, slug, origin_period_id, origin_decade, origin_country, description, musical_characteristics, related_genres, main_composers, representative_works, cultural_influences, image_url, theme_color, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '21d4204e-4785-435a-8b06-19cb7761373b', $$Reggae$$, $$reggae$$, NULL, $$1968$$, $$Jamaica$$, $$Voz da Jamaica para o mundo. Ritmo sincopado, mensagem de paz, amor e resistência. Movimento Rastafári e consciência social.$$, $${"obras": ["No Woman No Cry - Bob Marley", "Redemption Song - Marley", "The Harder They Come - Jimmy Cliff"], "temas": ["Rastafári", "Justiça social", "Paz", "Amor", "Resistência", "Repatriação", "Crítica ao sistema (Babylon)"], "estilos": ["Roots Reggae", "Dub", "Dancehall", "Lovers Rock", "Reggae Fusion"], "artistas": ["Bob Marley", "Peter Tosh", "Burning Spear", "Jimmy Cliff", "Toots and the Maytals", "Lee \"Scratch\" Perry", "King Tubby"], "estrutura": ["Ênfase no contratempo (offbeat)", "Baixo proeminente e melódico", "Skank característico (guitarra)", "Tempo médio/lento", "One drop (bateria)"]}$$, '[]', '[]', '[]', $$Jamaica, final anos 60. Evolução do ska/rocksteady. Movimento Rastafári. Bob Marley levou ao mundo. UNESCO: Patrimônio Imaterial.$$, NULL, $$#16a34a$$, true, '2025-10-27 18:41:40.135539+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_genres (tenant_id, id, name, slug, origin_period_id, origin_decade, origin_country, description, musical_characteristics, related_genres, main_composers, representative_works, cultural_influences, image_url, theme_color, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '23588b5b-865c-4f2a-9bdc-31aaed701a57', $$Bossa Nova$$, $$bossa-nova$$, NULL, $$1958$$, $$Brasil$$, $$Sofisticação brasileira que conquistou o mundo. Fusão de samba com jazz cool. "Batida diferente" que revolucionou a MPB.$$, $${"obras": ["Garota de Ipanema", "Chega de Saudade", "Desafinado", "Corcovado", "Águas de Março", "Wave"], "estilos": ["Bossa Nova Clássica", "Samba-jazz", "MPB (evolução)"], "artistas": ["Tom Jobim", "João Gilberto", "Vinicius de Moraes", "Stan Getz", "Elis Regina", "Nara Leão", "Astrud Gilberto", "Baden Powell"], "estrutura": ["Batida sincopada no violão", "Harmonia sofisticada (jazz)", "Melodia suave e intimista", "Ritmo de samba \"quebrado\"", "Influência do cool jazz"], "instrumentos": ["Violão (batida característica)", "Piano", "Baixo", "Bateria leve", "Flauta", "Voz suave"]}$$, '[]', '[]', '[]', $$Rio de Janeiro, final anos 50. Zona Sul carioca, intelectuais, classe média. Fusão samba + jazz. Sucesso internacional (Getz/Gilberto 1964).$$, NULL, $$#06b6d4$$, true, '2025-10-27 18:41:40.135539+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_genres (tenant_id, id, name, slug, origin_period_id, origin_decade, origin_country, description, musical_characteristics, related_genres, main_composers, representative_works, cultural_influences, image_url, theme_color, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '33fdd046-f688-4b0d-9a8c-9485e86b3348', $$MPB$$, $$mpb$$, NULL, $$1965$$, $$Brasil$$, $$Termo guarda-chuva para música brasileira de qualidade pós-Bossa Nova. Fusão de tradições brasileiras com influências internacionais.$$, $${"obras": ["Construção - Chico", "Águas de Março - Tom", "Alegria Alegria - Caetano", "Cálice - Chico/Gil"], "artistas": ["Chico Buarque", "Caetano Veloso", "Gilberto Gil", "Elis Regina", "Milton Nascimento", "Gal Costa", "Maria Bethânia", "Djavan"], "estrutura": ["Diversidade estilística", "Letra poética/literária", "Harmonia sofisticada", "Fusão de gêneros", "Experimentação"], "movimentos": ["Tropicália (1968)", "Clube da Esquina", "Vanguarda Paulista", "Música de Resistência (Ditadura)"], "influencias": ["Bossa Nova", "Samba", "Rock", "Jazz", "Música Nordestina", "Música Erudita"]}$$, '[]', '[]', '[]', $$Anos 60-70. Resposta à ditadura militar, Festivais da Canção TV Record. Sofisticação + engajamento político. Identidade brasileira moderna.$$, NULL, $$#8b5cf6$$, true, '2025-10-27 18:41:40.135539+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_genres (tenant_id, id, name, slug, origin_period_id, origin_decade, origin_country, description, musical_characteristics, related_genres, main_composers, representative_works, cultural_influences, image_url, theme_color, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '395cfb8c-2660-4827-8467-e4e8acdd625e', $$Tropicália$$, $$tropicalia$$, '480e5257-9aca-48e8-971f-f19794fc0dcf', NULL, NULL, $$Movimento de vanguarda que revolucionou a MPB. Mistura antropofágica de rock, samba, baião, música regional e experimentação. Letras poéticas e crítica social.$$, $${"estrutura": "Experimental", "instrumentos": ["guitarra elétrica", "berimbau", "instrumentos regionais", "eletrônica"], "caracteristicas": "Antropofagia cultural, fusão radical, engajamento político"}$$, '[]', '[]', '[]', NULL, NULL, NULL, true, '2025-12-14 20:49:33.510717+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_genres (tenant_id, id, name, slug, origin_period_id, origin_decade, origin_country, description, musical_characteristics, related_genres, main_composers, representative_works, cultural_influences, image_url, theme_color, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '3a16c10a-e2e3-4b98-89f3-37b7930928ce', $$Balada$$, $$balada$$, 'e8ce8fcc-5d20-4557-be06-c908b975e141', NULL, NULL, $$Forma musical instrumental de caráter narrativo e dramático, muitas vezes inspirada em poesia ou lendas.$$, $${"forma": "Livre", "mestre": "Chopin (para piano)", "carater": "Narrativo, dramático", "inspiracao": "Poesia, lendas"}$$, '[]', '[]', '[]', NULL, NULL, $$#a855f7$$, true, '2025-10-26 03:54:07.846053+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_genres (tenant_id, id, name, slug, origin_period_id, origin_decade, origin_country, description, musical_characteristics, related_genres, main_composers, representative_works, cultural_influences, image_url, theme_color, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '3f255cc4-dc35-4d6b-8507-07fb5d8c2da7', $$Hip-Hop$$, $$hip-hop$$, NULL, $$1973$$, $$Estados Unidos$$, $$Cultura urbana completa: rap, DJing, breakdance, graffiti. Voz das periferias, poesia urbana, denúncia social e celebração de identidade.$$, $${"obras": ["The Message - Grandmaster Flash", "Fight the Power - Public Enemy", "Alright - Kendrick Lamar"], "temas": ["Realidade das periferias", "Racismo e injustiça", "Superação", "Ostentação", "Política", "Identidade negra"], "estilos": ["Old School", "Golden Age", "Gangsta Rap", "Conscious Rap", "Trap", "Boom Bap", "Alternative Hip-Hop"], "artistas": ["Grandmaster Flash", "Run-DMC", "Public Enemy", "Tupac", "Notorious B.I.G.", "Nas", "Kendrick Lamar", "J. Cole"], "elementos": ["MCing/Rap", "DJing", "Breakdance", "Graffiti", "Beatboxing", "Knowledge (consciência)"], "estrutura": ["Rap (ritmo e poesia)", "Beat (base instrumental)", "Sampling (uso de trechos de outras músicas)", "Scratch (DJ)", "Flow (cadência do rap)"]}$$, '[]', '[]', '[]', $$Bronx, Nova York, anos 70. DJ Kool Herc, Afrika Bambaataa. Cultura de resistência afro-latina. Globalizou-se: maior gênero mundial hoje.$$, NULL, $$#7c3aed$$, true, '2025-10-27 18:41:40.135539+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_genres (tenant_id, id, name, slug, origin_period_id, origin_decade, origin_country, description, musical_characteristics, related_genres, main_composers, representative_works, cultural_influences, image_url, theme_color, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '45c82306-d206-465c-9ed1-bf3a4ea8a5be', $$Afrobeat$$, $$afrobeat$$, NULL, $$1970$$, $$Nigéria$$, $$Fusão explosiva de funk, jazz, highlife e ritmos yorubá. Criado por Fela Kuti na Nigéria. Música como arma política e celebração africana.$$, $${"obras": ["Zombie - Fela Kuti", "Water No Get Enemy - Fela", "Expensive Shit - Fela"], "temas": ["Crítica ao colonialismo", "Corrupção governamental", "Pan-africanismo", "Orgulho negro", "Resistência"], "artistas": ["Fela Kuti", "Tony Allen", "Antibalas", "Seun Kuti", "Femi Kuti", "Ebo Taylor", "Orchestra Baobab"], "estrutura": ["Groove hipnótico e repetitivo", "Seção de metais poderosa (jazz)", "Polirritmia complexa (percussão africana)", "Músicas longas (10-20 min)", "Call-response"], "influencias": ["Highlife (Gana/Nigéria)", "Funk (James Brown)", "Jazz", "Música Yorubá", "Política Pan-Africana"], "instrumentos": ["Saxofones", "Trompetes", "Guitarra", "Baixo", "Bateria", "Congas", "Shekere", "Teclados"]}$$, '[]', '[]', '[]', $$Lagos, Nigéria, anos 70. Fela Kuti cria fusão única. Ativismo político contra ditadura militar. Shrine (clube). Influência global moderna.$$, NULL, $$#ea580c$$, true, '2025-10-27 18:41:40.135539+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_genres (tenant_id, id, name, slug, origin_period_id, origin_decade, origin_country, description, musical_characteristics, related_genres, main_composers, representative_works, cultural_influences, image_url, theme_color, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '47442ac7-2734-436d-a5a8-9d386928c18e', $$Música Eletrônica$$, $$eletronica$$, NULL, $$1970$$, $$Alemanha/EUA$$, $$Revolução tecnológica na música. De experimentos acadêmicos a cultura de club global. Sintetizadores, samplers e computadores como instrumentos.$$, $${"cenas": ["Chicago House (anos 80)", "Detroit Techno", "UK Rave", "Ibiza", "Berlin Techno", "EDM (festivais)"], "obras": ["Blue Monday - New Order", "Around the World - Daft Punk", "Windowlicker - Aphex Twin"], "estilos": ["House", "Techno", "Trance", "Drum and Bass", "Dubstep", "EDM", "Ambient", "IDM", "Breakbeat"], "estrutura": ["Produção totalmente eletrônica", "Batida repetitiva (4/4)", "Build-up e drop", "Síntese sonora", "Loops e camadas"], "pioneiros": ["Kraftwerk", "Jean-Michel Jarre", "Giorgio Moroder", "Detroit Techno: Derrick May/Juan Atkins", "Daft Punk", "Aphex Twin"], "tecnologia": ["Sintetizadores", "Drum machines (TR-808, 909)", "Samplers", "DAWs (Ableton, FL Studio)", "Controllers"]}$$, '[]', '[]', '[]', $$Anos 70-80. Kraftwerk (Alemanha), Chicago House, Detroit Techno. Cultura club/rave. Democratizou produção musical (laptops).$$, NULL, $$#ec4899$$, true, '2025-10-27 18:41:40.135539+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_genres (tenant_id, id, name, slug, origin_period_id, origin_decade, origin_country, description, musical_characteristics, related_genres, main_composers, representative_works, cultural_influences, image_url, theme_color, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '49daf28e-7b8f-49bb-a5f5-fd2a107e5b5e', $$Poema Sinfônico$$, $$poema-sinfonico$$, 'e8ce8fcc-5d20-4557-be06-c908b975e141', NULL, NULL, $$Obra orquestral de um único movimento que ilustra ou evoca conteúdo extramusical como narrativa, paisagem ou ideia.$$, $${"inovador": "Franz Liszt", "natureza": "Música programática", "inspiracao": "Literatura, poesia, natureza", "movimentos": "Um único movimento"}$$, '[]', '[]', '[]', NULL, NULL, $$#f97316$$, true, '2025-10-26 03:54:07.846053+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_genres (tenant_id, id, name, slug, origin_period_id, origin_decade, origin_country, description, musical_characteristics, related_genres, main_composers, representative_works, cultural_influences, image_url, theme_color, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '4cc882da-037f-4306-8b42-971bf32c6c2f', $$Prelúdio$$, $$preludio$$, 'd8c30e03-788e-4a90-970c-7585963b3949', NULL, NULL, $$Peça instrumental breve que originalmente servia como introdução a outra obra, mas que se desenvolveu como forma independente.$$, $${"forma": "Livre", "carater": "Improvisatório", "duracao": "2-5 minutos", "natureza": "Introdutória ou independente"}$$, '[]', '[]', '[]', NULL, NULL, $$#10b981$$, true, '2025-10-26 03:54:07.846053+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_genres (tenant_id, id, name, slug, origin_period_id, origin_decade, origin_country, description, musical_characteristics, related_genres, main_composers, representative_works, cultural_influences, image_url, theme_color, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '5c4d2954-3812-448a-8ca4-169f292cd37b', $$J-Pop$$, $$j-pop$$, 'bf731274-4647-4e61-aa72-2ac8a0b3944c', NULL, NULL, $$Pop japonês mainstream. Produção sofisticada, melodias cativantes, influências de rock, eletrônica e R&B. Fenômeno cultural global.$$, $${"producao": "Alta qualidade", "estrutura": "Pop comercial", "instrumentos": ["sintetizadores", "guitarra", "bateria", "programação"], "caracteristicas": "Melodias complexas, mudanças de tonalidade"}$$, '[]', '[]', '[]', NULL, NULL, NULL, true, '2025-12-14 20:49:33.510717+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_genres (tenant_id, id, name, slug, origin_period_id, origin_decade, origin_country, description, musical_characteristics, related_genres, main_composers, representative_works, cultural_influences, image_url, theme_color, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '6b8ae50f-c464-4f1f-93a7-5604ad77382d', $$Cantata$$, $$cantata$$, NULL, $$1650$$, $$Alemanha/Itália$$, $$Obra vocal média para solistas, coro e instrumentos. Sacra ou profana.$$, $${"obras": ["Cantata BWV 147 - Bach", "Cantata do Café - Bach", "Cantatas Sacras - Bach"], "estrutura": ["Vocal + instrumental", "Recitativos/árias/coros", "Mais curta que ópera", "Sacra ou profana", "Tradição luterana"], "compositores": ["Bach", "Telemann", "Scarlatti", "Buxtehude"]}$$, '[]', '[]', '[]', $$Início Barroco. Bach: 200+ cantatas sacras para liturgia luterana.$$, NULL, $$#a855f7$$, true, '2025-10-27 18:42:59.423794+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_genres (tenant_id, id, name, slug, origin_period_id, origin_decade, origin_country, description, musical_characteristics, related_genres, main_composers, representative_works, cultural_influences, image_url, theme_color, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '7b099be1-9e04-4f36-8295-777fd9951d0d', $$Pop$$, $$pop$$, NULL, $$1950$$, $$Estados Unidos/Reino Unido$$, $$Música popular acessível e cativante. Melodias memoráveis, produção polida, apelo de massa. Reflete e molda cultura contemporânea.$$, $${"eras": ["Pop dos anos 50-60 (Elvis, Beatles)", "Disco (70s)", "Synth-pop (80s)", "Teen pop (90s-2000s)", "Pop contemporâneo"], "obras": ["Thriller - Michael Jackson", "Like a Prayer - Madonna", "I Wanna Dance with Somebody - Whitney"], "temas": ["Amor e relacionamentos", "Empoderamento", "Festa e celebração", "Superação", "Identidade"], "artistas": ["Michael Jackson", "Madonna", "Prince", "Whitney Houston", "Beyoncé", "Taylor Swift", "Ariana Grande", "The Weeknd"], "estrutura": ["Verso-refrão-verso-refrão-ponte-refrão", "Melodia cativante (hook)", "Duração 3-4 minutos", "Produção refinada", "Foco no refrão"], "caracteristicas": ["Apelo universal", "Produção de alta qualidade", "Videoclipes icônicos", "Performances espetaculares", "Fenômenos virais"]}$$, '[]', '[]', '[]', $$Anos 50-60 com rock and roll. Indústria fonográfica massiva. MTV (1981) revolucionou. Globalização via streaming. Maior alcance comercial.$$, NULL, $$#f472b6$$, true, '2025-10-27 18:41:40.135539+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_genres (tenant_id, id, name, slug, origin_period_id, origin_decade, origin_country, description, musical_characteristics, related_genres, main_composers, representative_works, cultural_influences, image_url, theme_color, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '7efd056c-ba65-4181-bea3-4fd0abe97c41', $$Choro$$, $$choro$$, 'b0bef9be-0afc-4319-a8fe-a117f44e2dc9', NULL, NULL, $$Primeiro gênero de música popular urbana do Brasil. Instrumental virtuoso com flauta, violão e cavaquinho. Contraponto melódico sofisticado.$$, $${"ritmo": "Sincopado", "estrutura": "Forma rondó (ABACA)", "instrumentos": ["flauta", "cavaquinho", "violão 7 cordas", "pandeiro"], "caracteristicas": "Improvisação, virtuosismo"}$$, '[]', '[]', '[]', NULL, NULL, NULL, true, '2025-12-14 20:49:33.510717+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_genres (tenant_id, id, name, slug, origin_period_id, origin_decade, origin_country, description, musical_characteristics, related_genres, main_composers, representative_works, cultural_influences, image_url, theme_color, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '809b5443-38a0-4afa-8a84-2c12721f4976', $$Suíte$$, $$suite$$, 'd8c30e03-788e-4a90-970c-7585963b3949', NULL, NULL, $$Coleção de movimentos de dança estilizados, organizados em uma sequência contrastante que forma uma obra completa.$$, $${"periodo": "Barroco principalmente", "estrutura": "Sequência de danças", "dancas_tipicas": "Allemande, Courante, Sarabande, Gigue", "instrumentacao": "Variável"}$$, '[]', '[]', '[]', NULL, NULL, $$#14b8a6$$, true, '2025-10-26 03:54:07.846053+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_genres (tenant_id, id, name, slug, origin_period_id, origin_decade, origin_country, description, musical_characteristics, related_genres, main_composers, representative_works, cultural_influences, image_url, theme_color, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '99cd3802-d802-46c5-85c5-457941734e64', $$Sinfonia Coral$$, $$sinfonia-coral$$, 'e8ce8fcc-5d20-4557-be06-c908b975e141', NULL, NULL, $$Sinfonia que inclui coro e às vezes solistas vocais, expandindo a forma sinfônica tradicional com elementos vocais.$$, $${"texto": "Geralmente poético ou literário", "escala": "Grande porte", "combinacao": "Orquestra + coro + solistas", "exemplo_icone": "Nona Sinfonia de Beethoven"}$$, '[]', '[]', '[]', NULL, NULL, $$#dc2626$$, true, '2025-10-26 03:54:07.846053+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_genres (tenant_id, id, name, slug, origin_period_id, origin_decade, origin_country, description, musical_characteristics, related_genres, main_composers, representative_works, cultural_influences, image_url, theme_color, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', 'ad3586ef-e52b-4e24-b07b-2516ae6a51d1', $$Oratório$$, $$oratorio$$, NULL, $$1650$$, $$Itália$$, $$Drama sacro para solistas, coro e orquestra, sem encenação.$$, $${"obras": ["Messias - Handel", "Paixão S. Mateus - Bach", "A Criação - Haydn"], "estrutura": ["Temática religiosa", "Solistas + coro + orquestra", "Sem encenação", "Narrador", "Recitativos/árias/coros"], "compositores": ["Handel", "Bach", "Haydn", "Mendelssohn"]}$$, '[]', '[]', '[]', $$Séc. XVII Itália, paralelo à ópera. Importante em países protestantes. Handel = ápice.$$, NULL, $$#6366f1$$, true, '2025-10-27 18:42:59.423794+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_genres (tenant_id, id, name, slug, origin_period_id, origin_decade, origin_country, description, musical_characteristics, related_genres, main_composers, representative_works, cultural_influences, image_url, theme_color, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', 'b6f9157c-c5e8-4bba-be8d-d6030197b1dc', $$Sinfonia$$, $$sinfonia$$, 'f8ed8ab3-ef44-47e5-8a3f-80b4dd60f89a', NULL, NULL, $$Composição orquestral em múltiplos movimentos, geralmente quatro, que representa uma das formas mais complexas e prestigiadas da música clássica.$$, $${"duracoes": "30-60 minutos", "estrutura": "4 movimentos típicos", "instrumentacao": "Orquestra completa", "forma_primeiro_movimento": "Forma sonata"}$$, '[]', '[]', '[]', NULL, NULL, $$#3b82f6$$, true, '2025-10-26 03:54:07.846053+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_genres (tenant_id, id, name, slug, origin_period_id, origin_decade, origin_country, description, musical_characteristics, related_genres, main_composers, representative_works, cultural_influences, image_url, theme_color, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', 'bb2b39dd-8833-44b2-9483-39820c16be28', $$Concerto$$, $$concerto$$, 'd8c30e03-788e-4a90-970c-7585963b3949', NULL, NULL, $$Obra musical para um ou mais instrumentos solistas acompanhados por orquestra, destacando o virtuosismo do solista em diálogo com a orquestra.$$, $${"forma": "Diálogo solista-orquestra", "cadenza": "Seção improvisatória do solista", "estrutura": "3 movimentos (rápido-lento-rápido)", "elemento_principal": "Virtuosismo do solista"}$$, '[]', '[]', '[]', NULL, NULL, $$#8b5cf6$$, true, '2025-10-26 03:54:07.846053+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_genres (tenant_id, id, name, slug, origin_period_id, origin_decade, origin_country, description, musical_characteristics, related_genres, main_composers, representative_works, cultural_influences, image_url, theme_color, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', 'be3bbc53-97b4-4e8c-86d1-2848cb5ea697', $$Ópera$$, $$opera$$, 'd8c30e03-788e-4a90-970c-7585963b3949', NULL, NULL, $$Forma dramática de teatro musical onde o texto (libreto) é cantado com acompanhamento orquestral, combinando música, drama, poesia e artes visuais.$$, $${"origem": "Florença, 1600", "partes": "Árias, recitativos, coros", "duracao": "2-5 horas", "elementos": "Canto, orquestra, teatro, cenografia"}$$, '[]', '[]', '[]', NULL, NULL, $$#ef4444$$, true, '2025-10-26 03:54:07.846053+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_genres (tenant_id, id, name, slug, origin_period_id, origin_decade, origin_country, description, musical_characteristics, related_genres, main_composers, representative_works, cultural_influences, image_url, theme_color, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', 'c38a0d21-401d-4837-9db4-2f24860bf147', $$Sonata$$, $$sonata$$, 'f8ed8ab3-ef44-47e5-8a3f-80b4dd60f89a', NULL, NULL, $$Composição instrumental, geralmente em 3 ou 4 movimentos, escrita para piano solo ou um instrumento melódico com acompanhamento de piano.$$, $${"estrutura": "3-4 movimentos", "intimidade": "Performance de câmara", "forma_sonata": "Primeiro movimento em forma sonata", "instrumentacao": "1-2 instrumentos"}$$, '[]', '[]', '[]', NULL, NULL, $$#ec4899$$, true, '2025-10-26 03:54:07.846053+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_genres (tenant_id, id, name, slug, origin_period_id, origin_decade, origin_country, description, musical_characteristics, related_genres, main_composers, representative_works, cultural_influences, image_url, theme_color, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', 'c3e71e46-22f6-4ece-904e-61fca9db5521', $$Rock$$, $$rock$$, NULL, $$1950$$, $$Estados Unidos/Reino Unido$$, $$Revolução cultural dos anos 50. Fusão de blues, country e R&B. Símbolo de rebeldia juvenil, liberdade e transformação social.$$, $${"obras": ["Stairway to Heaven - Led Zeppelin", "Bohemian Rhapsody - Queen", "Smells Like Teen Spirit - Nirvana"], "estilos": ["Rock and Roll", "Hard Rock", "Progressive Rock", "Punk Rock", "Heavy Metal", "Alternative Rock", "Indie Rock", "Grunge"], "artistas": ["Elvis Presley", "The Beatles", "Led Zeppelin", "Pink Floyd", "Queen", "Jimi Hendrix", "Nirvana", "Radiohead"], "estrutura": ["Backbeat forte (2 e 4)", "Guitarra elétrica como protagonista", "Forma: verso-refrão", "Energia e volume altos", "Distorção e efeitos"], "instrumentos": ["Guitarra elétrica", "Baixo elétrico", "Bateria", "Teclados", "Voz"]}$$, '[]', '[]', '[]', $$Anos 50 EUA/Reino Unido. Fusão de blues, country, R&B. Contracultura, rebeldia juvenil. Transformou indústria musical e cultura global.$$, NULL, $$#dc2626$$, true, '2025-10-27 18:41:40.135539+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_genres (tenant_id, id, name, slug, origin_period_id, origin_decade, origin_country, description, musical_characteristics, related_genres, main_composers, representative_works, cultural_influences, image_url, theme_color, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', 'd02dafe6-4b7e-46f5-b07b-dc753433fba9', $$Blues$$, $$blues$$, NULL, $$1890$$, $$Estados Unidos$$, $$Raiz da música popular moderna. Nasceu das work songs e spirituals afro-americanos. Expressão profunda de luta, dor, alegria e resistência.$$, $${"obras": ["Cross Road Blues - Robert Johnson", "The Thrill Is Gone - B.B. King", "Hoochie Coochie Man - Muddy Waters"], "estilos": ["Delta Blues", "Chicago Blues", "Texas Blues", "Blues Rock", "Jump Blues", "British Blues"], "artistas": ["Robert Johnson", "Muddy Waters", "B.B. King", "Howlin Wolf", "John Lee Hooker", "Bessie Smith", "Etta James", "Buddy Guy"], "estrutura": ["Forma de 12 compassos (I-IV-V)", "Blue notes (3ª e 7ª bemol)", "Call and response entre voz e instrumento", "Letra em AAB (repetição + resolução)", "Expressão emocional intensa"], "instrumentos": ["Guitarra (slide/bottleneck)", "Gaita (harmônica)", "Piano", "Baixo", "Bateria", "Voz"]}$$, '[]', '[]', '[]', $$Sul dos EUA (Delta do Mississippi), final séc. XIX. Raiz africana + experiência da escravidão/segregação. Influenciou rock, R&B, soul, jazz.$$, NULL, $$#1e40af$$, true, '2025-10-27 18:41:40.135539+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_genres (tenant_id, id, name, slug, origin_period_id, origin_decade, origin_country, description, musical_characteristics, related_genres, main_composers, representative_works, cultural_influences, image_url, theme_color, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', 'da1b0aa5-08c7-4503-bfe1-7c2dd0de0582', $$Forró$$, $$forro$$, NULL, $$1940$$, $$Brasil$$, $$Gênero nordestino que celebra a cultura sertaneja. Bailes populares, sanfona vibrante, ritmo contagiante e alegria coletiva.$$, $${"obras": ["Asa Branca - Luiz Gonzaga", "Xote das Meninas - Gonzaga", "Pagode Russo - Gonzaga", "Feira de Mangaio"], "estilos": ["Forró Pé-de-Serra (tradicional)", "Forró Universitário", "Forró Eletrônico", "Xote", "Baião", "Arrasta-pé"], "artistas": ["Luiz Gonzaga (Rei do Baião)", "Jackson do Pandeiro", "Dominguinhos", "Elba Ramalho", "Alceu Valença", "Sivuca", "Trio Nordestino"], "estrutura": ["Compasso 2/4", "Triângulo marcando tempo", "Sanfona como melodia principal", "Zabumba na base rítmica", "Dança a dois característica"], "instrumentos": ["Sanfona (acordeão)", "Zabumba", "Triângulo", "Violão", "Baixo"]}$$, '[]', '[]', '[]', $$Nordeste brasileiro, anos 40-50. Cultura sertaneja, festas juninas, bailes populares. Luiz Gonzaga popularizou nacionalmente. Identidade nordestina.$$, NULL, $$#f59e0b$$, true, '2025-10-27 18:41:40.135539+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_genres (tenant_id, id, name, slug, origin_period_id, origin_decade, origin_country, description, musical_characteristics, related_genres, main_composers, representative_works, cultural_influences, image_url, theme_color, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', 'de264c2b-399a-4901-a7bb-b62408b7a512', $$Jazz$$, $$jazz$$, NULL, $$1890$$, $$Estados Unidos$$, $$Gênero nascido da fusão de tradições africanas, blues e música europeia. Caracterizado por improvisação, síncope e expressão individual dentro de estruturas coletivas.$$, $${"obras": ["Take Five - Dave Brubeck", "So What - Miles Davis", "A Love Supreme - Coltrane"], "estilos": ["Dixieland", "Swing", "Bebop", "Cool Jazz", "Hard Bop", "Free Jazz", "Fusion", "Contemporary Jazz"], "artistas": ["Louis Armstrong", "Duke Ellington", "Charlie Parker", "Miles Davis", "John Coltrane", "Ella Fitzgerald", "Billie Holiday", "Herbie Hancock"], "estrutura": ["Improvisação como elemento central", "Síncope e swing", "Call and response", "Harmonia sofisticada (7ªs, 9ªs, alterações)", "Seções: tema-improvisação-tema"], "instrumentos": ["Trompete", "Saxofone", "Piano", "Contrabaixo", "Bateria", "Trombone", "Clarinete"]}$$, '[]', '[]', '[]', $$Nova Orleans, início séc. XX. Fusão de tradições africanas (ritmo, call-response), blues rural e harmonia europeia. Expressão da experiência afro-americana.$$, NULL, $$#d97706$$, true, '2025-10-27 18:41:40.135539+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_genres (tenant_id, id, name, slug, origin_period_id, origin_decade, origin_country, description, musical_characteristics, related_genres, main_composers, representative_works, cultural_influences, image_url, theme_color, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', 'e1db826e-01a8-4150-9fb6-54054e7ff2e5', $$Noturno$$, $$noturno$$, 'e8ce8fcc-5d20-4557-be06-c908b975e141', NULL, NULL, $$Peça instrumental, geralmente para piano, de caráter lírico e contemplativo, evocando a atmosfera noturna.$$, $${"carater": "Lírico, contemplativo, noturno", "estrutura": "Forma livre", "instrumento": "Principalmente piano", "popularizador": "Chopin"}$$, '[]', '[]', '[]', NULL, NULL, $$#8b5cf6$$, true, '2025-10-26 03:54:07.846053+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_genres (tenant_id, id, name, slug, origin_period_id, origin_decade, origin_country, description, musical_characteristics, related_genres, main_composers, representative_works, cultural_influences, image_url, theme_color, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', 'ed28810b-fc8d-40c3-8530-bf6622a2c138', $$Fuga$$, $$fuga$$, 'd8c30e03-788e-4a90-970c-7585963b3949', NULL, NULL, $$Técnica composicional contrapontística rigorosa onde um tema (sujeito) é desenvolvido por imitação em diferentes vozes.$$, $${"mestre": "J.S. Bach", "tecnica": "Contraponto imitativo", "estrutura": "Exposição + Desenvolvimento", "complexidade": "Alta"}$$, '[]', '[]', '[]', NULL, NULL, $$#6366f1$$, true, '2025-10-26 03:54:07.846053+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_genres (tenant_id, id, name, slug, origin_period_id, origin_decade, origin_country, description, musical_characteristics, related_genres, main_composers, representative_works, cultural_influences, image_url, theme_color, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', 'ee294591-d3bd-4408-98d1-68eeb60b529d', $$Música de Câmara$$, $$musica-camara$$, NULL, $$1750$$, $$Áustria$$, $$Música para pequenos grupos instrumentais, com diálogo equilibrado entre instrumentos.$$, $${"obras": ["Quarteto Op. 76 - Haydn", "Quinteto Clarineta - Mozart", "Trio Piano Op. 97 - Beethoven"], "estrutura": ["2 a 9 músicos", "Um músico por parte", "Conversação musical", "Quarteto/trio/quinteto"], "compositores": ["Haydn", "Mozart", "Beethoven", "Schubert", "Brahms"]}$$, '[]', '[]', '[]', $$Executada em salões de palácios. Quarteto de cordas = forma suprema (Haydn, Mozart, Beethoven).$$, NULL, $$#10b981$$, true, '2025-10-27 18:42:59.423794+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_genres (tenant_id, id, name, slug, origin_period_id, origin_decade, origin_country, description, musical_characteristics, related_genres, main_composers, representative_works, cultural_influences, image_url, theme_color, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', 'f1c3abb7-95b4-4400-a9bb-4797888b11a6', $$Quarteto de Cordas$$, $$quarteto-cordas$$, 'f8ed8ab3-ef44-47e5-8a3f-80b4dd60f89a', NULL, NULL, $$Formação de música de câmara com quatro instrumentos de cordas (2 violinos, viola e violoncelo) e também o gênero de obras escritas para essa formação.$$, $${"textura": "4 vozes independentes", "formacao": "2 violinos + viola + violoncelo", "natureza": "Música de câmara", "intimidade": "Performance sem regente"}$$, '[]', '[]', '[]', NULL, NULL, $$#f59e0b$$, true, '2025-10-26 03:54:07.846053+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_genres (tenant_id, id, name, slug, origin_period_id, origin_decade, origin_country, description, musical_characteristics, related_genres, main_composers, representative_works, cultural_influences, image_url, theme_color, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', 'f37e768f-1d17-4fe8-b7e1-217a2c073607', $$Samba$$, $$samba$$, NULL, $$1910$$, $$Brasil$$, $$Gênero símbolo do Brasil. Nasceu nos terreiros e rodas de samba do Rio de Janeiro. Patrimônio cultural imaterial da humanidade (UNESCO).$$, $${"obras": ["Pelo Telefone (1º samba gravado)", "Aquarela do Brasil", "Mas Que Nada", "O Mundo é um Moinho - Cartola"], "estilos": ["Samba de Roda", "Samba-enredo", "Samba-canção", "Samba de Breque", "Pagode", "Samba-rock", "Samba-jazz"], "artistas": ["Cartola", "Paulinho da Viola", "Clara Nunes", "Beth Carvalho", "Zeca Pagodinho", "Martinho da Vila", "Dona Ivone Lara", "Noel Rosa"], "estrutura": ["Compasso 2/4 sincopado", "Batucada característica", "Harmonia em tonalidade maior", "Partido-alto (improviso)", "Roda de samba (coletivo)"], "instrumentos": ["Surdo", "Pandeiro", "Tamborim", "Cuíca", "Cavaquinho", "Violão de 7 cordas", "Repique", "Agogô"]}$$, '[]', '[]', '[]', $$Rio de Janeiro, início séc. XX. Raízes africanas (batuque, lundu) + cultura afro-brasileira. Carnaval, resistência cultural, identidade nacional.$$, NULL, $$#10b981$$, true, '2025-10-27 18:41:40.135539+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

COMMIT;