-- =============================================
-- Migration: 024_history_movements.sql
-- Table: core.history_movements
-- Source CSV: historia_movimentos_rows.csv
-- Generated: 2026-02-28T16:15:03.724Z
-- Rows: 18
-- =============================================

BEGIN;

INSERT INTO core.history_movements (tenant_id, id, name, start_year, end_year, main_locations, manifesto, characteristics, composers, iconic_works, historical_context, legacy, image_url, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '176711df-1c31-41d3-87f6-a2acf371b70a', $$Música Concreta e Eletroacústica$$, 1948, 2000, $$["França","Alemanha","EUA"]$$, $$Explorar sons gravados, manipulados e sintetizados, expandindo a definição de música$$, $${"tags": ["eletrônica", "concreta", "tecnologia", "experimental"], "compositores": ["Pierre Schaeffer", "Stockhausen", "Boulez", "Varèse"], "caracteristicas_musicais": ["Sons concretos", "Manipulação de fita", "Síntese eletrônica", "Espacialização", "Texturas sonoras"]}$$, '[]', '[]', $$Movimento que explorou tecnologia: fita magnética, sintetizadores, gravação multipista, computadores$$, $$Abriu caminho para toda música eletrônica, música de cinema, sound design e produção moderna$$, NULL, true, '2025-10-26 13:42:54.791738+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_movements (tenant_id, id, name, start_year, end_year, main_locations, manifesto, characteristics, composers, iconic_works, historical_context, legacy, image_url, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '48da5aab-42e4-4102-939e-e80f42f9c77b', $$Movimento Tropicalista$$, 1967, 1972, $$["Brasil"]$$, $$Antropofagia cultural: fundir rock, música pop, vanguarda erudita e tradição brasileira$$, $${"tags": ["tropicalismo", "brasil", "antropofagia", "experimental"], "compositores": ["Caetano Veloso", "Gilberto Gil", "Tom Zé", "Os Mutantes"], "caracteristicas_musicais": ["Fusão de estilos", "Antropofagia cultural", "Experimentação eletrônica", "Letras provocativas", "Performance teatral"]}$$, '[]', '[]', $$Movimento brasileiro que fundiu rock, pop, vanguarda e tradição. Resistência à ditadura, influenciado por Bossa Nova, concretismo e contracultura$$, $$Revolucionou MPB, influenciou toda música brasileira posterior, exemplo de vanguarda política e musical$$, NULL, true, '2025-10-26 13:42:54.791738+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_movements (tenant_id, id, name, start_year, end_year, main_locations, manifesto, characteristics, composers, iconic_works, historical_context, legacy, image_url, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '4a7b6fdf-0c32-4f98-9d57-8d95db3831a4', $$Iluminismo Musical$$, 1750, 1820, $$["Áustria","Alemanha","França"]$$, $$Razão, clareza, equilíbrio e naturalidade$$, $${"tags": ["clássico", "forma sonata", "sinfonia", "equilíbrio"], "compositores": ["Haydn", "Mozart", "Beethoven inicial", "CPE Bach"], "caracteristicas_musicais": ["Forma sonata", "Simetria e equilíbrio", "Melodias cantáveis", "Harmonia tonal clara", "Orquestra moderna"]}$$, '[]', '[]', $$Movimento intelectual que valorizou razão, clareza, equilíbrio. Influenciado pelo Iluminismo filosófico, Revolução Francesa e ascensão da burguesia$$, $$Criou as formas clássicas (sonata, sinfonia, quarteto) que estruturaram a música até hoje$$, NULL, true, '2025-10-26 13:42:54.791738+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_movements (tenant_id, id, name, start_year, end_year, main_locations, manifesto, characteristics, composers, iconic_works, historical_context, legacy, image_url, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '4f7561d7-2a0d-4d6a-a036-7ffc7934aace', $$Nacionalismo Musical$$, 1850, 1920, $$["Praga","Moscou","Helsinque","Varsóvia"]$$, $$Busca por uma identidade musical nacional através do uso de melodias folclóricas, ritmos tradicionais e temas históricos ou literários locais.$$, $$["Melodias folclóricas", "Ritmos tradicionais", "Temas históricos nacionais", "Instrumentação característica", "Idiomas locais"]$$, '[]', '[]', $$Movimento que incorporava elementos folclóricos e temas nacionais na música erudita, valorizando a identidade cultural. Compositores: Smetana, Dvořák, Mussorgsky, Sibelius.$$, $$Estabeleceu escolas nacionais de composição em diversos países.$$, NULL, true, '2025-10-26 04:40:51.40056+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_movements (tenant_id, id, name, start_year, end_year, main_locations, manifesto, characteristics, composers, iconic_works, historical_context, legacy, image_url, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '6ce3a809-c639-474b-aba1-c97a902d9dcf', $$Neoclassicismo$$, 1920, 1950, $$["Paris","França","Rússia"]$$, $$Reação ao gigantismo romântico e ao expressionismo. Valoriza clareza, objetividade e formas do período clássico/barroco com harmonia moderna.$$, $$["Formas clássicas", "Clareza e objetividade", "Texturas transparentes", "Ironia e distanciamento", "Ritmos motóricos"]$$, '[]', '[]', $$Retorno às formas clássicas com linguagem moderna, rejeitando o excesso emocional do Romantismo tardio. Compositores: Igor Stravinsky, Sergei Prokofiev, Paul Hindemith.$$, $$Influenciou a música da metade do século XX com seu equilíbrio entre tradição e modernidade.$$, NULL, true, '2025-10-26 04:40:51.40056+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_movements (tenant_id, id, name, start_year, end_year, main_locations, manifesto, characteristics, composers, iconic_works, historical_context, legacy, image_url, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '75a7ab64-50f1-4257-a43d-94b8a9870f46', $$Nacionalismo Musical$$, 1850, 1920, $$["Rússia","Tchecoslováquia","Noruega","Finlândia","Brasil"]$$, $$Criar música com identidade nacional usando melodias folclóricas, ritmos populares e temas históricos$$, $${"tags": ["nacionalismo", "folclore", "identidade"], "compositores": ["Smetana", "Dvořák", "Grieg", "Sibelius", "Mussorgsky", "Villa-Lobos"], "caracteristicas_musicais": ["Melodias folclóricas", "Ritmos nacionais", "Escalas modais", "Temas históricos", "Instrumentos típicos"]}$$, '[]', '[]', $$Movimento que buscou criar música com identidade nacional. Impulsionado por independências nacionais, romantismo literário e busca por identidade cultural$$, $$Preservou e valorizou tradições musicais de diversos países, influenciando toda música do século XX$$, NULL, true, '2025-10-26 13:42:54.791738+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_movements (tenant_id, id, name, start_year, end_year, main_locations, manifesto, characteristics, composers, iconic_works, historical_context, legacy, image_url, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '7c3747b5-6ee3-4100-87cf-c81d2c04effc', $$Barroco$$, 1600, 1750, $$["Itália","Alemanha","França","Inglaterra"]$$, $$Ornamentação exuberante, contraste dramático, grandiosidade e emocionalidade intensa$$, $${"tags": ["barroco", "ópera", "concerto", "fuga"], "compositores": ["Bach", "Handel", "Vivaldi", "Monteverdi", "Purcell"], "caracteristicas_musicais": ["Ornamentação elaborada", "Baixo contínuo", "Contraste tutti/solo", "Affetti", "Forma fugal", "Ópera"]}$$, '[]', '[]', $$Movimento caracterizado por ornamentação, contraste dramático e emocionalidade. Influenciado pela Contrarreforma católica, absolutismo monárquico e arquitetura barroca$$, $$Estabeleceu ópera, concerto, fuga e o sistema tonal que dominaria a música ocidental$$, NULL, true, '2025-10-26 13:42:54.791738+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_movements (tenant_id, id, name, start_year, end_year, main_locations, manifesto, characteristics, composers, iconic_works, historical_context, legacy, image_url, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '7f785247-e7cc-4e8f-adf6-2485e117f4ca', $$Impressionismo Musical$$, 1890, 1920, $$["Paris","França"]$$, $$Assim como na pintura, o impressionismo musical evita contornos nítidos, preferindo sugestões e atmosferas. Privilegia o timbre sobre a melodia tradicional.$$, $$["Escalas modais e de tons inteiros", "Harmonias paralelas", "Texturas fluidas", "Ênfase no timbre", "Formas livres"]$$, '[]', '[]', $$Movimento que buscava criar atmosferas e impressões através de harmonias inovadoras, timbres sutis e estruturas fluidas. Compositores: Claude Debussy, Maurice Ravel, Erik Satie.$$, $$Influenciou profundamente a música do século XX, abrindo caminho para novas explorações harmônicas e tímbricas.$$, NULL, true, '2025-10-26 04:40:51.40056+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_movements (tenant_id, id, name, start_year, end_year, main_locations, manifesto, characteristics, composers, iconic_works, historical_context, legacy, image_url, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '8f2ce4bc-ecdd-4935-9ba8-2c58f8a7502a', $$Serialismo$$, 1920, 1975, $$["Viena","Darmstadt","Paris"]$$, $$Extensão do dodecafonismo para todos os parâmetros musicais (altura, duração, dinâmica, timbre). Controle total e sistemático.$$, $$["Dodecafonismo", "Séries de alturas", "Séries de durações", "Controle paramétrico total", "Ausência de hierarquia tonal"]$$, '[]', '[]', $$Sistema composicional onde todos os parâmetros musicais são organizados em séries pré-determinadas. Compositores: Arnold Schoenberg, Pierre Boulez, Karlheinz Stockhausen.$$, $$Representou o auge do controle composicional sistemático no século XX.$$, NULL, true, '2025-10-26 04:40:51.40056+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_movements (tenant_id, id, name, start_year, end_year, main_locations, manifesto, characteristics, composers, iconic_works, historical_context, legacy, image_url, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '93811399-e333-4598-b45f-cfc6dff4c88e', $$Minimalismo$$, 1960, 2000, $$["Nova York","São Francisco","Estados Unidos"]$$, $$Redução aos elementos essenciais. Uso de repetição, processos graduais e consonância. Reação à complexidade da vanguarda.$$, $$["Repetição de padrões", "Processos graduais", "Consonância tonal", "Pulso constante", "Simplicidade estrutural"]$$, '[]', '[]', $$Estilo caracterizado por repetição de padrões simples, mudanças graduais e estruturas acessíveis. Compositores: Steve Reich, Philip Glass, Terry Riley, John Adams.$$, $$Tornou-se um dos estilos mais populares e acessíveis da música contemporânea.$$, NULL, true, '2025-10-26 04:40:51.40056+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_movements (tenant_id, id, name, start_year, end_year, main_locations, manifesto, characteristics, composers, iconic_works, historical_context, legacy, image_url, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', 'a0757afc-9fc7-4a0d-8cb3-39fa66dc9f05', $$Humanismo Renascentista$$, 1400, 1600, $$["Itália","França","Inglaterra"]$$, $$Valorização do ser humano, da razão e do conhecimento clássico greco-romano$$, $${"tags": ["renascimento", "humanismo", "polifonia", "madrigal"], "compositores": ["Josquin des Prez", "Palestrina", "Orlando di Lasso", "Thomas Tallis"], "caracteristicas_musicais": ["Polifonia vocal", "Música sacra e secular", "Madrigais", "Chanson", "Imitação entre vozes"]}$$, '[]', '[]', $$Movimento cultural que valorizou o ser humano, a razão e o conhecimento clássico greco-romano. Na música, levou à polifonia mais complexa, uso de instrumentos e valorização da expressão humana$$, $$Estabeleceu as bases da música polifônica e da integração entre texto e música$$, NULL, true, '2025-10-26 13:42:54.791738+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_movements (tenant_id, id, name, start_year, end_year, main_locations, manifesto, characteristics, composers, iconic_works, historical_context, legacy, image_url, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', 'a14755c7-ed7d-4ced-a91e-cb31cd50e723', $$Expressionismo$$, 1900, 1925, $$["Viena","Berlim","Áustria","Alemanha"]$$, $$Rejeição da beleza tradicional em favor da expressão emocional crua e intensa. Reflexo da angústia do início do século XX.$$, $$["Atonalidade", "Dissonâncias extremas", "Formas fragmentadas", "Expressão emocional intensa", "Textos sombrios"]$$, '[]', '[]', $$Movimento que enfatiza a expressão intensa de emoções através de dissonâncias extremas, atonalidade e formas fragmentadas. Compositores: Arnold Schoenberg, Alban Berg, Anton Webern.$$, $$Levou ao desenvolvimento do dodecafonismo e serialismo.$$, NULL, true, '2025-10-26 04:40:51.40056+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_movements (tenant_id, id, name, start_year, end_year, main_locations, manifesto, characteristics, composers, iconic_works, historical_context, legacy, image_url, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', 'c8e90b58-7a4e-45ba-b5ca-9971511f969f', $$Romantismo$$, 1800, 1910, $$["Alemanha","Áustria","França","Rússia","Itália"]$$, $$Emoção, individualidade, natureza, nacionalismo e fantasia$$, $${"tags": ["romantismo", "emoção", "cromatismo", "virtuosismo"], "compositores": ["Beethoven", "Schubert", "Chopin", "Liszt", "Wagner", "Brahms", "Tchaikovsky"], "caracteristicas_musicais": ["Expansão harmônica", "Cromatismo", "Expressão emocional", "Poema sinfônico", "Lied", "Virtuosismo"]}$$, '[]', '[]', $$Movimento que valorizou emoção, individualidade, natureza e nacionalismo. Influenciado pela literatura romântica, pintura de Delacroix e Revolução Industrial$$, $$Expandiu a orquestra e a harmonia, criou o lied e o poema sinfônico, valorizou o sentimento pessoal$$, NULL, true, '2025-10-26 13:42:54.791738+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_movements (tenant_id, id, name, start_year, end_year, main_locations, manifesto, characteristics, composers, iconic_works, historical_context, legacy, image_url, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', 'cb1044f1-94e0-46ee-9514-0682d455772f', $$Neoclassicismo$$, 1920, 1950, $$["França","Rússia"]$$, $$Retorno às formas e clareza clássicas mas com linguagem harmônica moderna$$, $${"tags": ["neoclassicismo", "clareza", "objetividade"], "compositores": ["Stravinsky", "Prokofiev", "Hindemith", "Poulenc"], "caracteristicas_musicais": ["Formas clássicas", "Clareza textural", "Economia de meios", "Objetividade", "Politonalidade"]}$$, '[]', '[]', $$Reação ao Romantismo tardio e Expressionismo. Contexto do entre-guerras, Grupo dos Seis na França, busca por objetividade$$, $$Mostrou que música moderna podia ser acessível, clara e emotiva sem ser romântica$$, NULL, true, '2025-10-26 13:42:54.791738+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_movements (tenant_id, id, name, start_year, end_year, main_locations, manifesto, characteristics, composers, iconic_works, historical_context, legacy, image_url, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', 'd9e338f8-c304-4637-bafd-d4462aa1ea94', $$Minimalismo$$, 1960, 2000, $$["EUA"]$$, $$Repetição, mudanças graduais, pulsos constantes e material musical mínimo para criar obras hipnóticas$$, $${"tags": ["minimalismo", "repetição", "padrões", "pulso"], "compositores": ["Steve Reich", "Philip Glass", "Terry Riley", "John Adams"], "caracteristicas_musicais": ["Repetição de padrões", "Mudança gradual", "Pulsos constantes", "Harmonia modal simples", "Texturas estratificadas"]}$$, '[]', '[]', $$Estilo que usou repetição e mudanças graduais. Influenciado por arte minimalista, música indiana, jazz modal, reação ao serialismo$$, $$Tornou música contemporânea acessível novamente, influenciou pop, rock progressivo e trilhas sonoras$$, NULL, true, '2025-10-26 13:42:54.791738+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_movements (tenant_id, id, name, start_year, end_year, main_locations, manifesto, characteristics, composers, iconic_works, historical_context, legacy, image_url, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', 'dec02040-661e-4ccd-ba8c-d0d6082ab9db', $$Pós-Modernismo Musical$$, 1970, NULL, $$["Global"]$$, $$Misturar estilos diversos, aceitar pluralidade, usar citações, humor e ironia$$, $${"tags": ["pós-moderno", "ecletismo", "citação", "pluralidade"], "compositores": ["John Zorn", "Arvo Pärt", "Henryk Górecki", "Alfred Schnittke"], "caracteristicas_musicais": ["Ecletismo estilístico", "Citações e colagens", "Mistura erudito/popular", "Ironia", "Múltiplas influências"]}$$, '[]', '[]', $$Corrente que mistura estilos diversos. Contexto: pós-modernismo filosófico, globalização, world music, MTV, internet$$, $$Legitimou a mistura de estilos e o fim de hierarquias entre erudito e popular$$, NULL, true, '2025-10-26 13:42:54.791738+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_movements (tenant_id, id, name, start_year, end_year, main_locations, manifesto, characteristics, composers, iconic_works, historical_context, legacy, image_url, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', 'f1b01e03-5bbf-4a19-bb22-80b1c15c414e', $$Impressionismo Musical$$, 1890, 1920, $$["França"]$$, $$Criar atmosferas sonoras através de cores harmônicas, escalas exóticas e timbres inovadores$$, $${"tags": ["impressionismo", "atmosfera", "timbre", "exotismo"], "compositores": ["Debussy", "Ravel", "Satie"], "caracteristicas_musicais": ["Acordes de 9ª, 11ª, 13ª", "Escalas exóticas", "Timbres inovadores", "Forma livre", "Evocação atmosférica"]}$$, '[]', '[]', $$Inspirado pela pintura impressionista. Influenciado por Monet, simbolismo poético, música gamelan javanesa e Art Nouveau$$, $$Libertou a harmonia das regras tradicionais, valorizou timbre e atmosfera sobre melodia$$, NULL, true, '2025-10-26 13:42:54.791738+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_movements (tenant_id, id, name, start_year, end_year, main_locations, manifesto, characteristics, composers, iconic_works, historical_context, legacy, image_url, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', 'f2f34bd6-e126-4fd2-b94a-ec84d8521318', $$Expressionismo$$, 1908, 1930, $$["Áustria","Alemanha"]$$, $$Expressar angústias, medos e emoções extremas através de atonalidade e dissonância$$, $${"tags": ["expressionismo", "atonal", "dodecafônico", "angústia"], "compositores": ["Schoenberg", "Berg", "Webern"], "caracteristicas_musicais": ["Atonalidade livre", "Dodecafonismo", "Dissonâncias extremas", "Sprechgesang", "Expressão de angústia"]}$$, '[]', '[]', $$Movimento que expressou angústias do início do século XX. Influenciado por pintura expressionista alemã, Primeira Guerra Mundial e psicanálise de Freud$$, $$Rompeu com o sistema tonal de 300 anos, criou o dodecafonismo, abriu caminho para vanguardas$$, NULL, true, '2025-10-26 13:42:54.791738+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

COMMIT;