-- =============================================
-- Migration: 028_history_theory_concepts.sql
-- Table: core.history_theory_concepts
-- Source CSV: historia_conceitos_teoricos_rows.csv
-- Generated: 2026-02-28T16:15:03.774Z
-- Rows: 10
-- =============================================

BEGIN;

INSERT INTO core.history_theory_concepts (tenant_id, id, name, category, simple_definition, technical_definition, origin_period_id, audio_examples, diagram_url, difficulty_level, prerequisites, exercises, tags, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '1309f8b0-3508-4571-b1af-04b7058c3302', $$Baixo Contínuo$$, $$Harmonia$$, $$Prática de acompanhamento harmônico onde uma linha de baixo é realizada com acordes improvisados.$$, $$O baixo contínuo (basso continuo) é a espinha dorsal da música barroca. Um instrumento grave (violoncelo, fagote, contrabaixo) toca a linha de baixo enquanto um instrumento harmônico (cravo, órgão, alaúde) improvisa os acordes baseando-se em cifras numéricas escritas abaixo da linha de baixo. Exemplos: Sonatas barrocas, Concertos de Vivaldi, Cantatas de Bach.$$, 'd8c30e03-788e-4a90-970c-7585963b3949', '[]', NULL, 2, '[]', '[]', '["barroco","harmonia","teoria"]'::jsonb, true, '2025-10-26 04:40:58.558919+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_theory_concepts (tenant_id, id, name, category, simple_definition, technical_definition, origin_period_id, audio_examples, diagram_url, difficulty_level, prerequisites, exercises, tags, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '13e95794-8bc6-4ad7-99aa-1a94c5535292', $$Forma Sonata$$, $$Forma$$, $$Estrutura formal tripartite: Exposição, Desenvolvimento e Recapitulação, tipicamente usada no primeiro movimento.$$, $$A forma sonata é a estrutura mais importante do período clássico. Na Exposição, apresentam-se dois temas contrastantes em tonalidades diferentes. No Desenvolvimento, esses temas são transformados e modulam por várias tonalidades. Na Recapitulação, ambos os temas retornam na tonalidade principal, resolvendo a tensão tonal. Exemplos: Sinfonia No. 40 de Mozart (1º mov), Sonata "Patética" de Beethoven (1º mov).$$, 'f8ed8ab3-ef44-47e5-8a3f-80b4dd60f89a', '[]', NULL, 3, '[]', '[]', '["classico","forma","teoria"]'::jsonb, true, '2025-10-26 04:40:58.558919+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_theory_concepts (tenant_id, id, name, category, simple_definition, technical_definition, origin_period_id, audio_examples, diagram_url, difficulty_level, prerequisites, exercises, tags, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '53fc0da8-8295-48dc-8c94-5de5cc81f903', $$Politonalidade$$, $$Harmonia$$, $$Uso simultâneo de duas ou mais tonalidades diferentes.$$, $$Técnica do início do século XX onde linhas melódicas em tonalidades diferentes soam simultaneamente, criando choques harmônicos intencionais. Milhaud e Stravinsky exploraram extensivamente esta técnica, que cria textura complexa e desorienta a percepção tonal tradicional. Exemplos: A Sagração da Primavera de Stravinsky, Concerto para Orquestra de Bartók.$$, NULL, '[]', NULL, 4, '[]', '[]', '["moderno","harmonia","vanguarda"]'::jsonb, true, '2025-10-26 04:40:58.558919+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_theory_concepts (tenant_id, id, name, category, simple_definition, technical_definition, origin_period_id, audio_examples, diagram_url, difficulty_level, prerequisites, exercises, tags, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '6e86789d-e1de-48a0-b06f-a5c14164732b', $$Dodecafonismo$$, $$Harmonia$$, $$Sistema composicional que usa as doze notas cromáticas em ordem pré-determinada (série), evitando hierarquia tonal.$$, $$Desenvolvido por Schoenberg, o método de composição com doze tons trata todas as notas igualmente, sem tônica. A série básica pode ser usada em quatro formas: original, retrógrada, inversão e inversão retrógrada. Nenhuma nota pode repetir antes que todas as doze soem. Exemplos: Suíte para Piano Op. 25 de Schoenberg, Concerto para Violino de Berg.$$, NULL, '[]', NULL, 5, '[]', '[]', '["moderno","serialismo","schoenberg"]'::jsonb, true, '2025-10-26 04:40:58.558919+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_theory_concepts (tenant_id, id, name, category, simple_definition, technical_definition, origin_period_id, audio_examples, diagram_url, difficulty_level, prerequisites, exercises, tags, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '759d33a1-6765-479e-9d09-cc7d014f735b', $$Contraponto$$, $$Textura$$, $$Técnica de combinar duas ou mais linhas melódicas independentes que soam simultaneamente.$$, $$Do latim "punctus contra punctum" (nota contra nota). O contraponto envolve regras estritas sobre como melodias simultâneas devem se relacionar, incluindo tipos de movimento (paralelo, contrário, oblíquo), tratamento de dissonâncias e independência rítmica. A fuga é a forma contrapontística mais complexa. Exemplos: A Arte da Fuga de Bach, Missa em Si menor.$$, 'd8c30e03-788e-4a90-970c-7585963b3949', '[]', NULL, 4, '[]', '[]', '["barroco","textura","contraponto"]'::jsonb, true, '2025-10-26 04:40:58.558919+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_theory_concepts (tenant_id, id, name, category, simple_definition, technical_definition, origin_period_id, audio_examples, diagram_url, difficulty_level, prerequisites, exercises, tags, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '893a2078-e03a-4088-a7b7-d4ed7bd5d25b', $$Rubato$$, $$Ritmo$$, $$Liberdade expressiva no tempo, onde o intérprete acelera ou desacelera para efeito emocional.$$, $$Do italiano "tempo rubato" (tempo roubado). Prática interpretativa onde o performer toma liberdades com o tempo métrico para aumentar a expressividade. Particularmente característico da música pianística romântica. Chopin era mestre desta técnica. Exemplos: Noturnos de Chopin, Rapsódias Húngaras de Liszt.$$, 'e8ce8fcc-5d20-4557-be06-c908b975e141', '[]', NULL, 2, '[]', '[]', '["romantico","interpretacao","piano"]'::jsonb, true, '2025-10-26 04:40:58.558919+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_theory_concepts (tenant_id, id, name, category, simple_definition, technical_definition, origin_period_id, audio_examples, diagram_url, difficulty_level, prerequisites, exercises, tags, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', '90e4657d-cc37-44cf-aecd-a453da795970', $$Ostinato$$, $$Ritmo$$, $$Padrão musical (melódico, rítmico ou harmônico) que se repete persistentemente.$$, $$Do italiano "obstinado". Técnica composicional onde um padrão curto é repetido muitas vezes, geralmente no baixo (basso ostinato ou ground bass). Cria sensação hipnótica ou de inevitabilidade. Usado do Barroco ao Minimalismo. Exemplos: Passacaglia em Dó menor de Bach, Boléro de Ravel, Music for 18 Musicians de Reich.$$, 'd8c30e03-788e-4a90-970c-7585963b3949', '[]', NULL, 2, '[]', '[]', '["tecnica","repeticao","ostinato"]'::jsonb, true, '2025-10-26 04:40:58.558919+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_theory_concepts (tenant_id, id, name, category, simple_definition, technical_definition, origin_period_id, audio_examples, diagram_url, difficulty_level, prerequisites, exercises, tags, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', 'ac9e31d2-f0c3-4ede-b258-ea48b050c44c', $$Cromatismo$$, $$Harmonia$$, $$Uso extensivo de notas cromáticas (fora da escala diatônica) para colorir harmonias e melodias.$$, $$O cromatismo intensificou-se no Romantismo, especialmente com Wagner, levando à dissolução da tonalidade funcional. As doze notas cromáticas são usadas livremente, obscurecendo a tonalidade através de modulações constantes e harmonias ambíguas. Exemplos: Tristão e Isolda de Wagner, Sonata em Si menor de Liszt.$$, 'e8ce8fcc-5d20-4557-be06-c908b975e141', '[]', NULL, 3, '[]', '[]', '["romantico","harmonia","cromatismo"]'::jsonb, true, '2025-10-26 04:40:58.558919+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_theory_concepts (tenant_id, id, name, category, simple_definition, technical_definition, origin_period_id, audio_examples, diagram_url, difficulty_level, prerequisites, exercises, tags, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', 'ba5b40e1-59c2-4f88-bb8d-e03be37b17df', $$Modalismo$$, $$Harmonia$$, $$Uso de modos (escalas) diferentes das escalas maior e menor tradicionais.$$, $$Os modos (dórico, frígio, lídio, mixolídio, etc.) eram base da música medieval e renascentista. Compositores modernos como Debussy, Ravel e Vaughan Williams resgataram os modos para escapar do sistema tonal maior-menor, criando cores harmônicas distintas. Exemplos: Quarteto de Cordas de Debussy, Daphnis et Chloé de Ravel.$$, NULL, '[]', NULL, 3, '[]', '[]', '["moderno","harmonia","modos"]'::jsonb, true, '2025-10-26 04:40:58.558919+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_theory_concepts (tenant_id, id, name, category, simple_definition, technical_definition, origin_period_id, audio_examples, diagram_url, difficulty_level, prerequisites, exercises, tags, is_active, created_at)
VALUES ('00000000-0000-0000-0000-000000000001', 'c031a5bb-0d2f-433f-b426-a3f64caae96d', $$Leitmotiv$$, $$Melodia$$, $$Tema musical recorrente associado a um personagem, ideia ou situação em uma ópera ou obra programática.$$, $$Termo alemão "tema condutor". Wagner desenvolveu extensivamente esta técnica em suas óperas, onde dezenas de leitmotive se entrelaçam, transformam e comentam a ação dramática. O leitmotiv pode representar personagens, objetos, emoções ou conceitos abstratos. Exemplos: O Anel do Nibelungo de Wagner, Pedro e o Lobo de Prokofiev.$$, 'e8ce8fcc-5d20-4557-be06-c908b975e141', '[]', NULL, 3, '[]', '[]', '["romantico","opera","melodia"]'::jsonb, true, '2025-10-26 04:40:58.558919+00'::timestamptz)
ON CONFLICT (id) DO NOTHING;

COMMIT;