-- =============================================
-- Migration: 029_history_quizzes.sql
-- Table: core.history_quizzes
-- Source CSV: historia_quiz_rows.csv
-- Generated: 2026-02-28T16:15:03.778Z
-- Rows: 18
-- =============================================

BEGIN;

INSERT INTO core.history_quizzes (tenant_id, id, title, period_id, difficulty_level, question_type, question, options, correct_answer, explanation, audio_url, image_url, tags, is_active, created_at, points)
VALUES ('00000000-0000-0000-0000-000000000001', '01b03b2a-c6c8-46c6-8702-6bd282a76c56', $$Gênero Romântico$$, 'e8ce8fcc-5d20-4557-be06-c908b975e141', 2, 'multiple_choice', $$Qual gênero musical combina orquestra com narrativa ou ideia extramusical?$$, '[{"id": "a", "texto": "Sinfonia", "correta": false}, {"id": "b", "texto": "Concerto", "correta": false}, {"id": "c", "texto": "Poema sinfônico", "correta": true}, {"id": "d", "texto": "Sonata", "correta": false}]'::jsonb, $$Poema sinfônico$$, $$O poema sinfônico é música programática orquestral que ilustra uma história, paisagem ou ideia, desenvolvido por Liszt.$$, NULL, NULL, '["romantico","generos","programatica"]'::jsonb, true, '2025-10-26 04:41:04.989877+00'::timestamptz, 10)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_quizzes (tenant_id, id, title, period_id, difficulty_level, question_type, question, options, correct_answer, explanation, audio_url, image_url, tags, is_active, created_at, points)
VALUES ('00000000-0000-0000-0000-000000000001', '13a9a90f-78da-4f85-a901-dcb105a95dcd', $$Minimalismo$$, NULL, 2, 'multiple_choice', $$Qual técnica é característica da música minimalista?$$, '[{"id": "a", "texto": "Dodecafonismo", "correta": false}, {"id": "b", "texto": "Cromatismo extremo", "correta": false}, {"id": "c", "texto": "Repetição de padrões", "correta": true}, {"id": "d", "texto": "Rubato livre", "correta": false}]'::jsonb, $$Repetição de padrões$$, $$O minimalismo usa repetição de padrões simples com mudanças graduais, como em "Music for 18 Musicians" de Steve Reich.$$, NULL, NULL, '["moderno","minimalismo","tecnica"]'::jsonb, true, '2025-10-26 04:41:04.989877+00'::timestamptz, 10)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_quizzes (tenant_id, id, title, period_id, difficulty_level, question_type, question, options, correct_answer, explanation, audio_url, image_url, tags, is_active, created_at, points)
VALUES ('00000000-0000-0000-0000-000000000001', '31845a7f-1fd0-45ca-a530-a7969a39449a', $$Forma Musical Clássica$$, 'f8ed8ab3-ef44-47e5-8a3f-80b4dd60f89a', 2, 'multiple_choice', $$Qual é a estrutura típica do primeiro movimento de uma sinfonia clássica?$$, '[{"id": "a", "texto": "Tema e variações", "correta": false}, {"id": "b", "texto": "Forma sonata", "correta": true}, {"id": "c", "texto": "Rondó", "correta": false}, {"id": "d", "texto": "Fuga", "correta": false}]'::jsonb, $$Forma sonata$$, $$A forma sonata (Exposição-Desenvolvimento-Recapitulação) é a estrutura padrão do primeiro movimento de sinfonias clássicas.$$, NULL, NULL, '["classico","forma","teoria"]'::jsonb, true, '2025-10-26 04:41:04.989877+00'::timestamptz, 10)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_quizzes (tenant_id, id, title, period_id, difficulty_level, question_type, question, options, correct_answer, explanation, audio_url, image_url, tags, is_active, created_at, points)
VALUES ('00000000-0000-0000-0000-000000000001', '5eec0365-dac8-4131-89af-26c007b17e6c', $$Tonalidade$$, 'f8ed8ab3-ef44-47e5-8a3f-80b4dd60f89a', 2, 'multiple_choice', $$Qual é a tonalidade relativa menor de Dó maior?$$, '[{"id": "a", "texto": "Ré menor", "correta": false}, {"id": "b", "texto": "Lá menor", "correta": true}, {"id": "c", "texto": "Mi menor", "correta": false}, {"id": "d", "texto": "Sol menor", "correta": false}]'::jsonb, $$Lá menor$$, $$Lá menor é a relativa menor de Dó maior (compartilham a mesma armadura de clave, sem acidentes).$$, NULL, NULL, '["teoria","tonalidade","harmonia"]'::jsonb, true, '2025-10-26 04:41:04.989877+00'::timestamptz, 10)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_quizzes (tenant_id, id, title, period_id, difficulty_level, question_type, question, options, correct_answer, explanation, audio_url, image_url, tags, is_active, created_at, points)
VALUES ('00000000-0000-0000-0000-000000000001', '68e9ceb9-a66e-4006-92be-77c7ee33dc81', $$Andamento$$, 'd8c30e03-788e-4a90-970c-7585963b3949', 1, 'multiple_choice', $$Qual termo indica tempo muito lento?$$, '[{"id": "a", "texto": "Presto", "correta": false}, {"id": "b", "texto": "Adagio", "correta": true}, {"id": "c", "texto": "Allegro", "correta": false}, {"id": "d", "texto": "Vivace", "correta": false}]'::jsonb, $$Adagio$$, $$Adagio indica tempo lento e tranquilo. Presto é muito rápido, Allegro é rápido e alegre, Vivace é vivo e animado.$$, NULL, NULL, '["teoria","andamento","basico"]'::jsonb, true, '2025-10-26 04:41:04.989877+00'::timestamptz, 10)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_quizzes (tenant_id, id, title, period_id, difficulty_level, question_type, question, options, correct_answer, explanation, audio_url, image_url, tags, is_active, created_at, points)
VALUES ('00000000-0000-0000-0000-000000000001', '98adc19f-1ac0-4040-8d93-963b9a61a3cc', $$Tríade Clássica$$, 'f8ed8ab3-ef44-47e5-8a3f-80b4dd60f89a', 1, 'multiple_choice', $$Quem são os três grandes compositores do período Clássico?$$, '[{"id": "a", "texto": "Bach, Handel, Vivaldi", "correta": false}, {"id": "b", "texto": "Haydn, Mozart, Beethoven", "correta": true}, {"id": "c", "texto": "Chopin, Liszt, Schumann", "correta": false}, {"id": "d", "texto": "Brahms, Wagner, Verdi", "correta": false}]'::jsonb, $$Haydn, Mozart, Beethoven$$, $$Haydn, Mozart e Beethoven são conhecidos como a "Tríade Clássica de Viena", definindo o estilo do período.$$, NULL, NULL, '["classico","compositores","historia"]'::jsonb, true, '2025-10-26 04:41:04.989877+00'::timestamptz, 10)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_quizzes (tenant_id, id, title, period_id, difficulty_level, question_type, question, options, correct_answer, explanation, audio_url, image_url, tags, is_active, created_at, points)
VALUES ('00000000-0000-0000-0000-000000000001', 'a44e8da1-902b-4ce3-9676-ab30e789f8be', $$Característica do Barroco$$, 'd8c30e03-788e-4a90-970c-7585963b3949', 1, 'multiple_choice', $$Qual dessas características é típica da música Barroca?$$, '[{"id": "a", "texto": "Forma sonata", "correta": false}, {"id": "b", "texto": "Baixo contínuo", "correta": true}, {"id": "c", "texto": "Atonalismo", "correta": false}, {"id": "d", "texto": "Minimalismo", "correta": false}]'::jsonb, $$Baixo contínuo$$, $$O baixo contínuo é uma das características mais marcantes da música Barroca, fornecendo a base harmônica.$$, NULL, NULL, '["barroco","teoria","caracteristicas"]'::jsonb, true, '2025-10-26 03:54:07.846053+00'::timestamptz, 10)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_quizzes (tenant_id, id, title, period_id, difficulty_level, question_type, question, options, correct_answer, explanation, audio_url, image_url, tags, is_active, created_at, points)
VALUES ('00000000-0000-0000-0000-000000000001', 'acd3b0ea-1ab8-42e1-82a7-506261290059', $$Dinâmica$$, 'e8ce8fcc-5d20-4557-be06-c908b975e141', 1, 'multiple_choice', $$O que significa "crescendo" na música?$$, '[{"id": "a", "texto": "Tocar mais rápido", "correta": false}, {"id": "b", "texto": "Aumentar gradualmente o volume", "correta": true}, {"id": "c", "texto": "Tocar mais lento", "correta": false}, {"id": "d", "texto": "Diminuir o volume", "correta": false}]'::jsonb, $$Aumentar gradualmente o volume$$, $$Crescendo (cresc.) indica aumento gradual de volume, recurso expressivo importante especialmente no Romantismo.$$, NULL, NULL, '["teoria","dinamica","basico"]'::jsonb, true, '2025-10-26 04:41:04.989877+00'::timestamptz, 10)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_quizzes (tenant_id, id, title, period_id, difficulty_level, question_type, question, options, correct_answer, explanation, audio_url, image_url, tags, is_active, created_at, points)
VALUES ('00000000-0000-0000-0000-000000000001', 'bf3ea990-5492-45bc-a295-b4e669bed784', $$Textura Musical$$, 'f8ed8ab3-ef44-47e5-8a3f-80b4dd60f89a', 3, 'multiple_choice', $$Como se chama a textura onde várias linhas melódicas independentes soam simultaneamente?$$, '[{"id": "a", "texto": "Homofonia", "correta": false}, {"id": "b", "texto": "Monofonia", "correta": false}, {"id": "c", "texto": "Polifonia", "correta": true}, {"id": "d", "texto": "Heterofonia", "correta": false}]'::jsonb, $$Polifonia$$, $$Polifonia (ou contraponto) é a textura com múltiplas linhas melódicas independentes, característica de Bach e da música renascentista.$$, NULL, NULL, '["teoria","textura","contraponto"]'::jsonb, true, '2025-10-26 04:41:04.989877+00'::timestamptz, 10)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_quizzes (tenant_id, id, title, period_id, difficulty_level, question_type, question, options, correct_answer, explanation, audio_url, image_url, tags, is_active, created_at, points)
VALUES ('00000000-0000-0000-0000-000000000001', 'c568e508-f1b7-474a-ab6d-d9af09eacb0f', $$Virtuosismo Romântico$$, 'e8ce8fcc-5d20-4557-be06-c908b975e141', 1, 'multiple_choice', $$Qual compositor romântico era conhecido como o maior virtuose do piano de sua época?$$, '[{"id": "a", "texto": "Franz Liszt", "correta": true}, {"id": "b", "texto": "Robert Schumann", "correta": false}, {"id": "c", "texto": "Felix Mendelssohn", "correta": false}, {"id": "d", "texto": "Anton Bruckner", "correta": false}]'::jsonb, $$Franz Liszt$$, $$Franz Liszt foi o maior virtuose do piano do século XIX, revolucionando a técnica pianística e criando o recital solo.$$, NULL, NULL, '["romantico","piano","virtuosismo"]'::jsonb, true, '2025-10-26 04:41:04.989877+00'::timestamptz, 10)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_quizzes (tenant_id, id, title, period_id, difficulty_level, question_type, question, options, correct_answer, explanation, audio_url, image_url, tags, is_active, created_at, points)
VALUES ('00000000-0000-0000-0000-000000000001', 'cbb78a63-4382-49a2-ac04-43103a4a4001', $$Período de Mozart$$, 'f8ed8ab3-ef44-47e5-8a3f-80b4dd60f89a', 1, 'multiple_choice', $$Em qual período musical viveu Mozart?$$, '[{"id": "a", "texto": "Barroco", "correta": false}, {"id": "b", "texto": "Clássico", "correta": true}, {"id": "c", "texto": "Romântico", "correta": false}, {"id": "d", "texto": "Moderno", "correta": false}]'::jsonb, $$Clássico$$, $$Mozart (1756-1791) é um dos maiores representantes do período Clássico.$$, NULL, NULL, '["classico","compositores","mozart"]'::jsonb, true, '2025-10-26 03:54:07.846053+00'::timestamptz, 10)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_quizzes (tenant_id, id, title, period_id, difficulty_level, question_type, question, options, correct_answer, explanation, audio_url, image_url, tags, is_active, created_at, points)
VALUES ('00000000-0000-0000-0000-000000000001', 'd0b35742-2ede-4aa5-8300-351b41f9545e', $$Patronato Musical$$, 'f8ed8ab3-ef44-47e5-8a3f-80b4dd60f89a', 2, 'multiple_choice', $$Para qual família nobre Haydn trabalhou por quase 30 anos?$$, '[{"id": "a", "texto": "Habsburgos", "correta": false}, {"id": "b", "texto": "Esterházy", "correta": true}, {"id": "c", "texto": "Hohenzollern", "correta": false}, {"id": "d", "texto": "Romanov", "correta": false}]'::jsonb, $$Esterházy$$, $$Haydn serviu à família Esterházy de 1761 a 1790, compondo extensivamente para as atividades musicais da corte.$$, NULL, NULL, '["classico","historia","haydn"]'::jsonb, true, '2025-10-26 04:41:04.989877+00'::timestamptz, 10)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_quizzes (tenant_id, id, title, period_id, difficulty_level, question_type, question, options, correct_answer, explanation, audio_url, image_url, tags, is_active, created_at, points)
VALUES ('00000000-0000-0000-0000-000000000001', 'd29198ce-4d35-4d47-9948-088ce1b8e11d', $$Compositor Barroco Alemão$$, 'd8c30e03-788e-4a90-970c-7585963b3949', 1, 'multiple_choice', $$Qual compositor barroco alemão é conhecido como o "mestre da fuga"?$$, '[{"id": "a", "texto": "Handel", "correta": false}, {"id": "b", "texto": "Bach", "correta": true}, {"id": "c", "texto": "Vivaldi", "correta": false}, {"id": "d", "texto": "Telemann", "correta": false}]'::jsonb, $$Bach$$, $$J.S. Bach é considerado o mestre supremo do contraponto e da fuga, com obras como "A Arte da Fuga" e "O Cravo Bem Temperado".$$, NULL, NULL, '["barroco","compositores","bach"]'::jsonb, true, '2025-10-26 04:41:04.989877+00'::timestamptz, 10)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_quizzes (tenant_id, id, title, period_id, difficulty_level, question_type, question, options, correct_answer, explanation, audio_url, image_url, tags, is_active, created_at, points)
VALUES ('00000000-0000-0000-0000-000000000001', 'd511b968-f281-4eb0-b73b-7c5909f5d007', $$Instrumento Barroco$$, 'd8c30e03-788e-4a90-970c-7585963b3949', 2, 'multiple_choice', $$Qual instrumento era o principal responsável pelo baixo contínuo na música barroca?$$, '[{"id": "a", "texto": "Violino", "correta": false}, {"id": "b", "texto": "Flauta", "correta": false}, {"id": "c", "texto": "Cravo", "correta": true}, {"id": "d", "texto": "Oboé", "correta": false}]'::jsonb, $$Cravo$$, $$O cravo era o instrumento principal para realizar o baixo contínuo, improvisando harmonias sobre a linha de baixo cifrada.$$, NULL, NULL, '["barroco","instrumentos","teoria"]'::jsonb, true, '2025-10-26 04:41:04.989877+00'::timestamptz, 10)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_quizzes (tenant_id, id, title, period_id, difficulty_level, question_type, question, options, correct_answer, explanation, audio_url, image_url, tags, is_active, created_at, points)
VALUES ('00000000-0000-0000-0000-000000000001', 'e01f3ced-71a9-4d8c-8cdc-f5d8a47cf02c', $$Impressionismo$$, NULL, 2, 'multiple_choice', $$Qual compositor francês é considerado o pai do impressionismo musical?$$, '[{"id": "a", "texto": "Maurice Ravel", "correta": false}, {"id": "b", "texto": "Claude Debussy", "correta": true}, {"id": "c", "texto": "Erik Satie", "correta": false}, {"id": "d", "texto": "Gabriel Fauré", "correta": false}]'::jsonb, $$Claude Debussy$$, $$Debussy revolucionou a música com obras como "Prélude à l'après-midi d'un faune", usando escalas modais e harmonias inovadoras.$$, NULL, NULL, '["moderno","impressionismo","debussy"]'::jsonb, true, '2025-10-26 04:41:04.989877+00'::timestamptz, 10)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_quizzes (tenant_id, id, title, period_id, difficulty_level, question_type, question, options, correct_answer, explanation, audio_url, image_url, tags, is_active, created_at, points)
VALUES ('00000000-0000-0000-0000-000000000001', 'faa0c25b-0ab9-4d10-85da-36f89e237f7b', $$Nacionalismo Musical$$, 'e8ce8fcc-5d20-4557-be06-c908b975e141', 2, 'multiple_choice', $$Qual compositor russo é famoso pela obra "Quadros de uma Exposição"?$$, '[{"id": "a", "texto": "Tchaikovsky", "correta": false}, {"id": "b", "texto": "Rimsky-Korsakov", "correta": false}, {"id": "c", "texto": "Mussorgsky", "correta": true}, {"id": "d", "texto": "Borodin", "correta": false}]'::jsonb, $$Mussorgsky$$, $$Modest Mussorgsky compôs "Quadros de uma Exposição" originalmente para piano, depois orquestrada famosamente por Ravel.$$, NULL, NULL, '["romantico","nacionalismo","russia"]'::jsonb, true, '2025-10-26 04:41:04.989877+00'::timestamptz, 10)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_quizzes (tenant_id, id, title, period_id, difficulty_level, question_type, question, options, correct_answer, explanation, audio_url, image_url, tags, is_active, created_at, points)
VALUES ('00000000-0000-0000-0000-000000000001', 'fc71c0e3-688a-4871-8211-924f3d0bf685', $$Balé Revolucionário$$, NULL, 2, 'multiple_choice', $$Qual balé de Stravinsky causou escândalo em sua estreia em 1913?$$, '[{"id": "a", "texto": "O Pássaro de Fogo", "correta": false}, {"id": "b", "texto": "Petrushka", "correta": false}, {"id": "c", "texto": "A Sagração da Primavera", "correta": true}, {"id": "d", "texto": "Pulcinella", "correta": false}]'::jsonb, $$A Sagração da Primavera$$, $$"A Sagração da Primavera" causou tumulto em Paris por suas dissonâncias ousadas e ritmos primitivos violentos.$$, NULL, NULL, '["moderno","stravinsky","bale"]'::jsonb, true, '2025-10-26 04:41:04.989877+00'::timestamptz, 10)
ON CONFLICT (id) DO NOTHING;

INSERT INTO core.history_quizzes (tenant_id, id, title, period_id, difficulty_level, question_type, question, options, correct_answer, explanation, audio_url, image_url, tags, is_active, created_at, points)
VALUES ('00000000-0000-0000-0000-000000000001', 'fd11c498-3d02-46de-8dd7-f176c0f02cad', $$Atonalidade$$, NULL, 3, 'multiple_choice', $$Quem desenvolveu o método de composição dodecafônico?$$, '[{"id": "a", "texto": "Igor Stravinsky", "correta": false}, {"id": "b", "texto": "Arnold Schoenberg", "correta": true}, {"id": "c", "texto": "Béla Bartók", "correta": false}, {"id": "d", "texto": "Anton Webern", "correta": false}]'::jsonb, $$Arnold Schoenberg$$, $$Schoenberg criou o serialismo dodecafônico na década de 1920, um método sistemático de organizar as 12 notas cromáticas.$$, NULL, NULL, '["moderno","serialismo","schoenberg"]'::jsonb, true, '2025-10-26 04:41:04.989877+00'::timestamptz, 10)
ON CONFLICT (id) DO NOTHING;

COMMIT;